mockingbirdnest/Principia

ksp_plugin/interface.cpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/physics_bubble.cpp, ksp_plugin/physics_bubble.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/degrees_of_freedom.hpp, physics/degrees_of_freedom_body.hpp, physics/transforms_body.hpp, testing_utilities/solar_system_test.cpp
=> Change the C++ code to use the new DegreesOfFreedom wherever possible

geometry/pair.hpp, testing_utilities/componentwise.hpp, testing_utilities/componentwise_body.hpp, testing_utilities/componentwise_test.cpp
Not used in real tests yet.  Partially addresses #364.
=> Componentwise matcher for Pair

ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/degrees_of_freedom_test.cpp, physics/transforms_test.cpp, testing_utilities/componentwise_body.hpp, testing_utilities/solar_system_test.cpp
=> Use the Componentwise pair matcher in tests

base/not_null.hpp, base/not_null_body.hpp, ksp_plugin/celestial.hpp, ksp_plugin/celestial_body.hpp, ksp_plugin/physics_bubble.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/physics_bubble_test.cpp, physics/n_body_system_body.hpp, physics/n_body_system_test.cpp, physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp, physics/transforms_body.hpp, physics/transforms_test.cpp, testing_utilities/solar_system.hpp, testing_utilities/solar_system_body.hpp, testing_utilities/solar_system_test.cpp
We'll allow long lines for check_not_null.
=> First wave of changes for using not_null<>

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/logging.cs
=> Primitive recursive

physics/physics.vcxproj, physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp, serialization/physics.proto, serialization/serialization.vcxproj, serialization/serialization.vcxproj.filters
Write-only, we need `Body` to be serialized before reading this.
=> Trajectory protobuf

geometry/affine_map.hpp, geometry/affine_map_body.hpp, geometry/affine_map_test.cpp, geometry/identity.hpp, geometry/identity_body.hpp, geometry/identity_test.cpp, geometry/orthogonal_map.hpp, geometry/orthogonal_map_body.hpp, geometry/orthogonal_map_test.cpp, geometry/permutation.hpp, geometry/permutation_body.hpp, geometry/permutation_test.cpp, geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp, serialization/geometry.proto
This concludes serialization work for `geometry`.
=> Serialization of Permutation and AffineMap

physics/degrees_of_freedom.hpp, physics/degrees_of_freedom_body.hpp
=> Logging for DOF

physics/trajectory.hpp
=> Improve comments on Trajectory::Fork.

base/not_null.hpp
=> Some documentation may be out of date.

benchmarks/benchmarks.vcxproj, geometry/geometry.vcxproj, integrators/integrators.vcxproj, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj, physics/physics.vcxproj, physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp, quantities/quantities.vcxproj, testing_utilities/testing_utilities.vcxproj
=> Movable trajectory

geometry/frame_body.hpp, ksp_plugin/celestial_body.hpp, ksp_plugin/vessel_body.hpp, physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp, serialization/physics.proto
Somewhat preliminary in the sense that the serialization functions can only be called with parameters that verify tight constraints.
=> Serialization of native trajectory iterator

geometry/frame_body.hpp
=> Standardize

physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp
With an ugly `const_cast` for now.
=> Serialize/Deserialize Trajectory*

physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp, serialization/physics.proto
=> Serialization of pointers to trajectories (instead of iterators)

geometry/affine_map.hpp, geometry/affine_map_body.hpp, geometry/identity_body.hpp, geometry/orthogonal_map.hpp, geometry/orthogonal_map_body.hpp, geometry/orthogonal_map_test.cpp, geometry/r3x3_matrix.hpp, geometry/r3x3_matrix_body.hpp, geometry/r3x3_matrix_test.cpp, geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp, physics/transforms_body.hpp
=> Remove default constructor of maps and add Identity factory functions everywhere

ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/vessel_test.cpp, physics/trajectory.hpp, physics/trajectory_body.hpp, physics/trajectory_test.cpp
=> Immobilis immutabilisque

ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/vessel_test.cpp
=> is_initialized, is_synchronized

ksp_plugin_adapter/ksp_plugin_adapter.cs
Thanks to @sarbian for pointing this out.
=> Do not reallocate gigantic objects at every frame

ksp_plugin/plugin.cpp, physics/transforms.hpp, physics/transforms_body.hpp, physics/transforms_test.cpp
=> Remove usages of & on references

ksp_plugin/physics_bubble.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/plugin_test.cpp, serialization/ksp_plugin.proto
```cpp
&celestial->parent()
```
and
```cpp
&vessel->parent()
```
are #432 violations, to be fixed in a later CL.
This CL makes #431 quite obvious, to be fixed in a later CL.
=> Plugin serialization

base/base.vcxproj, base/base.vcxproj.filters, base/monostable.cpp, base/monostable.hpp, base/monostable_body.hpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/plugin.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters
=> Monostable to base::

ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_adapter/logging.cs
`PluginAdapter` was renamed since the class name is the `name` of the `SCENARIO` `ConfigNode` in which we write things, it's probably best to have the name `Principia` somewhere there.
=> Complete normed vector space

ksp_plugin/plugin.cpp
=> Reorder plugin.cpp

documentation/Setup Files/glog.patch, ksp_plugin/interface.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin_adapter/ksp_plugin_adapter.cs
Log stacktrace to all log files, and fix rotation threshold when loading from save.
=> Base address

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Detailed CTC logging

ksp_plugin_adapter/ksp_plugin_adapter.cs
Thanks to @ferram4 for reporting this!
=> Fix a bug where KSP would switch to a nonrotating reference frame while still in the atmosphere

ksp_plugin_adapter/ksp_plugin_adapter.cs
As requested by @diomedea, add a toggle to display the patched conics for comparison.
=> Prediction settings

base/bytes.hpp, base/bytes_body.hpp, base/pull_serializer.hpp, base/pull_serializer_body.hpp, base/pull_serializer_test.cpp
=> Rewrite the PullSerializer to fix nasty concurrency bugs

integrators/symplectic_partitioned_runge_kutta_integrator_body.hpp
The benchmarks in #473 should be recomputed after this CL is merged.
While it should have no effect on the harmonic oscillator, it may affect the N-body system.
=> hoist the step

physics/n_body_system_body.hpp, physics/trajectory_body.hpp
Fix #463, but probably only the @Wetmelon part.  I suspect that the @SamSchlegel part is something else entirely (wasn't able to reproduce yet).
=> Fix a bug when attempting to integrate with tmax_is_exact with tmax = end of trajectories

Principia.sln, coverage_analyser/coverage_analyser.cs, stacktrace_decoder/App.config, stacktrace_decoder/Properties/AssemblyInfo.cs, stacktrace_decoder/stacktrace_decoder.cs, stacktrace_decoder/stacktrace_decoder.csproj
Example:
```powershell
.\stacktrace_decoder\bin\Release\stacktrace_decoder.exe "https://gist.githubusercontent.com/eggrobin/8958ef1a2b394bd3ab67/raw/65a9703dd86026745bf56c51baaf64467904a226/tetryds%20INFO" "..\..\KSP_win 0.90.0\GameData\Principia\principia.pdb"
```
Output:
```markdown
[`base/map_util.hpp:50`](https://github.com/mockingbirdnest/Principia/blob/3f25c9d7bb1294ca9eda63ed19e6676bba06c34d/base/map_util.hpp#L50)
[`ksp_plugin/plugin.cpp:502`](https://github.com/mockingbirdnest/Principia/blob/3f25c9d7bb1294ca9eda63ed19e6676bba06c34d/ksp_plugin/plugin.cpp#L502)
[`ksp_plugin/plugin.cpp:262`](https://github.com/mockingbirdnest/Principia/blob/3f25c9d7bb1294ca9eda63ed19e6676bba06c34d/ksp_plugin/plugin.cpp#L262)
[`ksp_plugin/interface.cpp:311`](https://github.com/mockingbirdnest/Principia …
```
=> Stactrace decoder script

base/not_null.hpp, base/not_null_body.hpp
@Norgg confirms that this fixes #487.
=> Fix dereferencing of incomplete type

ksp_plugin_test/part_test.cpp
Adds constness, works around @Norgg's [last compile error](https://gist.github.com/Norgg/f151a95d2651018f809d), which looks like a compiler bug to me.
=> Constness and compiler bug workaround

ksp_plugin/celestial.hpp, ksp_plugin/celestial_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp
This is preparatory work for removing Ye Olde Ugly Boolean (YOUB).
=> Move the predictions into Celestial and Vessel

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_test.cpp
=> Add has_vessel and call it in the C# to avoid referencing a non-existent vessel

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, physics/n_body_system_test.cpp
Not used at the moment, but generally useful.
=> Add a utility to output a tuple in Mathematica

integrators/simple_harmonic_motion.cpp, quantities/quantities_body.hpp, quantities/quantities_test.cpp
I am hoping that this will completely fix #508 for both Linux and Mac OS X.
=> More test changes

Makefile
Also switches to git describe for zip name
=> Change Makefile packaging to include GameData dir

Principia.sln, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp, integrators/integrators.vcxproj, integrators/integrators.vcxproj.filters
https://www.google.com/search?q="explicit+embedded+runge"&hl=en
https://www.google.com/search?q="embedded+explicit+runge"&hl=en
=> D’amour mourir me font, belle marquise, vos beaux yeux

benchmarks/чебышёв_series.cpp, numerics/чебышёв_series.hpp, numerics/чебышёв_series_body.hpp, numerics/чебышёв_series_test.cpp
* Evaluation of the derivative.
* Tests at the bounds.
* Benchmark.
=> Chebyshev series improvements

integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
=> Art thou not i0, and a Montague?

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
Only Prolong, not Flow, for the time being, and with limited testing (only the Earth-Moon system).
=> First implementation of Ephemeris

geometry/grassmann.hpp
Probably fixes #568.  It's hard to know for sure because I couldn't get clang-cl to diagnose the original problem.  Thanks to *ren* and *sdrodge* for reporting.
=> Fix template parameter shadowing

Principia.sln, benchmark_automation/benchmark_automation.cs
Reverts mockingbirdnest/Principia#576
=> Let's not use CPU time.

integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/ordinary_differential_equations.hpp, integrators/symplectic_runge_kutta_nyström_integrator.hpp
See [N3797](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf), 14.6.2, paragraph 3. This is annoying.
Thanks to @Norgg for reporting this!
=> Alias declarations

benchmarks/чебышёв_series.cpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp
The choice of allowed and disallowed ranges is weird.
=> charname.allowed

integrators/symplectic_runge_kutta_nyström_integrator_test.cpp
Just moving code around.
Thanks to @Norgg for reporting this!
=> Declare things before using them

geometry/linear_map.hpp, geometry/pair_body.hpp, geometry/serialization.hpp, geometry/serialization_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/integrators.vcxproj, integrators/integrators.vcxproj.filters, integrators/ordinary_differential_equations.hpp, integrators/ordinary_differential_equations_body.hpp, integrators/srkn_integrator_test.cpp, integrators/symplectic_runge_kutta_nyström_integrator.hpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/degrees_of_freedom.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, serialization/integrators.proto, serialization/numerics.proto, serialization/physics.proto, serialization/serialization.vcxproj, serialization/serialization.vcxproj.filters, testing_utilities/solar_system.hpp, testing_utilities/solar_system_body.hpp, testing_utilities/solar_system_test.cpp
And of several other auxiliary classes: DoublePrecision, SystemState, the integrators.  And numerous small fixes here and there.
=> Serialization of Ephemeris

astronomy/gravity_models.cfg, astronomy/horizons.awk, astronomy/horizons.cfg, ksp_plugin_adapter/ksp_plugin_adapter.csproj
Thanks to @Sarbian and AmbulatoryCortex for help.
=> ModuleManager Magic

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/map_renderer.cs
Fixes #530 and makes things faster.
=> All hail sarbian

ksp_plugin/interface.cpp, physics/body.hpp, physics/body_body.hpp, physics/body_test.cpp, physics/ephemeris_test.cpp, physics/massive_body.hpp, physics/massive_body_body.hpp, physics/massless_body.hpp, physics/oblate_body.hpp, physics/oblate_body_body.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters, physics/rotating_body.hpp, physics/rotating_body_body.hpp, serialization/physics.proto, testing_utilities/solar_system_body.hpp
Complete with serialization and pre/post-Brouwer compatibility.
=> RotatingBody, a new class between MassiveBody and OblateBody in the body hierarchy

astronomy/frames.hpp, benchmarks/ephemeris.cpp, benchmarks/чебышёв_series.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, mathematica/integrator_plots.cpp, physics/ephemeris_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, quantities/parser_body.hpp, testing_utilities/solar_system.hpp, testing_utilities/solar_system_body.hpp, testing_utilities/solar_system_factory.hpp, testing_utilities/solar_system_factory_test.cpp
Not deleting testing_utilities::SolarSystem yet.
=> Replace usages of testing_utilities::SolarSystem with testing_utilities::SolarSystemFactory

Vagrantfile
Instead of @Norgg's old branch.
=> Use mockingbirdnest master on the VM

physics/body_centered_non_rotating_dynamic_frame_body.hpp, physics/dynamic_frame_test.cpp, physics/rigid_motion.hpp, physics/rigid_motion_body.hpp, physics/rigid_motion_test.cpp
And switch to saner conventions.
=> Fix a bug in the computation of the inverse of a rigid motion

physics/dynamic_frame_body.hpp
=> Fix a Clang error

geometry/grassmann_body.hpp
=> Fix Exp of a null bivector.

ksp_plugin_test/plugin_integration_test.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/continuous_trajectory_test.cpp, testing_utilities/numerics.hpp, testing_utilities/numerics_body.hpp, testing_utilities/numerics_test.cpp
=> AbsoluteError for Points.

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_test.cpp
Some more factoring might be welcome later (we compute the rotation from the Frenet frame three times), but this works.
=> In game Frenet trihedron

physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
=> Change Fork() to fail on a root trajectory

ksp_plugin/celestial.hpp, ksp_plugin/celestial_body.hpp, ksp_plugin/plugin.cpp
Don't take the address of a reference.
=> Return a pointer

base/not_null_test.cpp
Fortunately, we don't care. Fixes #722.
=> Mysterious conversion issue

ksp_plugin_test/physics_bubble_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_body.hpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
=> Change the discrete trajectory iterator to be a CRTP class to avoid the odd implicit constructor

ksp_plugin/vessel_body.hpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
=> Create a NewForkAtLast method, restructure the implementation 

ksp_plugin/interface.cpp, ksp_plugin/journal.cpp, ksp_plugin/journal.hpp, ksp_plugin/journal_body.hpp, serialization/journal.proto
=> Some more journalling.

ksp_plugin/interface.cpp, ksp_plugin/journal.cpp, ksp_plugin/journal.hpp, ksp_plugin_test/journal_test.cpp, serialization/journal.proto
Dave, my mind is going. I can feel it. I can feel it. My mind is going.
=> Journal even more things

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_adapter/reference_frame_selector.cs
The ridiculous undocumented list of celestials is no more.
=> Use the new frame selector

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/journal.cpp, ksp_plugin/journal.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, serialization/journal.proto
Also some renamings `from_snake_case` `ToCamelCase`.
=> Journal neverending stuff

ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/logging.cs, ksp_plugin_adapter/reference_frame_selector.cs
Addresses https://github.com/mockingbirdnest/Principia/pull/747#issuecomment-160334387 and uses extension methods for the interface.
=> A future PR.

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/journal.cpp, ksp_plugin/journal.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/journal_test.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, quantities/parser_body.hpp, quantities/parser_test.cpp, serialization/journal.proto
Complete with some testing.  The recording should be fully working.  Quite a bit left to do for replaying.
=> Journal at the end of the universe

Principia.sln, base/macros.hpp, journal/journal.cpp, journal/journal.hpp, journal/journal.vcxproj, journal/journal.vcxproj.filters, journal/journal_body.hpp, journal/journal_test.cpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/mock_plugin.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters
No significant code changes so far.
=> Move the journal code to a new project that runs against the Principia DLL.

journal/profiles.cpp, ksp_plugin/interface.cpp
* Enter the out pointers in the pointer map.
* Remove the pointers from the map when they are deleted.
=> Fix bugs related to journal replay

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
I hate garbage-collected languages.
=> Keep windows from accumulating when resetting the plugin

generate_version_header.ps1, tools/generate_profiles.cpp, tools/journal_proto_processor.cpp, tools/journal_proto_processor.hpp
=> Add support for generating multiple languages by peppering the code with cxx

Makefile, base/macros.hpp, journal/method_body.hpp, physics/barycentric_rotating_dynamic_frame_body.hpp
Also includes a couple minor fixes to the linux build.
=> Makefile changes to generate profile sources

journal/journal.vcxproj, journal/profiles.generated.cc, journal/recorder_test.cpp, serialization/journal.proto
Also, call the test for journal journal_tests.exe to make sure that it is run by the tools.
=> A bit of cleanup on the naming conventions of journal.proto

physics/kepler_orbit.hpp, physics/kepler_orbit_body.hpp, physics/kepler_orbit_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
Accessors for other characteristics might be nice.
=> First cut of elliptic orbits

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/manœuvre.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/manœuvre_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/discrete_trajectory_body.hpp, physics/forkable.hpp, physics/forkable_body.hpp, serialization/ksp_plugin.proto
Includes interesting bug fixes in DiscreteTrajectory and Forkable.
=> Serialization of vessels and flight plans

physics/hierarchical_system_body.hpp, physics/hierarchical_system_test.cpp
Encountered while investigating #631.
=> Hierarchical system bug

geometry/r3_element_body.hpp, journal/method.hpp, journal/method_body.hpp, journal/player.generated.cc, journal/player_test.cpp, journal/profiles.generated.cc, journal/profiles.generated.h, ksp_plugin/flight_plan.cpp, ksp_plugin/interface.cpp, ksp_plugin/interface.generated.h, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_adapter/interface.generated.cs, ksp_plugin_test/interface_test.cpp, serialization/journal.proto
Also change the interface to make sure that the journal may be replayed.
=> Fix a crash in the deserialization of manoeuvres

journal/player.cpp, journal/player_test.cpp, ksp_plugin/interface.cpp, ksp_plugin/interface_body.hpp
* Do not replay `InitGoogleLogging`, and deprecate its journalling.
* Properly handle `NaN`s in replay checks.
=> Fix bugs found while making a journal for PGO purposes

journal/method_body.hpp, journal/player_test.cpp, journal/recorder.cpp, journal/recorder.hpp, journal/recorder_test.cpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/logging.cs, ksp_plugin_test/interface_test.cpp
=> Add a new parameter to enable "verbose" journalling

Makefile, ksp_plugin_test/mock_manœuvre.hpp
The `journal` and `ksp_plugin` tests compiled nothing, and tested nothing. All tests now pass.
=> Linux madness

ksp_plugin/plugin.cpp, ksp_plugin_test/celestial_test.cpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/body_test.cpp, physics/ephemeris_test.cpp, physics/hierarchical_system_test.cpp, physics/jacobi_coordinates_body.hpp, physics/jacobi_coordinates_test.cpp, physics/ksp_system_test.cpp, physics/massive_body.hpp, physics/massive_body_body.hpp, physics/oblate_body_body.hpp, physics/resonance_test.cpp, physics/rotating_body.hpp, physics/rotating_body_body.hpp, physics/solar_system_body.hpp, serialization/astronomy.proto, serialization/physics.proto
For ease of review, it might be best to compare the latest state with 3e47f259d8b72c757bf11ac3f3d7e6aba63d1e5d.
=> Undo some of #885 by moving mean_radius down to RotatingBody

stacktrace_decoder/stacktrace_decoder.cs
Because sometimes we segfault.
=> Support for Unity stack traces

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/mock_ephemeris.hpp, serialization/ksp_plugin.proto
And a flight plan that doesn't crash. Fixes #846.
=> Max steps in flow

journal/player.cpp, journal/player.hpp, journal/player_test.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin_test/plugin_test.cpp
=> Another attempt at fixing #872

geometry/grassmann.hpp, geometry/grassmann_body.hpp, geometry/r3_element.hpp, geometry/r3_element_body.hpp, ksp_plugin/burn.cpp, ksp_plugin/manœuvre_body.hpp
Fix #854.  This is journal-incompatible.
=> Add NormalizeOrZero and call it.

ksp_plugin/flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/plugin_test.cpp
=> Encapsulate vessel operations and use the prediction to decide when to forget

ksp_plugin_adapter/boxed.cs, tools/journal_proto_processor.cpp
Things now work in the game (the strings are fine too, no issues there).
=> No generic marshals

astronomy/eclipse_test.cpp, benchmarks/dynamic_frame.cpp, benchmarks/ephemeris.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/ksp_system_test.cpp, physics/mock_ephemeris.hpp, physics/resonance_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, serialization/journal.proto
No semantic changes at this point.  In particular, `max_steps` is still hard-wired to 1000.  Partially addresses #911.
=> Wrap the parameters of the Ephemeris functions into parameter classes

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/mock_vessel.hpp, ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/discrete_trajectory.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
=> Remove vessel synchronization

ksp_plugin/vessel_body.hpp, physics/ephemeris_body.hpp, serialization/ksp_plugin.proto
From trying it out in-game.
Apparently when running things from VS (which differs from what Jenkins does, Jenkins works in a UTF-8 cmd) protoc wants BOMless UTF-8 (but MSVC wants BOMed UTF-8). BOM the C++, don't BOM the proto.
=> A build issue, a bug, and checks that can't hurt

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, serialization/ksp_plugin.proto
Also rearrange the serialization between Vessel and Plugin.  Fixes #844.
=> Do not serialize the prediction, recompute it instead

physics/ephemeris.hpp, physics/ephemeris_body.hpp
=> Cleanup of Ephemeris code

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/loader.cs
=> Error messages

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_vessel.hpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, serialization/ksp_plugin.proto
Not very deep, but at least it gives us 100% coverage.  Fix #914.
=> A decent unit test for Vessel

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/plugin_compatibility_test.cpp
=> Change SetAdaptiveStepParameters to preserve the invariants of FlightPlan

journal/profiles.hpp, ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_flight_plan.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, serialization/journal.proto, tools/journal_proto_processor.cpp, tools/journal_proto_processor.hpp
A first step towards solving #938.
=> Expose function to set and get the flight plan parameters to the C# code

physics/discrete_trajectory_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp
This is the physical computation for addressing #953.
=> Compute the apsides of a trajectory

journal/method.hpp, journal/method_body.hpp, journal/recorder_test.cpp
With some not-entirely-trivial helper traits.
=> Stronger SFINAE conditions

journal/profiles.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_iterator.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, serialization/journal.proto
Keeping `LineSegment` for the time being, will be removed in a later PR.
=> A more principled API for exchanging container through the interface

ksp_plugin_adapter/ksp_plugin_adapter.cs
Otherwise moving the camera around becomes difficult and the stock manœuvre nodes which we use for guidance break down.
=> Don't kill off too much of the game

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs
=> Only show apsides with respect to the fixed body, if any.

base/push_deserializer_body.hpp
On the one hand, 512 MiB is biggish and it will take a while to deserialize.  On the other hand, there is no security risk with loading a large protocol buffer (worst case, the game will crash).  On the third hand, there is really no reason to penalize users who have large saves.  On the fourth hand, we'll want to avoid creating such large saves.  On the fifth hand, that's way too many hands.
Fix #964.
=> Bump the protocol buffer deserialization limit to 512 MiB

base/pull_serializer_test.cpp, base/push_deserializer_test.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/flight_plan_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp, serialization/ksp_plugin.proto, serialization/physics.proto
Also rename a protocol buffer.  This is the first step towards solving #972.
=> Add DetachFork and NewForkWithoutCopy

ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs
Progress on #869: dashing and fading, switching the flight plan to a more visible colour. Configurable colours still need to be added.
=> Colours and style

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/plugin_test.cpp, serialization/ksp_plugin.proto
=> Change ForgetBefore to actual truncate the prediction and flight plan

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_flight_plan.hpp, serialization/journal.proto, serialization/ksp_plugin.proto
=> C++ support for accessing the actual final time (as opposed to the desired one)

astronomy/astronomy.vcxproj, physics/forkable_body.hpp
Also enable coverage for astronomy.
Fix #1000.
=> Fix a bug in AttachForkToCopiedBegin

ksp_plugin/manœuvre_body.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp, quantities/quantities_test.cpp
=> IsFinite for quantities

Principia.sln, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_integration_test.cpp, serialization/journal.proto
=> Full step^Wset of parameters for the prediction

physics/ephemeris_test.cpp
=> Linux tolerances

ksp_plugin/vessel_body.hpp, physics/ephemeris_body.hpp
=> Wreorder fixes

physics/ephemeris_body.hpp
Also add `CHECK`s to verify that the intermediate states make sense.
=> Remove unneeded intermediate states in ForgetBefore

ksp_plugin/flight_plan.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/resonance_test.cpp
Also some minor improvements to `FlightPlan`.
Fix #1024.
=> Short-circuit FlowWithAdaptiveStep when it doesn't advance time

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, serialization/journal.proto
=> Set prediction adaptive step parameters per vessel

ksp_plugin_test/plugin_test.cpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, serialization/physics.proto
=> Only persist minimal data for the Ephemeris and recompute the rest

journal/profiles.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/boxed.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, serialization/journal.proto, tools/journal_proto_processor.cpp, tools/journal_proto_processor.hpp
=> Remove InsertSun and use InsertCelestialJacobiKeplerian instead

ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_test.cpp, serialization/journal.proto
=> New interface function to compute the velocity in the plotting frame

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs
Fix an issue, maybe fix another one, address an old TODO, more informative window title and button text for the reference frame selectors.
=> Cleaning the KSP-side lavatory

base/fingerprint2011.hpp, journal/profiles.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/boxed.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, physics/kepler_orbit.hpp, physics/kepler_orbit_body.hpp, serialization/journal.proto, serialization/ksp_plugin.proto, serialization/physics.proto
=> Expose a predicate to check exactly if the system is the KSP stock system

journal/profiles.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin_adapter/boxed.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto, tools/journal_proto_processor.cpp
=> Put the journalling messages in their own namespace to resolve name conflicts

ksp_plugin_adapter/loader.cs
=> Better check that the C++ runtime is installed

geometry/affine_map_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/symplectic_runge_kutta_nyström_integrator.hpp, integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/manœuvre_test.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/continuous_trajectory_test.cpp, physics/dynamic_frame.hpp, physics/dynamic_frame_test.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/ksp_system_test.cpp, testing_utilities/solar_system_factory_test.cpp
=> Use Clang-style comments

ksp_plugin/physics_bubble.cpp, ksp_plugin/plugin.cpp, ksp_plugin_test/plugin_test.cpp, physics/continuous_trajectory_body.hpp
=> Fix pairs in loops

astronomy/astronomy.vcxproj, astronomy/astronomy.vcxproj.filters, astronomy/epoch.hpp, astronomy/epoch_body.hpp, astronomy/lunar_eclipse_test.cpp, astronomy/mercury_perihelion_test.cpp, geometry/geometry.vcxproj, geometry/geometry.vcxproj.filters, geometry/point_test.cpp, ksp_plugin_test/interface_test.cpp, physics/kepler_orbit_test.cpp, physics/solar_system_body.hpp, tools/generate_configuration.cpp, tools/main.cpp
=> Move epoch to astronomy

astronomy/gravity_model.cfg, astronomy/gravity_model.proto.txt, astronomy/gravity_model_two_bodies_test.proto.txt, ksp_plugin/interface.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, physics/ephemeris_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, serialization/astronomy.proto, serialization/journal.proto, testing_utilities/solar_system_factory.hpp, testing_utilities/solar_system_factory_body.hpp, testing_utilities/solar_system_factory_test.cpp, tools/generate_configuration.cpp
Reverts mockingbirdnest/Principia#1078
=> Revert "Add complete data for rotating bodies and parse it when building a solar system"

astronomy/date_body.hpp, astronomy/date_test.cpp
Thanks to @pdn4kd for the notification.
See Bulletin C 52:
[IERS](https://datacenter.iers.org/eop/-/somos/5Rgv/getTX/16/bulletinc-052.txt)
[Observatoire de Paris](https://hpiers.obspm.fr/iers/bul/bulc/bulletinc.52)
=> Bulletin C 52

astronomy/epoch.hpp, astronomy/epoch_body.hpp, ksp_plugin_test/vessel_test.cpp, physics/continuous_trajectory_body.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp
=> Infinities for Instant

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, physics/rotating_body_body.hpp, serialization/physics.proto
=> Pre-cardano compatibility

astronomy/frames.hpp, astronomy/solar_system_dynamics_test.cpp, geometry/r3_element.hpp, geometry/r3_element_body.hpp, geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp, ksp_plugin/plugin.cpp, ksp_plugin_test/physics_bubble_test.cpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/kepler_orbit_body.hpp
=> Euler and Cardan

ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/manœuvre_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/barycentric_rotating_dynamic_frame.hpp, physics/barycentric_rotating_dynamic_frame_body.hpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centered_non_rotating_dynamic_frame.hpp, physics/body_centered_non_rotating_dynamic_frame_body.hpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/body_centred_body_direction_dynamic_frame.hpp, physics/body_centred_body_direction_dynamic_frame_body.hpp, physics/body_centred_body_direction_dynamic_frame_test.cpp, physics/dynamic_frame_body.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters, serialization/physics.proto
First part of implementing #995.
=> A body-centred, body-direction frame

ksp_plugin/interface.cpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_test.cpp, serialization/journal.proto
Also remove two obsolete interface functions.
=> Expose the new frames through the interface

base/base.vcxproj, base/base.vcxproj.filters, base/disjoint_sets.hpp, base/disjoint_sets_body.hpp, base/disjoint_sets_test.cpp
One Ring to find them, One Ring to bring them all and in the darkness bind them.
=> Union find

ksp_plugin_adapter/ksp_plugin_adapter.cs
A tiny diagnosis field; we may want to remove that later, but for now it's semi-useful and a good reference snippet.
=> Report collisions

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/plugin_test.cpp
=> TestablePlugin now knows much less about Plugin.

integrators/symplectic_runge_kutta_nyström_integrator.hpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp
Minor changes in `SymplecticRungeKuttaNyströmIntegrator`.
=> Constexpr and simpler logic

base/map_util.hpp, base/not_null.hpp, base/not_null_body.hpp, geometry/grassmann.hpp, geometry/grassmann_body.hpp, geometry/pair.hpp, geometry/pair_body.hpp, geometry/rotation.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, quantities/quantities_body.hpp
=> Remove some obsolete NOLINTs

geometry/pair_test.cpp, quantities/cgs.hpp, quantities/elementary_functions_body.hpp, quantities/named_quantities.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp, quantities/quantities_test.cpp, quantities/si.hpp, testing_utilities/componentwise_test.cpp
Remove `Winding`, make `SolidAngle` the square of `Angle`. `Degree * Degree` is now the square degree. This fixes #1167.
=> Winding down

ksp_plugin/physics_bubble.cpp, ksp_plugin/physics_bubble.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/mock_plugin.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/physics_bubble_test.cpp, ksp_plugin_test/plugin_test.cpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/resonance_test.cpp
See #1174. There were some copies!
=> Pass by rvalue reference

base/get_line.hpp, base/get_line_body.hpp, base/pull_serializer_test.cpp, base/push_deserializer_test.cpp, journal/player.cpp, journal/player_body.hpp, journal/profiles.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/mock_flight_plan.hpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_test.cpp, mathematica/mathematica_body.hpp, numerics/чебышёв_series_test.cpp, physics/barycentric_rotating_dynamic_frame.hpp, physics/barycentric_rotating_dynamic_frame_body.hpp, physics/body_centred_body_direction_dynamic_frame.hpp, physics/body_centred_body_direction_dynamic_frame_body.hpp, physics/ephemeris_test.cpp, tools/journal_proto_processor.cpp
=> Pass by reference

base/optional_logging.hpp, base/status_or.hpp, base/unique_ptr_logging.hpp, base/unique_ptr_logging_body.hpp, geometry/affine_map_body.hpp, geometry/r3_element_body.hpp, integrators/symmetric_linear_multistep_integrator.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_test/mock_manœuvre.hpp, numerics/hermite3_body.hpp, numerics/root_finders.hpp, physics/discrete_trajectory.hpp, physics/ephemeris_body.hpp, physics/forkable_body.hpp, quantities/quantities.hpp
=> Remove spaces

astronomy/solar_system_dynamics_test.cpp, physics/kepler_orbit_body.hpp, quantities/constants.hpp, quantities/named_quantities.hpp, quantities/quantities_test.cpp, testing_utilities/solar_system_factory_test.cpp
=> Fix incorrect Torque and related quantities

mathematica/generate_graphs.wl, mathematica/integrator_plots.cpp, mathematica/main.cpp
We had 18 500 independent problems for each set of graphs (position-velocity-energy), so this falls under "embarrassingly parallel".
=> Parallel integrator plots

ksp_plugin_adapter/ksp_plugin_adapter.cs
Moved code around, added callbacks with commented stubs.
=> Reordering and commenting in preparation for pile-ups

Makefile
=> gtest reorg

base/not_null_test.cpp, coverage_analyser/coverage_analyser.csproj
We had a dependency on Visual Studio 12.0 somewhere...
=> New versions

coverage_analyser/coverage_analyser.csproj, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/mock_vessel.hpp, ksp_plugin_test/pile_up_test.cpp, serialization/geometry.proto
Not connected to the plugin or the C# code yet.
=> Add methods to inform the pile-up of the apparent positions of vessels and to help nudge them

journal/profiles.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, serialization/journal.proto
The interface for the functions introduced in #1220.
This makes `ksp_plugin` build again.
=> Interface for part-based pile ups

ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Utterly untested of course. But it builds.
=> Through to the adapter

ksp_plugin/identification.hpp, ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
`PileUp` serialization should be nicer now.
=> Get rid of the dummies, and notice a few incorrect things

ksp_plugin/interface.cpp, ksp_plugin/part.cpp, ksp_plugin/part.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/ksp_plugin.proto
Fix some bug and uncover others; the C# has some traces that I'm going to need as soon as things stop crashing below it, so I'm keeping them; the INFO traces on the C++ should stay, because they're for part creation/transfer/destruction, which should not be overly spammy.
=> Test the things

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp
=> Give the PileUp a real psychohistory so that NudgeParts doesn't lag behind

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/pile_up_test.cpp, ksp_plugin_test/plugin_test.cpp, serialization/ksp_plugin.proto
The integration test is not there yet.
=> Implement serialization of the Plugin and reinstate more tests

journal/player_test.cpp, ksp_plugin/interface.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
And expose journalling in the logging UI.
=> Remove noisy traces

ksp_plugin/plugin.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Use wet masses

ksp_plugin/interface.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
This should remove one out of three calls to CelestialRotation; I will see whether that can be brought down to 1 with a test system with tilt.
=> Timing and miscellaneous C# issues

ksp_plugin/interface.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
=> Let's try to stay consistent in how we name the interface methods

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
It is not a good idea to go through all the objects at 50 Hz.
=> Profile kraken

ksp_plugin/interface.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Another attempt at putting those calls in the right order.
=> Advance parts

ksp_plugin_adapter/ksp_plugin_adapter.cs
This is likely to be replaced by per-vessel plotting frames, persisted C++-side eventually, but it's very annoying right now.
=> Do not default to heliocentric

ksp_plugin/plugin.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, physics/body_surface_dynamic_frame.hpp, physics/body_surface_dynamic_frame_body.hpp
Which is flipped, as it happens.
=> The surface navball

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #1272, and probably our handling of airless worlds too.
=> Dämmerungsgötterdämmerung

ksp_plugin/plugin.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
Most of the commits here are traces to investigate the (unrelated) docking bug, which I think I understand now.
=> Don't spam vessel creations and deletions

ksp_plugin_adapter/ksp_plugin_adapter.cs
This fixes the bug with collisions with non-parts (which raised a nullreference exception), as well as the bug with collisions leading to explosions (3 should be 33).
There was an indent change too, so use https://github.com/mockingbirdnest/Principia/pull/1281/files?w=1 to disregard whitespace.
=> Eggsceptions

ksp_plugin_adapter/flight_planner.cs
Another issue with the patched conics being null.
=> Career flight plan

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/mock_continuous_trajectory.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters, physics/trajectory.hpp
=> Abstract Trajectory

ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, serialization/journal.proto
UI refinements are needed, but plotting the trajectory works.
=> LVLH frame through to the C#

integrators/integrators.hpp, integrators/symmetric_linear_multistep_integrator.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp, ksp_plugin/integrators.cpp, ksp_plugin/integrators.hpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/pile_up_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/mock_ephemeris.hpp, serialization/integrators.proto
Some code restructuring and bugs fixes in the startup phase.
=> Use a multistep integrator to compute histories

ksp_plugin/plugin.cpp
Unfortunately, they will probably change again in Cartan...
=> Correct fingerprints for Cardano

ksp_plugin/interface.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/apsides.hpp, serialization/journal.proto
Also a bit of renaming and restructuring.
=> Expose the ascending/descending nodes in the interface

base/not_null.hpp, benchmarks/dynamic_frame.cpp, benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp, benchmarks/hexadecimal.cpp, benchmarks/quantities.cpp, benchmarks/symplectic_runge_kutta_nyström_integrator.cpp, benchmarks/чебышёв_series.cpp, geometry/grassmann_test.cpp, journal/player_test.cpp, mathematica/retrobop_dynamical_stability.cpp, physics/forkable.hpp, physics/massive_body.hpp, tools/generate_profiles.cpp
=> Remove useless NOLINTs.

astronomy/astronomy.vcxproj, astronomy/astronomy.vcxproj.filters, astronomy/lunar_eclipse_test.cpp, astronomy/молния_orbit_test.cpp, mathematica/молния_orbit.wl
=> A test for Молния orbits

astronomy/ksp_fingerprint_test.cpp, astronomy/ksp_resonance_test.cpp, astronomy/ksp_system_test.cpp, astronomy/lunar_eclipse_test.cpp, astronomy/mercury_perihelion_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/молния_orbit_test.cpp, benchmarks/dynamic_frame.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centred_body_direction_dynamic_frame_test.cpp, physics/body_centred_non_rotating_dynamic_frame_test.cpp, physics/body_surface_dynamic_frame_test.cpp, physics/ephemeris_test.cpp, physics/kepler_orbit_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, testing_utilities/solar_system_factory_body.hpp, tools/generate_configuration.cpp
Also replace the `Initialize` method with a constructor.  This is preparatory work for using SolarSystem in the Plugin.
=> Make it possible to construct a SolarSystem from protocol buffers

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Fix airless landings

ksp_plugin_adapter/ksp_plugin_adapter.cs
We were setting degrees of freedom in the KCI frame where KSP was expecting them in the KCKF frame.
=> Fix #1366.

ksp_plugin/manœuvre_body.hpp, ksp_plugin/plugin.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centred_body_direction_dynamic_frame_test.cpp, physics/body_centred_non_rotating_dynamic_frame_test.cpp, physics/body_surface_dynamic_frame_test.cpp, physics/dynamic_frame.hpp, physics/dynamic_frame_body.hpp
=> Reorder parameters in dynamic frame deserialization

ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, testing_utilities/actions.hpp
The interface test is getting too big.  This is a fragment of #1374.
=> Split the flight plan test out of the main interface test

ksp_plugin/interface.cpp, ksp_plugin/interface_renderer.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin_test/interface_renderer_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, testing_utilities/actions.hpp, testing_utilities/testing_utilities.vcxproj, testing_utilities/testing_utilities.vcxproj.filters
=> Split the rendering-related code out of the main interface and test code

Vagrantfile
The old one crashed while building a test for some reason.
=> Use clang 4.0

ksp_plugin/interface.cpp, ksp_plugin_test/plugin_test.cpp, physics/solar_system_body.hpp, quantities/parser.hpp, quantities/parser_body.hpp, quantities/parser_test.cpp
=> A better parser for units

quantities/bipm.hpp, quantities/constants.hpp, quantities/elementary_functions.hpp, quantities/elementary_functions_body.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp, quantities/si.hpp, quantities/uk.hpp
* Some reordering of the headers.
* Move the elementary functions to `elementary_functions.hpp`.
=> Cleanup of quantities

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Skip a couple of frames when the vessel isn't quite ready

ksp_plugin_adapter/ksp_plugin_adapter.cs
Also removed the build date, since it's not a build date anymore (it's just the commit date), so it doesn't tell us anything that the commit number wouldn't.
=> Make the beach towel a bit smaller

ksp_plugin_adapter/ksp_plugin_adapter.cs
Hidden away in the KSP features section of the beach towel since it's there only for third-party compatibility and we plan to handle some of the features that require it ourselves eventually.
=> Celestial targeting

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Render the trajectory of the target in target-mobile frames

astronomy/epoch.hpp, journal/player_test.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp
=> Bail out early if the psychohistory is already long enough

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Æthelred Kerman

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Mysterious null collider

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Ælfgifu Kerman

Makefile, quantities/elementary_functions_test.cpp
=> Fix problems with the Linux build.

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Plot the trajectory of the selected vessel in the tracking station

documentation/Releasing.md, ksp_plugin_adapter/ksp_plugin_adapter.cs
=> A lunar reminder to update Principia

ksp_plugin/burn.cpp, ksp_plugin/burn.hpp, ksp_plugin/flight_plan.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/manœuvre.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/manœuvre_test.cpp, ksp_plugin_test/mock_manœuvre.hpp, ksp_plugin_test/plugin_test.cpp, serialization/journal.proto, serialization/ksp_plugin.proto
A first cut of #876. From the features side of things, the "show on navball" functionality needs to work differently in that case.
Subsequently, the implementation should be changed to properly integrate the velocity-dependent acceleration.
=> Track the trihedron

ksp_plugin_adapter/ksp_plugin_adapter.cs
This is a repeat of #1258 essentially...
=> Don't do stupidly slow things in space centre view.

ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/planetarium_test.cpp, serialization/journal.proto
It drops about 90% of the point, but unfortunately, the performance is worst than in Cayley...
Related to #973, again.
=> Implementation of method #1

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp, ksp_plugin_adapter/flight_planner.cs, serialization/journal.proto
=> Track the trihedron if appropriate when showing a manœuvre on the navball

base/array.hpp, base/array_body.hpp, base/array_test.cpp, geometry/perspective_body.hpp, numerics/root_finders_body.hpp
=> A constructor for BoundedArray

geometry/perspective_body.hpp, geometry/perspective_test.cpp
=> Handle the case where a segment is seen under a very small angle

ksp_plugin/planetarium.cpp
=> A tale of tangent bundles

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs
Fix #1453.
Also use geocentric by default in the tracking station, rather than heliocentric.
=> Παλαιολόγος

ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_test/planetarium_test.cpp
=> A limit on the number of points emitted by PlotMethod2

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/pile_up_test.cpp, serialization/ksp_plugin.proto
First step towards solving #1513.
=> Use forks to represent the psychohistory in PileUp

ksp_plugin/part.cpp, ksp_plugin/part.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/vessel.cpp, ksp_plugin_test/part_test.cpp, ksp_plugin_test/pile_up_test.cpp, physics/forkable_body.hpp, serialization/ksp_plugin.proto
This is the second part of #1513.
=> Add pre/psycho/history to Part

mathematica/floating_point.wl
=> Some utilities to analyse rounding errors

ksp_plugin/interface_future.cpp, ksp_plugin/interface_monitor.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, serialization/journal.proto
Only a single untitled monitor for now, we may want to have something cleaner later on.
=> Make the monitor accessible from C#

ksp_plugin_adapter/ksp_plugin_adapter.cs
Putting the AdvanceTime back in Early where it was in Чебышёв.
=> Another bug found by manual testing at the last minute

ksp_plugin_adapter/reference_frame_selector.cs
=> Don't toggle expanded_ for a leaf celestial

geometry/barycentre_calculator.hpp, geometry/pair.hpp, geometry/pair_body.hpp, geometry/point.hpp
=> Replace decltype by Product or Quotient

base/array_body.hpp, ksp_plugin_test/interface_renderer_test.cpp, quantities/parser_body.hpp
=> Fix the remaining warnings

journal/profiles.hpp, ksp_plugin/frames.hpp, ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/geometry.proto, serialization/journal.proto
3rd point of the 10-point plan.
=> Correctly handle the Krakensbane and floating origin, unpacked part insertion

ksp_plugin_adapter/ksp_plugin_adapter.cs
Point 5 of the 10-point plan, tested as part of point 6.
=> Ignore vessels that touch the ground or might fall underground, remove altitude thresholds

ksp_plugin/plugin.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Ground pile ups, and handle clambering

ksp_plugin_adapter/map_node_pool.cs
Working around a KSP bug...
Screenshot of the bug in action:
=> Do not reuse map nodes for another type

ksp_plugin_adapter/ksp_plugin_adapter.cs
Not sure whether we want this in Chasles, but it seems cleaner and faster, and should provide better logs.
Note that I could not reproduce the mysteriously ground-colliding Kerbal, so at least we would have more detailed traces if it came back.
Also note that this should not spam about vessels that are firmly on the ground, as those have the state LANDED, so will be unmanageable regardless of collisions.
=> Handle collisions with scenery as collisions

Makefile, install_deps.sh
only good build box is still 10.11 so this has to be the floor for now.
=> only support macosx >= 10.11

ksp_plugin_adapter/flight_planner.cs
=> Ensure flight planner is always (partially) visible

ksp_plugin/vessel.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, serialization/physics.proto
This is part of the work on #228.
=> Downsampling trajectories

ksp_plugin/vessel.cpp, physics/discrete_trajectory_body.hpp
Fix #228, finally.
Also some C++ grammatical warts.
=> Use the downsampling

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #1618.
We don't have a save, so this is not tested, but the trace looks similar enough to #1447 that we can reasonably guess that this is the issue.
=> #1618 is the new #1447

ksp_plugin_adapter/loader.cs
=> libc++ version and removal of 32-bit support

integrators/backward_difference.hpp, integrators/backward_difference_body.hpp, integrators/integrators.vcxproj, integrators/integrators.vcxproj.filters, mathematica/fornberg.wl
This is the first step in addressing #1628.
=> Tables for finite differences computations

benchmarks/ephemeris.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/pile_up_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/mock_ephemeris.hpp
For now, swallowing the collisions.
=> Change FlowWithAdaptiveStep to return a status, just like FlowWithFixedStep

ksp_plugin/plugin.cpp
=> Capture by copy

ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp
=> Report collisions with a celestial

numerics/fit_hermite_spline_body.hpp, numerics/fit_hermite_spline_test.cpp
=> Make the downsampling iterative and add a check

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Remove the broken option to force stop/start.

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Use the current time

numerics/double_precision_body.hpp
This fixes the interesting part of #1624.
=> Incorrect sign in DoublePrecision difference of points

Principia.sln, google_googletest.props, rebuild_all_solutions.ps1
This requires to pull master from all our forks of the Google repositories.
=> Change the location of googletest

journal/profiles.hpp, ksp_plugin/integrators.cpp, ksp_plugin/integrators.hpp, ksp_plugin/interface.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/config_node_extensions.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_test/pile_up_test.cpp, quantities/parser_body.hpp, serialization/journal.proto, serialization/ksp_plugin.proto
=> Custom integrators

ksp_plugin_adapter/ksp_plugin_adapter.cs
#1667 had an incorrect null check that prevented the stock game from loading. Fix forward and catch the exception so the error isn't reported as a null plugin in a call to a plugin member.
=> Null check the right way

benchmarks/newhall.cpp, numerics/newhall.hpp, numerics/newhall_body.hpp, numerics/newhall_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
This doesn't do much, but it's in preparation of moving to a monomial basis, where computing an error estimate will be real work.
=> Change the Newhall approximation to return the error estimate

testing_utilities/is_near.hpp, testing_utilities/is_near_body.hpp, testing_utilities/is_near_test.cpp, testing_utilities/testing_utilities.vcxproj, testing_utilities/testing_utilities.vcxproj.filters
=> A new matcher to check that a value is near another one

numerics/newhall.hpp, numerics/newhall_body.hpp, numerics/newhall_test.cpp, numerics/polynomial.hpp
… and returns the base class.  This is the one we'll use in `ContinuousTrajectory`.
=> A version of the Newhall approximation that takes a nonconstant degree

benchmarks/polynomial.cpp, geometry/point_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, quantities/quantities_body.hpp, serialization/numerics.proto
This requires a change in the way that quantities exponents are serialized, because we need to support large negative exponent.  Hopefully this won't be save-incompatible as we probably never used large positive exponents.
=> Polynomial serialization, part 1: writing

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp
Error message:
./numerics/fixed_arrays_body.hpp:122:46: error: use 'template' keyword to treat 'Row' as a dependent
template name
typename FixedMatrix<Scalar, rows, columns>::Row<r>
^
template
=> Fix error reported by Clang

numerics/newhall_body.hpp
Lo and behold!  This removes code!
=> Use macros for the repetitive code in Newhall

testing_utilities/solar_system_factory_body.hpp
Reported by @lamont-granquist.
=> Remove stray static

base/macros.hpp, principia.props
And turn Microsoft extension warnings into errors.
=> Clean up clang-cl warnings

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
=> Make sure that all windows stay on screen (a bit)

documentation/Setup.md
googlemock was merged into googletest some time ago
=> Remove separate googlemock dep from Setup.md

journal/player_test.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp
=> Disable downsampling after a collision

ksp_physics/ksp_physics_lib.hpp
This bloated the Linux Cohen binary, let's make Coxeter more reasonable.
=> Ifdef out the explicit instantiations on *nix

documentation/bibliography.tex
Hello!
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).
Cheers :-)
=> link DOIs against preferred resolver

quantities/dimensions.hpp, quantities/dimensions_body.hpp, quantities/generators.hpp, quantities/generators_body.hpp, quantities/named_quantities.hpp, quantities/parser_body.hpp, quantities/quantities.hpp, quantities/quantities.vcxproj, quantities/quantities.vcxproj.filters, quantities/quantities_body.hpp
=> Split quantities into three parts to make the code more manageable

integrators/backward_difference.hpp, integrators/backward_difference_body.hpp, integrators/cohen_hubbard_oesterwinter.hpp, integrators/cohen_hubbard_oesterwinter_body.hpp, integrators/integrators.vcxproj, integrators/integrators.vcxproj.filters, integrators/symmetric_linear_multistep_integrator.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp, mathematica/cohen_hubbard_oesterwinter.wl
and a fix for the order of the backward difference method.
=> Coefficients for Cohen-Hubbard-Oesterwinter

ksp_plugin_adapter/ksp_plugin_adapter.cs
Need to keep the old code around so versions of Principia for 1.2.2 and
1.3.1 still build
=> Limit texture2d.LoadImage change to KSP 1.4.1 only

astronomy/astronomy.vcxproj, astronomy/astronomy.vcxproj.filters, ksp_plugin_adapter/ksp_plugin_adapter.csproj
This was a regression in Coxeter.
=> Release the numerics blueprint for RSS

integrators/integrators_body.hpp, integrators/methods.hpp, integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp
=> Support for ABA composition

ksp_plugin_adapter/loader.cs
=> 2017 Redistributable runtime

astronomy/time_scales_test.cpp, base/not_null_test.cpp
=> Upgrade to Preview 4

base/file_body.hpp
=> Filesystem is complete starting with Preview 3

ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/utf16_marshaler.cs, ksp_plugin_adapter/utf8_marshaler.cs, tools/journal_proto_processor.cpp
=> A marshmallow for a UTF-16 string whose ownership is taken by the caller

benchmarks/base32768.cpp, benchmarks/hexadecimal.cpp
```
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
BM_HexadecimalEncode            145259 ns     181469 ns       7479   341.597MB/s
BM_HexadecimalEncode            144936 ns     131409 ns       7479    471.73MB/s
BM_HexadecimalEncode            144943 ns     127237 ns       7479   487.196MB/s
BM_HexadecimalEncode            145334 ns     123065 ns       7479   503.711MB/s
BM_HexadecimalEncode            144945 ns     141838 ns       7479   437.044MB/s
BM_HexadecimalEncode            145340 ns     152267 ns       7479   407.109MB/s
BM_HexadecimalEncode            147007 ns     148096 ns       7479   418.577MB/s
BM_HexadecimalEncode …
```
=> Benchmark for hex encoding

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Fix a memory leak in flight plan rendering

ksp_plugin_adapter/disposable.cs, ksp_plugin_adapter/disposable_marshaller.cs, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
=> Disposable planetarium

geometry/r3x3_matrix.hpp, geometry/r3x3_matrix_body.hpp, geometry/r3x3_matrix_test.cpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp
This is the first very small step towards addressing #1639.
=> Change R3x3Matrix to support a scalar type

geometry/geometry.vcxproj, geometry/geometry.vcxproj.filters, geometry/r3x3_matrix.hpp, geometry/r3x3_matrix_body.hpp, geometry/r3x3_matrix_test.cpp, geometry/symmetric_bilinear_form.hpp, geometry/symmetric_bilinear_form_body.hpp, geometry/symmetric_bilinear_form_test.cpp
Without serialization for now.
=> Symmetric bilinear forms

ksp_physics/ksp_physics_lib.cpp, stacktrace_decoder/stacktrace_decoder.cs
Also, we might as well print out the base address for`physics.dll`.
=> Fix the stack decoder to read from both principia.pdb and physics.pdb

integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
Even if funky rounding would cause small over/undershoot.
Fix #1839.
Fix #1864.
=> Make sure that the integrator complies with last_step_is_exact

astronomy/trappist_gravity_model.cfg, astronomy/trappist_gravity_model.proto.txt, astronomy/trappist_gravity_model_slippist1.cfg, astronomy/trappist_initial_state_jd_2457000_000000000.cfg, tools/generate_configuration.cpp, tools/generate_kopernicus.cpp
We may also need to do something about EVE clouds if @gregroxmun uses those.
=> TRAPPIST-1 rescalings

astronomy/date_time.hpp, astronomy/date_time_body.hpp, base/macros.hpp
=> Convert Date, Time, and DateTime to use moderner C++

astronomy/date_time_body.hpp
=> Date and time parser converted to C++17

astronomy/time_scales_body.hpp, base/macros.hpp
=> Convert time scales to C++17

astronomy/time_scales_body.hpp, astronomy/time_scales_test.cpp, benchmarks/planetarium_plot_methods.cpp
=> Support for Julian dates in TAI and UT1

geometry/cartesian_product.hpp, geometry/cartesian_product_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, quantities/tuples.hpp, quantities/tuples_body.hpp
Paddock calls!  (Macbeth, I, 1)
=> Ring structure on tuples

geometry/pair.hpp, testing_utilities/componentwise.hpp, testing_utilities/componentwise_body.hpp, testing_utilities/componentwise_test.cpp
=> Fix the matchers once and for all

astronomy/sol_gravity_model.proto.txt, benchmarks/geopotential.cpp, physics/ephemeris_test.cpp, physics/geopotential_test.cpp, physics/oblate_body_body.hpp, physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, serialization/physics.proto, testing_utilities/solar_system_factory_body.hpp
Replace them by utilities in SolarSystem.
=> Remove fields max_degree and zonal from the astronomy proto

ksp_plugin/interface.cpp, ksp_plugin/interface_renderer.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_renderer_test.cpp, ksp_plugin_test/interface_test.cpp, serialization/journal.proto
=> Simplify the setting of the plotting frame through the interface

astronomy/trappist_numerics_blueprint.cfg, astronomy/trappist_numerics_blueprint.proto.txt, mathematica/mathematica_body.hpp
This alleviates the problems describes in #1999.
=> Fix the Trappist-1 blueprint

astronomy/trappist_dynamics_test.cpp, base/base.vcxproj, base/base32768_body.hpp, base/base32768_test.cpp, base/bundle.hpp, base/bundle_test.cpp, base/not_null_test.cpp, ksp_plugin_test/manœuvre_test.cpp, principia.props
This PR incorporates some of the changes proposed by @madman2003 in #2005.
=> Upgrade to Visual Studio 2017 15.9.3 preview 1

integrators/integrators_body.hpp, integrators/methods.hpp, serialization/integrators.proto
Another contribution to #1931.
=> Serialization of the Fine integrator

ksp_plugin_adapter/loader.cs
Reverts mockingbirdnest/Principia#2011
=> Revert "New C++ redistributable runtime for 15.9"

integrators/integrators_body.hpp, integrators/methods.hpp, serialization/integrators.proto
Reverts mockingbirdnest/Principia#2010
=> Revert "Serialization of the Fine integrator"

physics/geopotential_body.hpp
Fix #2014, which was caused by NaN potatoroids.
=> Do not try ordering NaN

integrators/integrators_body.hpp, integrators/methods.hpp, serialization/integrators.proto
Reverts mockingbirdnest/Principia#2016
=> Revert "Revert "Serialization of the Fine integrator""

ksp_plugin_adapter/loader.cs
Reverts mockingbirdnest/Principia#2015
=> Revert "Revert "New C++ redistributable runtime for 15.9""

coverage_analyser/coverage_analyser.cs
The coverage analysis worked when run by Jenkins before the upgrade, but seems to be broken now even when the rebuild, instrumentation, profiling, and test running are done by hand.
This fails to make sense.
Handling `AccessViolationException` is disturbing, but let's see if this gives us coverage and whether Jenkins continues to hang following the coverage analysis.
=> Ignore AccessViolationException in the coverage analyser

ksp_plugin_test/interface_test.cpp
=> Fix the test to be able to read gipfeli saves

base/arena_allocator_test.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/interface_test.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, serialization/physics.proto
=> Do not prolong the Ephemeris to t_max on deserialization

physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, testing_utilities/testing_utilities.vcxproj, testing_utilities/testing_utilities.vcxproj.filters, tools/tools.vcxproj, tools/tools.vcxproj.filters
Detect collisions substantially below mean_radius.
Fix #2072.
=> Add intrinsic forces even if a collision is detected

ksp_plugin/interface_external.cpp, ksp_plugin_test/interface_external_test.cpp, serialization/journal.proto
=> Geopotential API

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
Preparatory work for asynchronous predictions (aka prognostications).
=> Make ContinuousTrajectory thread-safe

ksp_plugin/plugin.cpp, ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp
Fix a bug in the computation of closest approaches, and do some cleanup in Renderer and Plugin.
=> Remove GetTargetVesselPrediction

ksp_plugin_adapter/dialog.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs
Also centre the dialog by default.
=> Change the Dialog class to persist its data using a ConfigNode

ksp_plugin_adapter/dialog.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
To do this, split "supervised" from "unsupervised" renderer.  Also move persistence to the renderer (not used yet to persist the flight plan and frame selector).
=> Make Dialog a WindowRenderer

ksp_plugin/plugin.cpp, ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/mock_vessel.hpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp
=> Asynchronous computation of target trajectory and frame

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
The real solution would be to use the new canvas API, but that's quite a bit of work.  This solution is a bit hacky, but it works well enough and improves usability on modern displays.
=> Dynamic scaling of the UI

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Render the guidance node in the adapter and not in the flight planner

astronomy/trappist_gravity_model_slippist1.cfg, tools/generate_kopernicus.cpp
=> Rename the Slippist b planet.

ksp_plugin_adapter/burn_editor.cs
=> Take the thrust limiter into account

physics/protector.cpp
=> Proper usage of the multiset container

ksp_plugin_adapter/flight_planner.cs
=> Systematically set the flight plan final time when displaying the flight planner

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/vessel_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
=> Guard the ephemeris as soon as we construct the prognosticator parameters

ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/style.cs
=> Multiline label in the frame selector

ksp_plugin_adapter/reference_frame_selector.cs
=> Run the callback the first time the frame changes after construction

journal/player.cpp, journal/player.hpp, journal/player_test.cpp, ksp_plugin/interface_flight_plan.cpp
=> Remove the last manœuvre when it leads to an integration error

build_for_benchmarking.ps1, find_msbuild.ps1
PowerShell works in mysterious ways.
=> Correctly handle the case where a single Visual Studio version is installed

Principia.sln.DotSettings, ksp_plugin_adapter/boxed.cs, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/class_marshalers.cs, ksp_plugin_adapter/config_node_parsers.cs, ksp_plugin_adapter/dialog.cs, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/disposable.cs, ksp_plugin_adapter/disposable_marshaller.cs, ksp_plugin_adapter/external_interface.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/loader.cs, ksp_plugin_adapter/logging.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_adapter/null_extensions.cs, ksp_plugin_adapter/optional_marshaler.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/rendering_actions.cs, ksp_plugin_adapter/style.cs, ksp_plugin_adapter/utf16_marshaler.cs, ksp_plugin_adapter/utf8_marshaler.cs, ksp_plugin_adapter/window_renderer.cs
Two types of changes:
1. Systematic changes of things that we always want (e.g., unused `using` clauses).
1. Proposed changes that we may or may not want applied by hand.
No contentious things like adjusting naming conventions or reformatting.
=> Apply some ReSharper fixes to our code

numerics/elliptic_integrals.cpp
Note to the reviewer: this is _not_ a diffbase.
=> Better identifiers and control structure for FukushimaEllipticBsDsJs

numerics/elliptic_integrals.cpp
Note to the reviewer: this is a diffbase, only c2ca6f2 needs to be reviewed.
=>  Rewrite BulirschCel and FukushimaEllipticBDJ

ksp_plugin_adapter/flight_planner.cs
=> Fix persistent error message and problems with short flight plans

ksp_plugin_adapter/burn_editor.cs
=> Take the thrust limiter into account.

documentation/Releasing.md, make_principia_release.ps1
Fix some issues in the script and documentation found while building the Fermat release.
=> Improve the release process

ksp_plugin_adapter/main_window.cs
This will display empty fields for the length/steps of the prediction when no vessel is selected (e.g., at the space centre) which hopefully will be less confusing than displaying the default values.
The stupid GUILayout UI doesn't let us display a disabled button, so the buttons are clickable but do nothing when there is no selected vessel.
Fix #2239.
=> Disable the prediction controls when there is no predicted vessel

Principia.sln.DotSettings, journal/player_test.cpp, physics/continuous_trajectory_body.hpp
We spend 4-5% of the journal on these assertions, which are mostly belt-and-suspender safety.
=> A micro-optimization found when profiling a journal

astronomy/astronomy.vcxproj, astronomy/astronomy.vcxproj.filters, astronomy/orbit_recurrence.hpp, astronomy/orbit_recurrence_body.hpp, astronomy/orbit_recurrence_test.cpp
=> Orbit recurrence

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs
=> Save the prediction parameters when they are modified in the UI

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Do not show our UI in contexts where it's not useful

benchmarks/main.cpp, ksp_plugin/interface.cpp, mathematica/main.cpp, tools/main.cpp
Note that this requires a `rebuild_all_solutions`.
Fix #2259.
=> Set the log filename extension

Principia.sln.DotSettings, astronomy/sol_gravity_model.cfg, astronomy/sol_gravity_model.proto.txt, ksp_plugin/interface.cpp, ksp_plugin_adapter/config_node_parsers.cs, ksp_plugin_test/interface_test.cpp, physics/geopotential_test.cpp, physics/oblate_body_body.hpp, serialization/journal.proto, serialization/physics.proto, tools/generate_configuration.cpp
=> Add support for specifying the geopotential using J

astronomy/lunar_orbit_test.cpp, benchmarks/apsides.cpp, ksp_plugin/interface_external.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_renderer.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs, physics/apsides.hpp, physics/apsides_body.hpp, physics/apsides_test.cpp, serialization/journal.proto
This is expected to bring major improvements to #2261.
=>  Pass the maximum number of points to compute from C# to C++

astronomy/geodesy_test.cpp, astronomy/orbital_elements_test.cpp, astronomy/standard_product_3_test.cpp, benchmarks/apsides.cpp, benchmarks/ephemeris.cpp, ksp_plugin/flight_plan.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/pile_up_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/apsides_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/mock_ephemeris.hpp
=> Get rid of last_point_only

quantities/quantities_body.hpp, quantities/si.hpp, quantities/si_body.hpp
=> Move the formatting of quantity dimensions to a common place

testing_utilities/approximate_quantity.hpp, testing_utilities/approximate_quantity_body.hpp, testing_utilities/approximate_quantity_test.cpp
* Support for querying the unit.
* Computation of distance in ulps.
* Support for signs.
* Linker fixes.
=> More features in ApproximateQuantity

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Remove an obsolete condition

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Unmanageable hacks

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs
=> Don't attempt to use the plugin in the main window if it's not running

astronomy/geodesy_test.cpp, astronomy/lunar_orbit_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/trappist_dynamics_test.cpp, astronomy/молния_orbit_test.cpp, numerics/elliptic_functions_test.cpp
=> Move tests longer than 30 seconds to postsubmit

astronomy/orbital_elements_test.cpp, physics/apsides_test.cpp
=> Clang 8 test tolerances

astronomy/orbit_recurrence.hpp, astronomy/orbit_recurrence_body.hpp, astronomy/orbital_elements_body.hpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/orbit_analyser.cpp, ksp_plugin/orbit_analyser.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/orbit_analyser_test.cpp
The followup (interface and C# UI) will be https://github.com/eggrobin/Principia/compare/orbit-analyser-class...eggrobin:orbit-analyser?expand=1.
=> A class that asynchronously analyses orbits

journal/player_test.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
=>  Don't look at anomalous manœuvres when building the guidance node

geometry/identity.hpp, geometry/identity_body.hpp, geometry/identity_test.cpp, geometry/linear_map.hpp, geometry/r3x3_matrix.hpp, geometry/r3x3_matrix_body.hpp, geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp, geometry/symmetric_bilinear_form.hpp, geometry/symmetric_bilinear_form_body.hpp
Also a bit of cleanup on old code.
=> Changes to geometry to support the inertia tensor

base/macros.hpp, benchmarks/dynamic_frame.cpp, benchmarks/main.cpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_external.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_future.cpp, ksp_plugin/interface_iterator.cpp, ksp_plugin/interface_monitor.cpp, ksp_plugin/interface_planetarium.cpp, ksp_plugin/interface_renderer.cpp, ksp_plugin/interface_vessel.cpp, mathematica/main.cpp, principia.props, tools/journal_proto_processor.cpp, tools/main.cpp
Once this is merged, we should wait a bit to see whether there are performance changes just from the calling convention change, and then switch from passing quantities by const reference to passing them by copy in a separate pull request.
=> Change the calling convention

geometry/affine_map.hpp, geometry/affine_map_body.hpp, geometry/affine_map_test.cpp, geometry/identity.hpp, geometry/identity_body.hpp, geometry/identity_test.cpp, geometry/orthogonal_map.hpp, geometry/orthogonal_map_body.hpp, geometry/orthogonal_map_test.cpp, geometry/permutation.hpp, geometry/permutation_body.hpp, geometry/permutation_test.cpp, geometry/perspective.hpp, geometry/perspective_body.hpp, geometry/perspective_test.cpp, geometry/quaternion_body.hpp, geometry/quaternion_test.cpp, geometry/rotation.hpp
=> Add operator<< to many classes

physics/euler_solver.hpp, physics/euler_solver_body.hpp, physics/euler_solver_test.cpp
to take the momentum in the inertial frame.
=> Change the construction of the solver

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin_test/pile_up_test.cpp, physics/rigid_motion.hpp, physics/rigid_motion_body.hpp, serialization/ksp_plugin.proto
=> Change the PileUp data structures to hold rigid motions

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Run the adapter in the main menu to detect loading problems early

physics/mechanical_system.hpp, physics/mechanical_system_body.hpp, physics/mechanical_system_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
=> Rename ClosedSystem into MechanicalSystem

serialization/journal.proto
#2463 changed spaces to tabs while moving things around.
Undo that.
=> The final frontier

base/not_null_test.cpp, ksp_plugin/part.cpp
This required upgrading to 1.4.4 because apparently 1.3.8 cannot compile `SymmetryBilinearForm`...
=> Fix the diurnal build

Makefile, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp
=> Upgrade to Xcode 11 and revert #2344

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Properly track rotation across a change of SOI

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, physics/ephemeris_test.cpp
Useful for understanding what happens in #2400.
=> A test of the downsampling/serialization/compression of trajectories

ksp_plugin_test/interface_test.cpp, testing_utilities/serialization.hpp, testing_utilities/serialization_body.hpp
Obviously, we have not debugged saves for a looong time.
=> Change the deserialization test to be able to read base64 saves

Principia.sln.DotSettings, geometry/r3x3_matrix.hpp, geometry/r3x3_matrix_body.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface_part.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/part.cpp, ksp_plugin/part.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/pile_up_test.cpp, physics/euler_solver.hpp, physics/mechanical_system_test.cpp, serialization/geometry.proto, serialization/journal.proto, serialization/ksp_plugin.proto
More precisely, this is `pleroy/Videos` which was on top of `frobenioid` and in which `master` was merged.
=> Merge frobenioid into master

ksp_plugin_adapter/ksp_plugin_adapter.cs
The issue was in #2463, but visible only starting with #2471 (and we did not see it until much later).
=> Fix Frobenius

ksp_plugin_adapter/flight_planner.cs
With the fix to #852, long flight plans are easy to build with an RCS that provides very small forward thrust.  Raising an exception in the UI is not nice, it's better to saturate to the longest possible `TimeSpan` and let the user sort things out (probably by reducing the duration of the burn and that of the plan).
=> Avoid exceptions on very long flight plans

ksp_plugin_adapter/flight_planner.cs
=> Avoid changing the layout between Layout and Repaint and fix a message

ksp_plugin_adapter/main_window.cs
Keeping it around as we will likely want to take another look at #2519.
=> Hide the 2519 debugging UI

geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp
=> New operations related to Rotations

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp
=> Mathematica logging of the inertia tensor

physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
This is restructuring work for #2570.
=> Pass the iterator traits as a template parameter to Forkable and ForkableIterator

Principia.sln.DotSettings, ksp_plugin_adapter/external_interface.cs
=> Use the Status message in the exceptions returned from the external interface

geometry/frame.hpp, geometry/named_quantities.hpp, ksp_plugin/interface_part.cpp, ksp_plugin/pile_up.cpp, physics/barycentric_rotating_dynamic_frame_body.hpp, physics/body_centred_body_direction_dynamic_frame_body.hpp, physics/dynamic_frame_body.hpp, physics/mechanical_system.hpp, physics/mechanical_system_body.hpp, physics/rigid_motion.hpp, physics/rigid_motion_body.hpp, physics/rigid_motion_test.cpp
=> A better syntax for the selectors of RigidMotion and AcceleratedRigidMotion

ksp_plugin/pile_up.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
=> Skip collisions with unready Kerbals

ksp_plugin/interface_part.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
=> Pass the lever arm across the interface

geometry/cartesian_product.hpp, geometry/cartesian_product_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, principia.props
=> The vector space of Poisson series

numerics/poisson_series_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, quantities/named_quantities.hpp
=> Polynomial primitive and a few templates

numerics/polynomial_body.hpp
=> Try to make Clang happy

numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
Another contribution to #2400.
=> Conversion of a polynomial to a higher degree

numerics/polynomial_body.hpp
=> Use CONSTEXPR_CHECK to try to fix Clang errors

geometry/rotation_body.hpp, geometry/symmetric_bilinear_form.hpp, geometry/symmetric_bilinear_form_body.hpp, geometry/symmetric_bilinear_form_test.cpp, journal/player_test.cpp, journal/profiles.cpp
=> Properly deal with two very close eigenvalues in Diagonalize

numerics/apodization.hpp, numerics/apodization_body.hpp, numerics/apodization_test.cpp
=> Apodization functions

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp
=> Inner product of Poisson series

numerics/fast_fourier_transform_test.cpp
=> FFT tolerances for Clang

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
As @ferram4 said,
> consider it all cursed.
This fixes #2607.
=> Parachute torque

numerics/root_finders.hpp, numerics/root_finders_body.hpp, numerics/root_finders_test.cpp
=> Golden section search

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs
=> Fix a couple of bugs in flight plan rebasing

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp
=> Piecewise Poisson series

numerics/poisson_series_test.cpp
=> Tolerances for Clang

geometry/rotation.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp
=> Output operators for Polynomial and PoissonSeries

numerics/frequency_analysis_body.hpp
=> Fix a compilation error found by Clang

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp
=> A test for the projection of piecewise Poisson series

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp
Yet another step towards #2400.
=> Support for secular terms in the Кудрявцев projection

base/macros.hpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/poisson_series.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp
#2400, the gift that keeps giving.
=> ToMathematica for polynomials and (not quite) Poisson series

mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/polynomial_body.hpp
=> Work-around polynomial operators +/- and fix the Mathematica test

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, quantities/named_quantities.hpp, serialization/numerics.proto
Unclear if we will need it for #2400, but it might as well work rather than being half-broken.
=> Support for affine-valued polynomials

geometry/geometry.vcxproj, geometry/geometry.vcxproj.filters, geometry/hilbert.hpp, geometry/hilbert_body.hpp, geometry/hilbert_test.cpp, quantities/traits.hpp
Not used yet. Will make it possible to have vector projections for #2400.
=> A trait to represent a Hilbert space

geometry/hilbert.hpp, geometry/hilbert_body.hpp
For reference, https://godbolt.org/z/qWs75f.
#2400, of course.
=> A version of Hilbert that may be more palatable to Clang

geometry/cartesian_product.hpp, geometry/cartesian_product_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
=> Pointwise inner product of polynomials

geometry/cartesian_product_body.hpp
=> Clang doesn't implement CWG 150/P0522R0

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, quantities/quantities.vcxproj, quantities/quantities.vcxproj.filters, quantities/traits.hpp, quantities/traits_test.cpp
=> Add pointwise inner product for Poisson series and use it in Dot

geometry/grassmann.hpp, geometry/hilbert.hpp, geometry/hilbert_test.cpp, numerics/frequency_analysis_body.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
=> Multidimensional basis of Poisson series

physics/continuous_trajectory_body.hpp
=> Fix compilation errors found by Clang

numerics/poisson_series_basis_body.hpp
=> Fix errors found by Clang

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/poisson_series.hpp, numerics/polynomial.hpp
=> Better support for Mathematica output of functions

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp
Hoping to improve the conditioning of #2400.
=> Origin change for Poisson series

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp
Also allow evaluation of a piecewise Poisson series at its last point.
Might improve conditioning in #2400.
=> Add support for multiorigin piecewise Poisson series

numerics/poisson_series_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
=> Piecewise series from continuous trajectory and a tolerance

numerics/poisson_series_test.cpp
=> Fix tolerances for Clang

numerics/numerics.vcxproj.filters, numerics/quadrature_test.cpp
=> Tolerances for Linux/macOS

numerics/poisson_series_test.cpp
=> More tolerance adjustments

geometry/complexification.hpp, geometry/complexification_body.hpp, geometry/hilbert.hpp, numerics/fast_fourier_transform.hpp, numerics/fast_fourier_transform_body.hpp, numerics/fast_fourier_transform_test.cpp, numerics/frequency_analysis_test.cpp, testing_utilities/almost_equals.hpp, testing_utilities/almost_equals_body.hpp
Will allow frequency analysis for displacement, *ad majorem #2400 gloriam*.
=> Use complexification in FFT

geometry/complexification.hpp
=> Fix Clang errors

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp
=> Precise mode computation for vectors

numerics/frequency_analysis_body.hpp
=> Fix a problem found by Clang

numerics/root_finders.hpp, numerics/root_finders_body.hpp, numerics/root_finders_test.cpp
=> they're good minimization algorithms Brent

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/root_finders.hpp, physics/kepler_orbit_test.cpp, quantities/elementary_functions_body.hpp
1. Use the Russian peasant algorithm to implement `Pow`.
1. Use `Brent` for precise frequency analysis.
#2400
=> Numerical optimizations

geometry/cartesian_product_body.hpp, numerics/frequency_analysis.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp
=> Use the Fourier transform for precise mode computation

geometry/cartesian_product_body.hpp
=> Attempt to fix the SFINAE

numerics/polynomial.hpp
=> More bugs found by clang

numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
This will come handy for QR decomposition in the context of #2400.
=> Add support for upper-triangular matrices

numerics/double_precision_body.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, physics/analytical_series_test.cpp
To try to improve the conditioning of #2400.
=> Change the projection algorithm to use Modified Gram-Schmidt

geometry/symmetric_bilinear_form_body.hpp, geometry/symmetric_bilinear_form_test.cpp, journal/player_test.cpp, ksp_plugin/pile_up.cpp, stacktrace_decoder/stacktrace_decoder.cs
=> Computation of eigenvalues of matrices that are very close to a multiple of the identity

numerics/frequency_analysis_test.cpp
=> Adjust tolerances for Clang

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, serialization/numerics.proto
=> Serialization of Poisson series

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, serialization/numerics.proto
=> Serialization of PiecewisePoissonSeries

numerics/frequency_analysis_test.cpp, numerics/quadrature_test.cpp
=> Adjust tolerances for Linux and macOS

numerics/quadrature_body.hpp
Will fix errors found by Clang; #2400.
=> Declare and reorder functions

numerics/quadrature_test.cpp
=> Adjust number of iterations for Linux and macOS

.gitignore
The .vscode directory contains project-specific VSCode settings.
=> Added .vscode directory to .gitignore.

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, serialization/numerics.proto
=> Change PiecewisePoissonSeries to avoid origin changes on additions

numerics/poisson_series_test.cpp
=> Adjust tolerances for Linux/macOS

numerics/frequency_analysis.hpp, numerics/frequency_analysis_body.hpp, numerics/poisson_series_basis.hpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_basis_test.cpp
Should help avoiding singular basis in #2400.
=> Add support for limiting the degree of polynomials produced by the basis generator

numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, physics/analytical_series_test.cpp
Comparison between the various methods, 5+3 periods, 10 frequencies.  The hybrid algorithm has about the same accuracy as Clenshaw-Curtis and about the same speed as formal integration.
Hybrid algorithm:
```
I1024 18:22:01.925325 16632 analytical_series_test.cpp:174] ---------- Io
I1024 18:22:11.196252 16632 analytical_series_test.cpp:88] step=11
I1024 18:22:11.205253 16632 analytical_series_test.cpp:126] max_residual=+1.33499009696820690e+03 m
I1024 18:22:11.206254 16632 analytical_series_test.cpp:174] ---------- Moon
I1024 18:22:14.385571 16632 analytical_series_test.cpp:88] step=10
I1024 18:22:14.393573 16632 analytical_series_test.cpp:100] max_residual=+1.23781079255599155e-01 m
I1024 18:22:14.394572 16632 analytical_series_test.cpp:174] ---------- Phobos
I1024 18:22:23.911525 16632 …
```
=> A hybrid algorithm for InnerProduct and Norm of Poisson series

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/piecewise_poisson_series.hpp, numerics/piecewise_poisson_series_body.hpp, numerics/piecewise_poisson_series_test.cpp, physics/analytical_series_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
=> Support for distinct degrees in piecewise Poisson series

ksp_plugin/interface_vessel.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin_adapter/main_window.cs, serialization/journal.proto
=> Remove rotation traces related to #2519

astronomy/orbital_elements_body.hpp
This is made possible by #2786.
=> Bring back some designated initializers

integrators/integrators_body.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series_basis.hpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_basis_test.cpp
In particular, this avoids the ugliness around dimensions and the stupid sort.
#2400.
=> Rewrite the Poisson series basis generator

ksp_plugin/interface_body.hpp, ksp_plugin/interface_vessel.cpp
We will need to do it for flight plan analyses as well.
=> Factor out the OrbitAnalyser::Analysis to OrbitAnalysis conversion

numerics/apodization_body.hpp, numerics/apodization_test.cpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_test.cpp, numerics/quadrature.hpp
=> Change the apodization functions to be centred

astronomy/orbit_analysis_test.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/window_renderer.cs, serialization/journal.proto
=> Describe the current orbit on the analyser button

numerics/piecewise_poisson_series.hpp, numerics/piecewise_poisson_series_body.hpp, numerics/piecewise_poisson_series_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/quadrature.hpp, numerics/quadrature_body.hpp
About 1.7× faster.
A modest contribution to #2400.
=> Use Clenshaw-Curtis in the piecewise Poisson series inner product

numerics/frequency_analysis_body.hpp, numerics/piecewise_poisson_series.hpp, numerics/piecewise_poisson_series_body.hpp
=> Cache the evaluations at the Gauss-Legendre points

numerics/frequency_analysis_test.cpp, numerics/piecewise_poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/quadrature_body.hpp
=> Fix tolerances for Linux and remove a check

numerics/frequency_analysis_body.hpp
=> Termination check in frequency analysis

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, numerics/fast_fourier_transform.hpp, numerics/fast_fourier_transform_body.hpp, numerics/fast_fourier_transform_test.cpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, physics/analytical_series_test.cpp
=> Support for pass-band mode and Mathematica traces in the analytical series test

astronomy/orbital_elements_body.hpp
=> Negative sidereal periods are out of range

ksp_plugin_adapter/config_node_parsers.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs
Adds user configurable drawing styles for trajectories via an MM patch.
I think this addresses #869.
=> Added drawing style configuration

numerics/frequency_analysis_test.cpp, numerics/piecewise_poisson_series.hpp
=> Minor cleanups

geometry/cartesian_product.hpp, geometry/cartesian_product_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
=> Composition of polynomials

numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/double_precision_test.cpp
=> New double precision operators

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
=> Output of triangular arrays

numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/double_precision_test.cpp
=> Reduction mod 2π

numerics/poisson_series_test.cpp
=> A new test of ill-conditioned inner product

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp
=> Mathematica output of DoublePrecision

numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
=> Fix a bug when the left argument of Compose has degree 0

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp
=> Use CGS with reorthogonalization for frequency analysis

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series_basis.hpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_basis_test.cpp, serialization/journal.proto
=> Make Poisson series basis dimensionless

numerics/frequency_analysis_body.hpp
=> Remove code duplication

numerics/frequency_analysis_test.cpp
=> Adjust tolerances for macOS

numerics/frequency_analysis_test.cpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
Use this function in `PoissonSeries::Integrate`.
Also add a test based on actual processing of the Moon trajectory that demonstrates how bad `PoissonSeries::Integrate` is in real life.
#2400 is sad.
=> Add Integrate to Polynomial, which uses Gauss-Legendre

geometry/symmetric_bilinear_form_test.cpp, journal/player_test.cpp, tools/journal_proto_processor.cpp
=> Another test of diagonalization and fixes in the code generated for repeated strings

ksp_plugin_adapter/flight_planner.cs
=> Reset the final trajectory analyser when deleting the flight plan

ksp_plugin/orbit_analyser.cpp, ksp_plugin_test/orbit_analyser_test.cpp, physics/ephemeris_body.hpp
=> Fix a bug or two with short orbit analyses

physics/discrete_trajectory_body.hpp
A small code cleanup found while investigating #2815.
=> Remove a redundant check

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/orbit_analyser.cs
I had to garble two messages in Chinese because of changes in the number of parameters.  I left `TODO`s.
=> Fix small localization glitches

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/map_node_pool.cs
For Chinese I am just using the English text for now.
=> Add localization for some messages that were missed in the first pass

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/main_window.cs
This should cover punctuation and units.
=> Avoid string concatenation when composing messages

physics/solar_system.hpp, physics/solar_system_body.hpp, physics/solar_system_test.cpp, serialization/physics.proto
=> General fingerprinting of solar systems

ksp_plugin_adapter/localization/zh-cn.cfg
=> I forgot to actually make the suggested change

base/base.vcxproj, base/base.vcxproj.filters, base/macos_allocator_replacement.hpp, base/macos_allocator_replacement_test.cpp
Also add the files from #2900 to `base`.
=> Fix some lint

geometry/complexification.hpp, geometry/complexification_body.hpp
Some code that was left in one of my branches...
=> Complexification inner product

physics/checkpointer_test.cpp
=> More testing for the Checkpointer class

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
=> Support for prepending a continuous trajectory to another one

README.md
=> Fix a missed change from Goldbach to Grassmann

physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/checkpointer_test.cpp
These functions will be used in a future PR.
=> Extend the checkpointer API with new functions

ksp_plugin/orbit_analyser.cpp, ksp_plugin/orbit_analyser.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
=> Remove the Guard class as the t_min of the Ephemeris cannot move forward anymore

ksp_plugin/plugin.cpp, ksp_plugin_test/planetarium_test.cpp, physics/apsides_body.hpp, physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/checkpointer_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp
Tested (to some extent) in game.
=> Full implementation of the reanimator

physics/checkpointer_body.hpp
We cannot stay broken until Grassmannian gets merged.
=> Fix the build at head

base/base.vcxproj, base/base.vcxproj.filters, base/recurring_thread.hpp, base/recurring_thread_body.hpp, base/recurring_thread_test.cpp
=> A helper class for recurring execution of an action

base/recurring_thread.hpp, base/recurring_thread_body.hpp, base/recurring_thread_test.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp
Also beef up `RecurringThread`.
=> Use RecurringThread for the prognosticator

base/recurring_thread.hpp, base/recurring_thread_body.hpp
=> Support for restarting a RecurringThread

physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/checkpointer_test.cpp
=> More functions in the Checkpointer

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp
=> Documentation changes to ContinuousTrajectory

ksp_plugin_adapter/ksp_plugin_adapter.cs
Found in `TEST2986`, regression introduced when fixing #2922.
=> A packed vessel is not unfaithful

numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, serialization/numerics.proto
This fixes an old code smell that dated back to VS2015.
=> Rewrite PolynomialInMonomialBasis to avoid specializations

numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp
For some mysterious reason one of the four causes MSVC to go down the path of insanity.  We'll live with the rest.
=> Additive operators for converting vector-valued and affine valued polynomials

numerics/newhall.hpp, numerics/newhall_body.hpp, numerics/newhall_test.cpp
Note that we stick to vectors for Чебышёв series because it's not clear what it means for those to be affine-valued.
=> Support for affine-valued polynomials in Newhall

Makefile
Reverts mockingbirdnest/Principia#3011
=> Revert "Group all the Abseil libraries in the linker command line"

geometry/grassmann.hpp, geometry/grassmann_body.hpp, geometry/grassmann_test.cpp, geometry/point.hpp, geometry/point_body.hpp, geometry/point_test.cpp, geometry/r3_element.hpp, geometry/r3_element_body.hpp, numerics/fma_test.cpp, quantities/elementary_functions_test.cpp
This will make it possible to use FMA in the polynomials.
=> FMA for geometry

numerics/polynomial_evaluators_body.hpp
=> Fix the build more

numerics/polynomial_evaluators.hpp, numerics/polynomial_evaluators_body.hpp
Addressing https://github.com/mockingbirdnest/Principia/pull/3028#discussion_r647168522.
=> No exported namespace

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp
* No semantic changes.
* Reorder the code so that the serialization methods are at the end of the public part.
* Comment a bunch of public methods.
#2400 for vessels.
=> Some cleanups in class Vessel

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/vessel_test.cpp
=> Add a predicate to check if a vessel is in a state that allows collapsing its trajectory

astronomy/date_time_body.hpp
Follow-up on #3040, missed in #3044.
=> More initialization

numerics/fit_hermite_spline.hpp, numerics/fit_hermite_spline_body.hpp, numerics/fit_hermite_spline_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp
=> Make FitHermiteSpline interruptible

base/macros.hpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
This is preparatory work for having downsampling properly handle forks, which itself might contribute to #2400.
=> Restructure a bit the code of the discrete trajectory downsampling

ksp_plugin_test/plugin_compatibility_test.cpp
While it is slower than maccollo’s, it is also much slower to load.
=> Do not test Reach’s save in debug

physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/ephemeris_test.cpp, physics/forkable_body.hpp, serialization/physics.proto
This is preparatory work for having downsampling on forks and is a distant contribution to #2400.
=> Change the Downsampling class to manage a proper data structure and its invariants

ksp_plugin_adapter/orbit_analyser.cs
=> Widen the mission duration label

physics/discrete_trajectory_body.hpp
This should fix the diurnal build.
=> Fix a compatibility issue with pre-陈景润 saves

journal/player.cpp, journal/player.hpp, journal/player_test.cpp, journal/profiles.cpp
=> A few improvements to journal replaying

ksp_plugin/part.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/vessel.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp, serialization/physics.proto
=> Add support for storing the exact degrees of freedom at some points of a trajectory

ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/localization/celestial_strings.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/reference_frame_selector.cs
Also changes to the celestial strings for apsides that should have been in #3101.
=> French translations

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/vessel_test.cpp, serialization/ksp_plugin.proto
Also some code reordering, in a separate commit.
This is horribly untested because it's hard to test in isolation.
#2400.
=> Add a function to reanimate one checkpoint

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
No testing because this is not called.
#2400.
=> Add method Reanimate and add thread safety to the Vessel history

ksp_plugin/vessel.cpp, ksp_plugin_test/vessel_test.cpp, serialization/ksp_plugin.proto
=> Serialization and deserialization of vessel checkpoints

ksp_plugin/part.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/vessel.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, serialization/physics.proto
Also reordering some parameters to make `message` the last one.
#2400.
=> Partial serialization of DiscreteTrajectory

physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
=> Add a -= operator on trajectory iterators

astronomy/sol_numerics_blueprint.cfg, astronomy/sol_numerics_blueprint.proto.txt, astronomy/лидов_古在_test.cpp, journal/profiles.hpp, ksp_plugin/integrators.cpp, ksp_plugin/integrators.hpp, ksp_plugin/interface.cpp, ksp_plugin/orbit_analyser.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/config_node_parsers.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_test.cpp, serialization/astronomy.proto, serialization/journal.proto, tools/generate_configuration.cpp
=> Make it possible to configure downsampling using the numerics blueprint file

ksp_plugin/interface.cpp, ksp_plugin_test/vessel_test.cpp, physics/degrees_of_freedom_body.hpp, physics/discrete_trajectory_body.hpp, physics/mock_ephemeris.hpp, testing_utilities/trajectory_factories.hpp, testing_utilities/trajectory_factories_body.hpp, testing_utilities/trajectory_factories_test.cpp
=> Bring improved Vessel test to Entwurf and change the test for checkpointing

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Orbits of a possibly different colour

ksp_plugin_adapter/main_window.cs
=> Use the translated celestial name in the celestial targeting UI

physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_test.cpp
=> Serialization of empty segments

ksp_plugin/integrators.cpp, ksp_plugin/integrators.hpp, ksp_plugin/orbit_analyser.cpp
Also `integrators.{hpp,cpp}` which are prerequisites.
#3136.
=> Convert OrbitAnalyser and its test to DiscreteTraject0ry

ksp_plugin/manœuvre.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_test/manœuvre_test.cpp
=> Convert Manœuvre and its test to DiscreteTraject0ry

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin_test/plugin_test.cpp, physics/discrete_traject0ry_body.hpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp
=> Convert Plugin and its test to DiscreteTraject0ry

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface_external.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_iterator.cpp, ksp_plugin/interface_planetarium.cpp, ksp_plugin/interface_renderer.cpp, ksp_plugin/iterators_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/interface_renderer_test.cpp, ksp_plugin_test/mock_flight_plan.hpp, ksp_plugin_test/mock_renderer.hpp, physics/apsides.hpp, physics/apsides_body.hpp, physics/discrete_traject0ry_body.hpp
Note to the reviewer: it might make sense to do this review commit by commit as the commit are mostly independent.
#3136.
=> Convert the interface methods to DiscreteTraject0ry

ksp_plugin_test/plugin_integration_test.cpp
Also made sure that the plugin benchmark works.
#3136.
=> Convert the plugin integration test to DiscreteTraject0ry

ksp_plugin/part.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, physics/discrete_traject0ry.hpp
=> Fix a bug in Part compatibility deserialization and add a test

ksp_plugin/plugin.hpp
=> Fix another Clang error

ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, testing_utilities/string_log_sink.hpp, testing_utilities/string_log_sink_body.hpp, testing_utilities/testing_utilities.vcxproj, testing_utilities/testing_utilities.vcxproj.filters
=> Fix link problems by inlining StringLogSink

physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_test.cpp
=> Add a function to merge two nonoverlapping DiscreteTrajectory objects

testing_utilities/discrete_trajectory_factories.hpp, testing_utilities/discrete_trajectory_factories_body.hpp, testing_utilities/discrete_trajectory_factories_test.cpp
=> A factory for an accelerated trajectory

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_segment_body.hpp, serialization/physics.proto
=> Only write the number of dense points if downsampling is enabled

ksp_plugin/vessel.cpp
=> Start the flight plan at the end of the backstory, not at the end of the history

physics/discrete_trajectory_iterator_body.hpp
=> Make progress on segments of size 2

ksp_plugin/vessel.cpp
=> Fix a bug when rebasing the flight plan

physics/discrete_trajectory_segment_body.hpp
=> A consistency check for merging trajectory segments

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
=> Fix t_min for a trajectory starting with empty segments

ksp_plugin_adapter/style.cs
=> Initialize the styles more lazily

ksp_plugin_adapter/localization/celestial_strings.cfg, ksp_plugin_adapter/localization/fr-fr.cfg
Fix #3236.
Drive-by change: fix an inconsistent translation of _rebase_ into French.
=> Some localization issues

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
=> Fix a bug where ForgetAfter was creating orphaned 1-point segments

ksp_plugin_adapter/localization/celestial_strings.cfg
For use with KSP-RO/RealSolarSystem#253.
=> Russian celestial strings

ksp_plugin_adapter/localization/ru.cfg
Reported on discord by @von-Kerman (see https://discord.com/channels/319857228905447436/480397772248580098/925815060482367518 _sqq_.). Declension issues, as well as the ambiguous _Length_ becoming _Forecast for_ as the label for the mission duration in the orbit analyser.
=> Fix some linguistic issues in the Russian translation

journal/player_test.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, physics/ephemeris.hpp
=> Update the oldest_reanimated_checkpoint_ when the first know checkpoint is created

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/vessel_test.cpp
=> Reconstruct the flight plan lazily

Makefile, install_deps.sh
=> Require Mojave.

Makefile, install_deps.sh
Require Sierra again (by disabling exceptions).
=> Unrequire Mojave.

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/transposed_view.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
This requires the addition of class `UnboundedMatrix` and of a variety of `operator*`.
#2966.
=> Add computation of Rayleigh quotient

Makefile, base/macros.hpp, mathematica/mathematica_test.cpp, physics/rigid_motion_body.hpp, quantities/quantities.hpp
Some fixes so that the code compiles and the tests pass under Clang 13.
=> Compatibility with latest version of Clang

Makefile, Principia.sln, base/base.vcxproj, base/base.vcxproj.filters, base/macos_filesystem_replacement.hpp, install_deps.sh
Use the so-called "@rnlahaye pattern".
=> Move to C++20 and hack the macOS filesystem

base/macros.hpp, geometry/named_quantities.hpp, numerics/next_body.hpp, quantities/quantities.hpp
Fixed in https://reviews.llvm.org/D63793, brought to my attention by https://twitter.com/stephentyrone/status/1143641037312856064.
=> All hail zygoloid

ksp_plugin_adapter/plotter.cs
Hopefully fix #3311, though I cannot reproduce it.
=> Keep the index count even when the topology is LINES

ksp_plugin_adapter/plotter.cs
Fix #3311 once and for all—but—ONCE AND FOR ALL!
=> Put the logic where it does something, and also the right thing

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp, numerics/unbounded_arrays_body.hpp
Also some simplification of the templates in `matrix_computations_body.hpp`.
#2966.
=> Resolution of linear systems

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
=> Add a number of useful matrix operations

numerics/davenport_q_method_test.cpp
=> Davenport tolerances for macOS and Linux

ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp
=> Eliminate the reference part and use Davenport's Q Method instead

journal/player_test.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
This may help with #3219.  Even if it's not the root cause of that bug (it's hard to tell) pushing unfaithful parts to the C++ is a recipe for disaster.
=> No collisions or aerodynamics for unfaithful parts

integrators/ordinary_differential_equations_body.hpp
=> Fix an error found by Clang

physics/dynamic_frame.hpp, physics/dynamic_frame_body.hpp
=> RotationFreeGeometricAccelerationAtRest

integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp, integrators/embedded_explicit_runge_kutta_integrator.hpp, integrators/embedded_explicit_runge_kutta_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_integrator_test.cpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/integrators.hpp, integrators/integrators_body.hpp, integrators/ordinary_differential_equations.hpp, integrators/ordinary_differential_equations_body.hpp, physics/ephemeris_body.hpp, physics/equipotential.hpp, physics/equipotential_body.hpp, physics/equipotential_test.cpp, physics/physics.vcxproj.filters, serialization/integrators.proto
This requires minor adjustments to some integrator APIs and to serialization.
#3358.
=> Change first order ODEs to take an "independent variable" instead of an Instant

physics/geopotential.hpp, physics/geopotential_body.hpp, physics/geopotential_test.cpp, physics/harmonic_damping.hpp, physics/harmonic_damping_body.hpp, physics/harmonic_damping_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
This is purely a restructuring in preparation for introducing the computation of the potential for #3358.
=> Move HarmonicDamping to its own file

physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/geopotential_test.cpp, physics/solar_system.hpp
This includes a number of renamings to have functions whose name reflects what they do.
#3358.
=> Compute gravitational potential in Ephemeris

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/culture.cs, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/style.cs, ksp_plugin_adapter/time_span.cs
Scrollable figure spaces and adaptive fractional digits (dependent on the final acceleration) corresponding to the precision representable by the flight plan.
IAU-style timings in the flight plan, to the microsecond.
=> Scrollable spaces and variable fractional digits

ksp_plugin_adapter/planetarium_camera_adjuster.cs
=> Fix the camera jumping when changing reference frames

numerics/hermite2.hpp, numerics/hermite2_body.hpp, numerics/hermite2_test.cpp, numerics/hermite3.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters
A prerequisite for gradient descent, which is itself a prerequisite for #3358.
=> Add support for 2nd-degree Hermite polynomials

physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centred_body_direction_dynamic_frame_test.cpp, physics/body_surface_dynamic_frame_test.cpp, physics/dynamic_frame_test.cpp
Also a cleanup of unused declarations.
=> A better test of Frenet frames, using a bench vice

ksp_plugin_adapter/event_void_holder.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
Reviewer, beware!  It would be easy to make a typo.
Fix #3387.
=> Fix the memory leaks identified by KSPCommunityFixes

numerics/nearest_neighbour.hpp, numerics/nearest_neighbour_body.hpp, numerics/nearest_neighbour_test.cpp
This should make it easier for clients to find the returned value in their data structures.
Related to #3358.
=> Change the PCP tree API to pointers to values

ksp_plugin_adapter/plotter.cs
Apparently Unity doesn't like us to do work in the constructor.
Fix #3436.
=> Change the plotter to create the mesh lazily

numerics/nearest_neighbour.hpp, numerics/nearest_neighbour_body.hpp, numerics/nearest_neighbour_test.cpp
=> Support for adding values to a PCP tree

benchmarks/nearest_neighbour.cpp
=> A benchmark for adding to a PCP tree

numerics/nearest_neighbour.hpp, numerics/nearest_neighbour_body.hpp, numerics/nearest_neighbour_test.cpp
This will be useful for global optimization.
Related to #3358.
=> Support for applying a filter when looking for the nearest neighbour

numerics/gradient_descent.hpp, numerics/gradient_descent_body.hpp, numerics/gradient_descent_test.cpp, physics/equipotential_body.hpp
Instead, it takes an argument that is any type whose difference belongs to a Hilbert space.
Related to #3358.
=> Change the gradient descent code to not depend on Position

parallel_test_runner/parallel_test_runner.cs
Also properly wait for the standard error stream to be drained.
=> Add a semaphore to limit the parallelism when running the tests

numerics/global_optimization_test.cc, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, testing_utilities/optimization_test_functions.cpp, testing_utilities/optimization_test_functions.hpp, testing_utilities/optimization_test_functions_test.cpp, testing_utilities/testing_utilities.vcxproj, testing_utilities/testing_utilities.vcxproj.filters
=> Move out the optimization test functions and add Branin

numerics/global_optimization_test.cc, testing_utilities/componentwise_body.hpp, testing_utilities/is_near_body.hpp, testing_utilities/optimization_test_functions.cpp, testing_utilities/optimization_test_functions.hpp, testing_utilities/optimization_test_functions_test.cpp
Also switch all the tests to check absolute value, since the algorithm takes an absolute tolerance.  And fix some spacing issues in the matchers.
#3358.
=> A test of global optimization with Hartmann 3

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/global_optimization.cpp, numerics/global_optimization_test.cc, numerics/gradient_descent_body.hpp
And, perhaps more importantly, a fix for a situation where zooming was taking forever to make progress.
#3358.
```
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 6144 KiB (x1)
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_MLSLBranin/10/10             187858 ns       187752 ns         3739 average minima: 3.22011
BM_MLSLBranin/20/10             389219 ns       391089 ns         1795 average minima: 3.24513
BM_MLSLBranin/50/10            1081732 ns      1095171 ns          641 average minima: 3.30577
BM_MLSLBranin/10/20             393715 ns …
```
=> A benchmark for multi-level single linkage

geometry/symmetric_bilinear_form.hpp, geometry/symmetric_bilinear_form_body.hpp, geometry/symmetric_bilinear_form_test.cpp, numerics/global_optimization.hpp, numerics/global_optimization_body.hpp, numerics/global_optimization_test.cc, numerics/gradient_descent_body.hpp, numerics/nearest_neighbour.hpp, numerics/nearest_neighbour_body.hpp, numerics/nearest_neighbour_test.cpp, physics/mechanical_system_body.hpp
Note how the tests show that we call the functions less often.
Before:
```
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_MLSLBranin/10/10             187858 ns       187752 ns         3739 average minima: 3.22011
BM_MLSLBranin/20/10             389219 ns       391089 ns         1795 average minima: 3.24513
BM_MLSLBranin/50/10            1081732 ns      1095171 ns          641 average minima: 3.30577
BM_MLSLBranin/10/20             393715 ns       379608 ns         1726 average minima: 3.28911
BM_MLSLBranin/20/20             843044 ns       852179 ns          897 average minima: 3.31438
BM_MLSLBranin/50/20 …
```
=> Optimize the optimization code

numerics/global_optimization.hpp, numerics/global_optimization_body.hpp, numerics/global_optimization_test.cc, numerics/gradient_descent.hpp, numerics/gradient_descent_body.hpp, numerics/gradient_descent_test.cpp, physics/equipotential_body.hpp
And a fix to limit the gradient descent to a finite radius around the start point.
#3358.
=> A global optimization test with a function similar to the gravitational potential

geometry/geometry.vcxproj, geometry/geometry.vcxproj.filters, geometry/plane.hpp, geometry/plane_body.hpp, geometry/plane_test.cpp
=> A class to represent a non-oriented plane

numerics/global_optimization.hpp, numerics/global_optimization_body.hpp
=> Add support for finding the global maxima

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/mock_plugin.hpp, numerics/global_optimization.hpp, numerics/global_optimization_body.hpp
=> Extend the target vessel prediction when the flight plan gets extended

benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp, benchmarks/symplectic_runge_kutta_nyström_integrator.cpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp, integrators/ordinary_differential_equations.hpp, integrators/ordinary_differential_equations_body.hpp, integrators/symmetric_linear_multistep_integrator_test.cpp, integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, physics/ephemeris_body.hpp
=> Reorder the ODE parameters

integrators/ordinary_differential_equations.hpp, ksp_plugin_test/interface_flight_plan_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/equipotential.hpp, physics/equipotential_body.hpp, physics/integration_parameters.hpp, physics/integration_parameters_body.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters, serialization/ksp_plugin.proto, serialization/physics.proto
=> Move the integration parameters out of Ephemeris and use them in Equipotential

base/not_null_test.cpp, numerics/global_optimization_test.cc, numerics/gradient_descent_body.hpp, numerics/gradient_descent_test.cpp, numerics/polynomial.hpp
=> Detect violations of the Wolfe condition and a better Hermite margin test

astronomy/ksp_resonance_test.cpp, astronomy/ksp_system_test.cpp, astronomy/lunar_orbit_test.cpp, astronomy/orbit_analysis_test.cpp, astronomy/orbital_elements_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/trappist_dynamics_test.cpp, astronomy/лидов_古在_test.cpp, astronomy/молния_orbit_test.cpp, integrators/symmetric_linear_multistep_integrator_test.cpp, mathematica/integrator_plots.cpp, mathematica/local_error_analysis_body.hpp, mathematica/logger.hpp, mathematica/logger_body.hpp, mathematica/logger_test.cpp, mathematica/mathematica.hpp, mathematica/mathematica.vcxproj, mathematica/mathematica.vcxproj.filters, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, mathematica/retrobop_dynamical_stability.cpp, physics/analytical_series_test.cpp, physics/ephemeris_test.cpp, physics/equipotential_test.cpp
The first of a series of improvements to the logger.
=> Move the mathematica::Logger to its own file

physics/ephemeris_body.hpp, physics/equipotential.hpp, physics/equipotential_body.hpp, physics/equipotential_test.cpp
=> A function that tries to separate peaks from wells

physics/equipotential.hpp, physics/equipotential_body.hpp, physics/equipotential_test.cpp
=> Correctly build a series of States to represent equipotential lines

integrators/integrators.hpp, integrators/integrators.vcxproj, integrators/integrators.vcxproj.filters, integrators/integrators_body.hpp, integrators/starter.hpp, integrators/starter_body.hpp, integrators/symmetric_linear_multistep_integrator.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp
Roll forward of #3505 after Horner.
=> Revert "Revert "Add class Starter to encapsulate the operations needed to start a linear multistep integrator""

geometry/pair.hpp
=> Try to fix errors found by Clang

generate_version_translation_unit.sh
=> Fix the version generation script on Linux

astronomy/orbital_elements.hpp, astronomy/orbital_elements_body.hpp, astronomy/orbital_elements_test.cpp, testing_utilities/is_near_body.hpp
=> A test that computes the length of the year

astronomy/orbital_elements.hpp, astronomy/orbital_elements_body.hpp, astronomy/orbital_elements_test.cpp
We want to be using the same reference frame as for the orbit of the satellite, so we must look at the motion of the Sun that way.
=> Consider the orbit of the Sun around the Earth

testing_utilities/serialization.hpp
=> No base 32768 on Clang

testing_utilities/algebra.hpp, testing_utilities/algebra_body.hpp, testing_utilities/algebra_test.cpp
=> Fix inconsistent declarations in algebra testing

journal/journal.vcxproj, journal/journal.vcxproj.filters, journal/method.hpp, journal/method_body.hpp, journal/player.cpp, journal/player.hpp, journal/player_body.hpp, journal/player_test.cpp, journal/profiles.cpp, journal/profiles.hpp, journal/recorder.cpp, journal/recorder.hpp, journal/recorder_test.cpp, renamespacer/Properties/launchSettings.json, renamespacer/renamespacer.cs
=> Renamespace journal

astronomy/ksp_system_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/trappist_dynamics_test.cpp, base/macros.hpp, mathematica/error_analysis_test.cpp, mathematica/integrator_plots.cpp, mathematica/integrator_plots.hpp, mathematica/local_error_analysis.hpp, mathematica/local_error_analysis_body.hpp, mathematica/logger.hpp, mathematica/logger_body.hpp, mathematica/logger_test.cpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, mathematica/retrobop_dynamical_stability.cpp, mathematica/retrobop_dynamical_stability.hpp, numerics/piecewise_poisson_series.hpp, numerics/poisson_series.hpp, numerics/polynomial.hpp, physics/ephemeris_test.cpp, renamespace_all_the_things.ps1
=> Renamespace mathematica

numerics/polynomial.hpp
=> Clang is not my friend

numerics/piecewise_poisson_series.hpp, numerics/poisson_series.hpp
=> More friendship trouble

physics/discrete_trajectory_iterator.hpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_iterator.hpp
=> Even more pain with friendship

physics/discrete_trajectory_iterator.hpp, physics/discrete_trajectory_segment_iterator.hpp
=> Friend the tests

geometry/geometry.vcxproj, geometry/geometry.vcxproj.filters, geometry/homothecy.hpp, geometry/homothecy_body.hpp, geometry/homothecy_test.cpp, geometry/identity.hpp, geometry/linear_map.hpp, geometry/orthogonal_map.hpp, geometry/permutation.hpp, geometry/rotation.hpp, geometry/signature.hpp, serialization/geometry.proto
=> A class to represent homothecies

geometry/homothecy.hpp, geometry/identity.hpp, geometry/identity_body.hpp, geometry/linear_map.hpp, geometry/linear_map_body.hpp, geometry/orthogonal_map.hpp, geometry/orthogonal_map_body.hpp, geometry/permutation.hpp, geometry/permutation_body.hpp, geometry/rotation.hpp, geometry/rotation_body.hpp, geometry/signature.hpp
=> Clean up the contract of LinearMap and reify it using CRTP

base/macos_allocator_replacement_test.cpp
=> Try to fix the mac build again

.github/workflows/remove-before-flight.yml
It seems that the workflow doesn’t run for the pull request that adds it, so I cannot test the part that checks the pull request title and description.
=> Check for “remove before flight” comments

ksp_plugin/geometric_potential_plotter.cpp, ksp_plugin/geometric_potential_plotter.hpp
=> Draw another equipotential to pinpoint L₄/L₅

physics/barycentric_rotating_reference_frame_body.hpp
=> Fix empty range

ksp_plugin/geometric_potential_plotter.cpp
This gets rid of some very useless equipotentials close to Pluto [spotted](https://discord.com/channels/319857228905447436/480397772248580098/1107384276573499523) by @al2me6 in the SPL frame.
=> Use the radius of the secondary system when there are multiple secondaries

physics/body_centred_body_direction_reference_frame_body.hpp
=> Fix the t_min & t_max of the Tgt *O frame

stacktrace_decoder/stacktrace_decoder.cs
It has been a while since we have had to use it.
=> Update the unity stacktrace parser

ksp_plugin/geometric_potential_plotter.cpp, ksp_plugin/geometric_potential_plotter.hpp, physics/equipotential_test.cpp, physics/lagrange_equipotentials.hpp, physics/lagrange_equipotentials_body.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
No functional change.
This should make it possible to tweak the logic that chooses the energy levels, and to do some much-needed benchmarking.
=> Refactor equipotentials

physics/equipotential_test.cpp, physics/lagrange_equipotentials_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
=> A test for Lagrange equipotentials

benchmarks/planetarium_plot_methods.cpp
```
> .\Release\x64\benchmarks.exe --benchmark_filter=Planetarium
2023-06-10T13:32:01+02:00
Running C:\Users\robin\Projects\mockingbirdnest\Principia\Release\x64\benchmarks.exe
Run on (28 X 3312 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x14)
L1 Instruction 32 KiB (x14)
L2 Unified 1024 KiB (x14)
L3 Unified 19712 KiB (x1)
--------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations
--------------------------------------------------------------------------------------------------
BM_PlanetariumPlotMethod3/NearPolarPerspectiveECI             17.0 ms         16.7 ms           45 16211 points within -1.49365 ± 7028.58 × 3.70166 ± 7029.11 × -0.0446205 ± 77.5489 …
```
=> Benchmark PlotMethod3 in all frames

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/reference_frame_selector.cs
=> Fix two bugs with the ReferenceFrameParameters mess

integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp, integrators/embedded_explicit_runge_kutta_integrator.hpp, integrators/embedded_explicit_runge_kutta_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_integrator_test.cpp, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp, integrators/explicit_linear_multistep_integrator.hpp, integrators/explicit_linear_multistep_integrator_body.hpp, integrators/explicit_linear_multistep_integrator_test.cpp, integrators/explicit_runge_kutta_integrator.hpp, integrators/explicit_runge_kutta_integrator_body.hpp, integrators/explicit_runge_kutta_integrator_test.cpp, integrators/integrators.hpp, integrators/integrators_body.hpp, integrators/ordinary_differential_equations.hpp, integrators/ordinary_differential_equations_body.hpp, integrators/symmetric_linear_multistep_integrator.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp, integrators/symmetric_linear_multistep_integrator_test.cpp, integrators/symplectic_runge_kutta_nyström_integrator.hpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp, integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, sourcerer/Properties/launchSettings.json, sourcerer/analyser.cs, sourcerer/include_what_you_using.cs, sourcerer/parser.cs
This requires improved support for includes in conditional compilation.
=> Include-what-you-using for integrators

ksp_plugin_adapter/main_window.cs
=> Reduce the "dead zone" in the slider that controls history length

ksp_plugin_adapter/manœuvre_marker.cs
=> Don't show manœuvre markers in flight

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
On top of #3716.
Fix a footgun triggered while implementing said PR.
=> Only allow window shrinking when safe

numerics/gradient_descent.hpp, numerics/gradient_descent_body.hpp, numerics/gradient_descent_test.cpp
This will be useful for flight plan optimization, where the computation of the full gradient is expensive.
Let's discuss the terminology in the review.
#3681.
=> A variant of BFGS that takes the Gateaux derivative

ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin_test/flight_plan_optimizer_test.cpp
=> An optimizer to tweak a manœuvre to fly at a certain distance from a celestial

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/vessel.cpp, ksp_plugin_test/flight_plan_test.cpp
=> Add a copy constructor for the FlightPlan and use it in Vessel

ksp_plugin/flight_plan_optimization_driver.cpp, ksp_plugin/flight_plan_optimization_driver.hpp, ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/orbit_analyser.hpp, ksp_plugin/vessel.cpp, numerics/global_optimization_body.hpp, numerics/gradient_descent.hpp, numerics/gradient_descent_body.hpp, numerics/gradient_descent_test.cpp, testing_utilities/matchers.hpp
=> An asynchronous driver for flight plan optimization

ksp_plugin/flight_plan.cpp, ksp_plugin/manœuvre.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_test/manœuvre_test.cpp
=> Make the Manœuvre properly copyable by avoiding references to trajectories

ksp_plugin/flight_plan_optimization_driver.cpp, ksp_plugin/flight_plan_optimization_driver.hpp, ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin_test/flight_plan_optimizer_test.cpp
=> Reify the metric used to perform flight plan optimization

ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters
=> Fix problems introduced when merging into Wilkinson

ksp_plugin/flight_plan_optimization_driver.cpp, ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin_adapter/flight_planner.cs, numerics/gradient_descent_body.hpp
Optimization should be idempotent modulo the small errors introduced by UI rounding.  The root cause of the problem was that infinities made the metric discontinuous.
#3681.
=> Avoid the situation where repeatedly hitting the "optimize" button yields improved solutions

ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin_test/flight_plan_optimizer_test.cpp
Not particularly useful in and of itself (it will just set Δv to 0) but intended for use in combination with other metrics.
#3681.
=> A metric that minimizes Δv

ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin_test/flight_plan_optimizer_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp
=> Add linear combination of metrics

numerics/angle_reduction.hpp, numerics/angle_reduction_body.hpp, numerics/angle_reduction_test.cpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, testing_utilities/almost_equals.hpp, testing_utilities/almost_equals_body.hpp
This copies all the code related to reduction to a single place, and adds tests and matchers.  Not changing the clients yet.
#3768.
=> A library for angle reductions

astronomy/orbit_analysis_test.cpp, astronomy/orbit_ground_track_body.hpp, astronomy/orbital_elements_body.hpp, astronomy/trappist_dynamics_test.cpp, numerics/angle_reduction_body.hpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/double_precision_test.cpp, numerics/elliptic_integrals.cpp, physics/kepler_orbit_body.hpp, tools/generate_kopernicus.cpp
=> Change the clients of angle reduction

numerics/angle_reduction.hpp
=> More clangfigthing: actually use the value passed to the wrapper

numerics/angle_reduction.hpp
=> Even more clangfighting: Allow integers (in addition to doubles) in template instantiations

ksp_plugin_adapter/flight_planner.cs
#3658 put the branch in the wrong place. Spotted on Discord: https://discord.com/channels/319857228905447436/480397772248580098/1162137516560887958.
Maybe we should make that a C# enum and a switch statement.
=> Try harder to emit a message slightly more useful than "error 4"

ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg
=> Localization of flight plan optimization

ksp_plugin_adapter/flight_planner.cs
=> Fix rebasing

base/base.vcxproj, base/base.vcxproj.filters, base/push_pull_callback.hpp, base/push_pull_callback_body.hpp, base/push_pull_callback_test.cpp
This entails inverting the flow of control like we do for serialization/deserialization.
#2913.
=> Helper classes to have C++ code effectively call into C# in a way that is compatible with journaling

ksp_plugin/interface_collision.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs, physics/apsides_body.hpp, serialization/journal.proto
1. Prediction only.
2. Surface frame only.
3. Only one collision, located "somewhere".
4. May be entirely missing in some cases.
5. Flight plan unaffected.
#2913.
=> Limited C# support for displaying terrain collisions

ksp_plugin_adapter/flight_planner.cs
=> Don't try to recreate an optimizer after deleting the flight plan

benchmarks/newhall_benchmark.cpp, benchmarks/чебышёв_series_benchmark.cpp, numerics/newhall.hpp, numerics/newhall_body.hpp, numerics/newhall_test.cpp, numerics/чебышёв_series.hpp, numerics/чебышёв_series_body.hpp, numerics/чебышёв_series_test.cpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, serialization/numerics.proto
=> Generalize the Чебышёв series to take another argument than Instant

numerics/combinatorics.hpp, numerics/combinatorics_body.hpp, numerics/чебышёв_series.hpp, numerics/чебышёв_series_body.hpp, numerics/чебышёв_series_test.cpp
=> Frobenius companion matrix in the Чебышёв basis

numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp
=> Computation of the real Schur decomposition of a matrix

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/matrix_computations_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp
This makes the clients somewhat simpler.
=> Change the vector and matrix classes to reexport their Scalar parameter

geometry/interval.hpp, geometry/interval_body.hpp, physics/apsides.hpp, physics/apsides_body.hpp, physics/apsides_test.cpp, testing_utilities/matchers.hpp
=> A function to compute the time intervals where a trajectory can collide with a celestial

numerics/approximation.hpp, numerics/approximation_body.hpp, numerics/approximation_test.cpp
=> Adaptive Чебышёв polynomial interpolant with interval subdivision

ksp_plugin/plugin.cpp, numerics/approximation.hpp, numerics/approximation_body.hpp, numerics/approximation_test.cpp, physics/apsides_body.hpp
=> Avoid subdividing the zero-free intervals 

numerics/approximation.hpp, numerics/approximation_body.hpp, numerics/approximation_test.cpp, physics/apsides_body.hpp
=> Add a streaming computation of interpolants, and use it to stop once the first collision has been found

Makefile
=> Handle larger fold expressions in Clang

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, numerics/polynomial_in_чебышёв_basis.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp, serialization/numerics.proto
1. Add a base class that is agnostic to the degree and provides polymorphism.
2. Add _Mathematica_ support.
3. Add compatibility support for deserialization.
=> Improvements to PolynomialInЧебышёвBasis

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Don't remove a guidance node that is for another vessel

benchmarks/approximation_benchmark.cpp, find_msbuild.ps1, numerics/approximation.hpp, numerics/approximation_body.hpp, numerics/approximation_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/polynomial_in_чебышёв_basis.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp, numerics/quadrature_body.hpp, numerics/чебышёв_lobatto.hpp, numerics/чебышёв_lobatto_body.hpp, physics/apsides_body.hpp
Also some optimization of the Чебышёв-Lobatto points.
Benchmarks before:
```
-------------------------------------------------------------------------------------------------------------------
Benchmark                                                                         Time             CPU   Iterations
-------------------------------------------------------------------------------------------------------------------
ApproximationBenchmark<4>/AdaptiveЧебышёвPolynomialInterpolant4     21721212 ns     21484375 ns           32
ApproximationBenchmark<8>/AdaptiveЧебышёвPolynomialInterpolant8     16757837 ns     16387195 ns           41
ApproximationBenchmark<16>/AdaptiveЧебышёвPolynomialInterpolant16   17460602 ns     17708333 ns           45 …
```
=> Replace ЧебышёвSeries with PolynomialInЧебышёвBasis in the approximation code

serialization/journal.proto
Has something to do with #3822.
=> A bigger message

serialization/journal.proto
Reverts mockingbirdnest/Principia#3878
=> Revert "A bigger message" because it was not working

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_views.hpp, numerics/matrix_views_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp
=> Extract BlockView and ColumnView and make them independent from the other arrays

numerics/concepts.hpp, numerics/matrix_views.hpp, numerics/matrix_views_body.hpp, numerics/matrix_views_test.cpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters
=> Make BlockView and ColumnView complete and tested

.github/workflows/keep_alive.yaml
Running every 15 minutes for now, to help debug the action.
=> An action to keep runners alive

ksp_plugin_test/plugin_compatibility_test.cpp, numerics/fma.hpp
And avoid running the Reach test twice there.
=> Try to fix the clang build

ksp_plugin_adapter/main_window.cs
=> Next release is کاشانی

functions/std_accuracy_test.cpp
=> Fix sin/cos tolerances on Linux

functions/std_accuracy_test.cpp, ksp_plugin/flight_plan.cpp, numerics/polynomial_evaluators_body.hpp, numerics/polynomial_evaluators_test.cpp, physics/body_surface_reference_frame_body.hpp, physics/ephemeris_test.cpp, physics/lagrange_equipotentials_test.cpp
Also fix warnings emitted by Clang.
#1760.
=> Adjust the elementary functions tolerances

functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Support for creating accurate tables for multiple functions simultaneously

functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Add support for constructing accurate values in parallel

base/base.vcxproj, benchmarks/newhall_benchmark.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, numerics/newhall.hpp, numerics/newhall_body.hpp, numerics/newhall_test.cpp, numerics/polynomial_in_monomial_basis.hpp, numerics/polynomial_in_monomial_basis_body.hpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, serialization/numerics.proto, serialization/physics.proto
This will make it possible to use more efficient evaluators without affecting existing saves.
=> Add a mechanism to represent the policy used to choose the evaluator of a polynomial

numerics/concepts.hpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp, numerics/matrix_views.hpp, numerics/matrix_views_body.hpp, numerics/matrix_views_test.cpp, numerics/transposed_view.hpp, numerics/transposed_view_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp, testing_utilities/approximate_quantity_body.hpp
=> Implement classical Gram-Schmidt for matrices

functions/cos.cc, functions/sin.cc
=> Conditional compilation of core-math for Clang

Principia.sln, functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp, functions/functions.vcxproj, geometry/interval_body.hpp
=> A version of the Stehlé-Zimmermann algorithm that adaptively searches around a point

functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Change the Stehlé-Zimmermann algorithm to rescale the argument and function values

functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Fix a bug in the Stehlé-Zimmermann algorithm when T goes all the way down to 0

mathematica/floating_point.wl
=> Avoid leaking symbols in the public part of the Mathematica floating_point package

benchmark_automation/benchmark_automation.cs
=> Fix the benchmark automation script to handle / in a benchmark name

ksp_plugin_adapter/reference_frame_selector.cs
=> Fix a text overflow in the description of some frames

benchmarks/elementary_functions_benchmark.cpp, benchmarks/elementary_functions_experiments_benchmark.cpp
🍐
```
CPU Caches:
---------------------------------------------------------------------------------------------------------
Benchmark                                                               Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------
BM_EvaluateElementaryFunction<Metric::Latency, std::sin>             7.27 ns         7.15 ns     89600000 cycles: 27.5278
BM_EvaluateElementaryFunction<Metric::Throughput, std::sin>          2.12 ns         2.13 ns    344616000 cycles: 8.00057
BM_EvaluateElementaryFunction<Metric::Latency, cr_sin>               31.9 ns         32.2 …
```
=> Print the number of CPU cycles

numerics/double_precision_body.hpp, numerics/fma.hpp, numerics/polynomial_evaluators_body.hpp
=> Correct implementation of FMAPolicy::Force for Clang

mathematica/floating_point.wl
The syntax is something like `RoundingMode->Toward0` and the default is `RoundingMode->Automatic` which uses the global rounding mode.
#1760.
=> Add option RoundingMode to CorrectlyRound

ksp_plugin/interface.cpp
This won't fix #4026 but it will make the problem more apparent (and possibly help find the culprit).
=> Detect the case of a null guid or name in InsertOrKeepVessel

numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp
=> UnitriangularGramSchmidt for matrices with a zero column

base/not_null_test.cpp, geometry/hilbert.hpp, geometry/hilbert_body.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp, physics/euler_solver_body.hpp, tools/journal_proto_processor.cpp
No bugs fixed in this release.
=> Upgrade to Visual Studio 17.10.5

mathematica/mathematica.hpp, mathematica/mathematica_body.hpp
=> More errors found by Clang

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/lattices_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
=> Strictly upper triangular matrices

base/file.hpp, base/file_body.hpp, mathematica/logger_body.hpp
=> Flush harder in the Mathematica logger

benchmarks/planetarium_benchmark.cpp, ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/plotter.cs, serialization/journal.proto
This is not the final resolution of #4048, because now we obviously have too many markers:
#4048.
=> Don't draw the prediction or flight plan after the first collision, if any

numerics/angle_reduction.hpp, numerics/angle_reduction_body.hpp, numerics/double_precision_body.hpp, numerics/elliptic_integrals.cpp, numerics/elliptic_integrals_test.cpp
=> Return NaN on elliptic integrals that are applied to angles so large that we cannot reduce them

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg
=> Add a button to select the time base of a manœuvre

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs
🍐
Also fix a bug in the display of manœuvre markers.
Fix #3485.
=> Display the target Clear and Switch To buttons when not in map view.

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/plotter.cs
🍐
Also fix a crash when going to map view without a main vessel.
Fix #4071.
=> Display the target vessel trajectory even in the absence of a main vessel

numerics/root_finders.hpp, numerics/root_finders_body.hpp
Brought to our attention by @gotmachine.
=> Modernize SolveQuadraticEquation

README.md, functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Speed up Stehlé-Zimmermann by using locally-constructed Taylor polynomials

functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
=> Continue with searching a slice when a solution is rejected

Makefile
=> Use core-math on macOS and Ubuntu

Makefile
=> Use SSE4.1 (introduced in 2007)

SUPPORT.md
=> I know a dead forum when I see one, and I'm looking at one right now

ksp_plugin/interface_planetarium.cpp, ksp_plugin/plugin.cpp
Apparently the bug was introduced in January 2022 in #3268.
Fix #4119.
=> Make sure that a deserialized flight plan exists before accessing the flight plan

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #4135.  Well, doesn't fix it, really, but makes the detection more straightforward.
=> Improved detection of broken mods

benchmarks/rigid_reference_frame_benchmark.cpp
TL;DR: It is awfully slow:
```
CPU Caches:
------------------------------------------------------------------------------------------
Benchmark                                                Time             CPU   Iterations
------------------------------------------------------------------------------------------
BM_BodyCentredNonRotatingReferenceFrame/1024001        279 ms          281 ms            3
BM_BarycentricRotatingReferenceFrame/1024001          3965 ms         3953 ms            1
BM_RotatingPulsatingReferenceFrame/1024001           51332 ms        51297 ms            1
```
=> A benchmark for the Sun-Neptune rotating pulsating reference frame

physics/barycentric_rotating_reference_frame.hpp, physics/barycentric_rotating_reference_frame_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
Similar to #4171.  No visible effects on the benchmarks.
=> Optimization of the computation of the jerk

ksp_plugin/frames.hpp, ksp_plugin_test/planetarium_test.cpp, mathematica/logger.hpp, mathematica/logger_body.hpp, physics/equipotential_test.cpp
Mostly a change detector at this point, but should be a basis for evaluating changes to the plotting algorithm.
=> A test for PlotMethod3

numerics/root_finders.hpp, numerics/root_finders_body.hpp, numerics/root_finders_test.cpp
It separates the zeroes by looking for extrema.
=> An algorithm to find all zeroes of a function over an interval

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/interface.cs
Reported on Discord by "mako":
=> Handle "resource exhausted" in the flight planner UI

ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs
=> Don't display the 0 button on the slider that defines the final time of the flight plan.

ksp_plugin/interface.cpp
=> Log the size of the geopotential, it helps debugging custom solar systems

mathematica/ieee754_floating_point_evaluation.wl, mathematica/ieee754_floating_point_evaluation_test.wl
Also some rewriting of `IEEEEvaluate` to make it more consistent with the rest and easier to maintain.
#1760.
=> Add support for rounding reals and for evaluation polynomials

mathematica/ieee754_floating_point_evaluation.wl, mathematica/ieee754_floating_point_evaluation_test.wl
=> Support for polynomials in relative/absolute error computation

numerics/sin_cos.cpp
=> Adjust the polynomials based on more precise Mathematica computations

mathematica/ieee754_floating_point_evaluation.wl, mathematica/ieee754_floating_point_evaluation_test.wl
=> Addition of quantities that have no error intervals

numerics/sin_cos.cpp
I don't want to wait until the documentation is in to have the updated code available.
#1760.
=> Code changes to Sin/Cos extracted from #4269

benchmarks/elementary_functions_experiments_benchmark.cpp, geometry/grassmann.hpp, geometry/grassmann_body.hpp, geometry/point.hpp, geometry/point_body.hpp, geometry/rp2_point_body.hpp, numerics/cbrt.cpp, numerics/cbrt_test.cpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/double_precision_test.cpp, numerics/elementary_functions.hpp, numerics/elementary_functions_body.hpp, numerics/fma.hpp, numerics/m128d_body.hpp, numerics/newhall_test.cpp, numerics/polynomial.hpp, numerics/polynomial_evaluators.hpp, numerics/polynomial_evaluators_body.hpp, numerics/root_finders_body.hpp, numerics/sin_cos.cpp, tools/journal_proto_processor.cpp
=> Rationalize the APIs related to FMA

numerics/m128d_test.cpp
=> Another test that fails on Clang
