mockingbirdnest/Principia

ksp_plugin/rendering_frame.cpp, physics/transforms.hpp, physics/transforms_body.hpp, physics/transforms_test.cpp
Mostly, that's because they access the prolongation and the prolongation constantly gets deallocated and reallocated.
=> The transforms should evaluate the trajectories lazily

geometry/epoch_body.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/physics_bubble.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_interface.cs, ksp_plugin_test/interface_test.cpp
Fix the "crashes crash" bug (due to adding 0-part vessels to the physics bubble), the bug where the plugin would still manage the physics bubble at ground level on bodies without an atmosphere, and the bug where a crashed vessel would keep being simulated.
Improved performance by not calling `FindObjectOfType` at every frame.
=> Cauchy distribution

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp
This is well-defined since members are initialized in order of declaration and `sun_` is declared last.
=> Todo regarding sun initialization

ksp_plugin/frames.hpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/vessel_test.cpp, serialization/ksp_plugin.proto, serialization/serialization.vcxproj, serialization/serialization.vcxproj.filters
`Vessel` serialization, and a big proto file outlining the way forward.
I'm not sure making these big types movable (we started doing that with `Trajectory`) is a good idea. We don't make them move-assignable (otherwise we can't have `const` member variables), so we almost always have to put them in `not_null<std::unique_ptr<T>>`s, which means that factories that return a `T` directly are always used with a `make_not_null_unique<T>`. Moreover, it's easy to break invariants when writing a move constructor: we had to use `swap`s to make sure `Trajectory` was safe (it's still unsafe for past-the end `Iterator`s, although that's a minor issue), here I spent an hour tracking a bug due to a missing `prolongation_(std::move(other.prolongation_)),` which could easily have slipped past testing …
=> Vessel proto

ksp_plugin/celestial.hpp, ksp_plugin/celestial_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.hpp, ksp_plugin/vessel_body.hpp
Also change `Celestial::parent` and `Vessel::parent` to return pointers.
Fix #433 because we'll deal with any remaining issues when we notice them.
=> Remove more & applied to references

ksp_plugin_adapter/ksp_plugin_adapter.cs
Now that the plugin auto-starts, make it clear that this is a manual override.
=> Reword button

ksp_plugin_adapter/ksp_plugin_adapter.cs
Thanks to @diomedea for reporting this!
When reverting to VAB, the old save is loaded immediately, but the time is only reset when exiting the VAB. Running Principia in the editor causes it to integrate back to the future, and causes a `FATAL` failure (Closed Timelike Curve) when KSP's time gets reverted.
See the graph below:
Horizontal axis is real time, in hundreds of nanoseconds since `0001-01-01T00:00:00Z` Gregorian.
Vertical axis is KSP time in seconds since the beginning of the game.
Orange is plugin timestamps, blue is KSP timestamps. The difference is highlighted by thick black bars.
Green lines indicate serializations, red lines deserializations.
The first revert is a revert to launch, the second is a revert to VAB. The log ends (with a crash) when exiting the VAB.
=> Do not crash on revert to VAB

physics/transforms.hpp, physics/transforms_body.hpp
As part of investigating #451, adding traces shows good cache hit ratio for the histories and none for the predictions, which is as expected given the state of things:
```
I0419 13:45:37.631872  4444 transforms_body.hpp:308] Hit ratio for trajectory 62126AE8 is 0.999347
I0419 13:45:37.690878  4444 transforms_body.hpp:308] Hit ratio for trajectory 62126AE8 is 0.999347
I0419 13:45:37.723881  4444 transforms_body.hpp:308] Hit ratio for trajectory 4A897E60 is 0.975899
I0419 13:45:37.780887  4444 transforms_body.hpp:308] Hit ratio for trajectory 62126AE8 is 0.999349
I0419 13:45:37.838893  4444 transforms_body.hpp:308] Hit ratio for trajectory 62126AE8 is 0.999347
I0419 13:45:37.865896  4444 transforms_body.hpp:308] Hit ratio for trajectory 4A898060 is 0
I0419 13:45:37.928902  4444 …
```
=> Monitoring the caching of transforms.

ksp_plugin/plugin.cpp, physics/transforms.hpp, physics/transforms_body.hpp
This fixes a bug where the graph of predictions was oscillating between two trajectories because of deallocated/reallocated pointers left in the cache.
=> Add a hook to control cacheability of lazy trajectories

ksp_plugin/plugin.cpp, ksp_plugin_test/plugin_test.cpp
The rotation axis was stupidly tansformed as if it were a vector [during the flipping of `Barycentre`](https://github.com/mockingbirdnest/Principia/commit/ddeaba08527bcdc40f35283140fcf9bf925e1bd9#diff-5e7c3a9ac924e644e0a57506e5e1a2a3R582).
This made the planet on which the player is rotate backwards (with respects to the planets; the fixed stars rotated backwards too for some reason), yielding some pretty sunsets in the east.
=> Make the sun set in the west again.

integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp
This looks far more elegant than it did in the SPRK/SRKN.
=> Handle the FSAL property in the embedded ERKN

base/macros.hpp, ksp_plugin_test/plugin_test.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp
This issue was fixed in the new class Ephemeris, but it turns out that the resulting trajectories are very large and cause memory problems.  We'll properly address this mess by decimating trajectories post-Bourbaki, but for Bourbaki the best approach is to restore the bug.
=> Restore issue #228

base/base.vcxproj, benchmarks/benchmarks.vcxproj, geometry/geometry.vcxproj, integrators/integrators.vcxproj, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj, mathematica/mathematica.vcxproj, numerics/numerics.vcxproj, physics/physics.vcxproj, quantities/quantities.vcxproj, testing_utilities/testing_utilities.vcxproj
It has very many errors probably because Microsoft changed their mind between VS 2014 CTP and VS 2015 regarding characters.
=> Use the latest greatest LLVM

mathematica/navball.wl
This allows for differently-coloured meridians and text in the three regions (north, south, equatorial band).
Example:
=> Old code written to make a custom navball for diomedea

ksp_plugin/interface.cpp, physics/body_test.cpp, physics/ephemeris_test.cpp, physics/massive_body.hpp, physics/massive_body_body.hpp, physics/oblate_body.hpp, physics/oblate_body_body.hpp, testing_utilities/solar_system_body.hpp
Introduce Parameters classes to reduce the combinatorial explosion of parameters in constructors.  This is preliminary work for rotating bodies.
=> Change the parameterization of MassiveBody and OblateBody

astronomy/astronomy.vcxproj, geometry/permutation.hpp, geometry/permutation_test.cpp, google_glog.props, google_googlemock_main.props
This requires to remove an include of `gtest_prod.h`.
=> Change the properties files so that _test is only appended to the exe name if googletest is imported

geometry/barycentre_calculator.hpp, geometry/barycentre_calculator_body.hpp, geometry/pair.hpp, geometry/pair_body.hpp, geometry/pair_test.cpp, geometry/point.hpp, geometry/point_body.hpp, geometry/point_test.cpp, ksp_plugin/physics_bubble.cpp, ksp_plugin_test/physics_bubble_test.cpp, mathematica/integrator_plots.cpp, physics/barycentric_rotating_dynamic_frame_body.hpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centered_non_rotating_dynamic_frame_test.cpp, physics/degrees_of_freedom.hpp, physics/degrees_of_freedom_body.hpp, physics/degrees_of_freedom_test.cpp, physics/ephemeris_test.cpp, physics/transforms_body.hpp, physics/transforms_test.cpp
* `BarycentreCalculator` is now specialized for all the classes that need it, instead of being sometimes a nested template.
* `Barycentre` is implemented one and is available for all the classes that have a`BarycentreCalculator`.
* All of this is in `geometry`, not in random namespaces.
=> Cleanup and restructuring of barycentre computations

Makefile, Vagrantfile
Just a minor tweak to the Makefile since it was previously ending up doing a lot of unnecessary recompiling while trying to fix errors.
=> Prevent Makefile cleaning up valid .o files on build errors.

astronomy/astronomy.vcxproj, base/base.vcxproj, benchmarks/benchmarks.vcxproj, benchmarks/dynamic_frame.cpp, benchmarks/ephemeris.cpp, define_ndebug.props, geometry/geometry.vcxproj, integrators/integrators.vcxproj, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/physics_bubble_test.cpp, mathematica/mathematica.vcxproj, numerics/numerics.vcxproj, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp, physics/physics.vcxproj, quantities/quantities.vcxproj, serialization/serialization.vcxproj, testing_utilities/testing_utilities.vcxproj
* Remove `TransformingIterator` and related types and functions.
* Rename `NativeIterator` into `Iterator`.
* Remove most of the old iterator API: `first`, `on_or_after`, `Positions`, `Velocities`, `Times`, `at_end`.
* Add methods `Size` and  `Fork` to `Forkable`.
* Remove `ForkTime`.  Clients should use `Fork` instead.
=> Simplify the API of DiscreteTrajectory by removing functions and types that we don't need anymore

base/not_null.hpp, base/not_null_body.hpp, base/not_null_test.cpp
I had to look at the standard for this one.
See also this example with a dummy `not_null` http://goo.gl/PJoIfa.
Once again, clang is the closest we have to the standard.
See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf 13.3.3.2 (this document should really be in the bibliograhpy...).
=> More Confusing C++

benchmarks/sprk_integrator.cpp, benchmarks/symplectic_runge_kutta_nyström_integrator.cpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp
Changes to the benchmark speed up by roughly 20% and are for fairness with legacy benchmarks.  Changes to the integrator speed up by roughly 12%.
=> Optimize the benchmarks for SymplecticYadaYada

ksp_plugin/vessel_body.hpp, physics/discrete_trajectory_body.hpp
Also some cleanup of DiscreteTrajectory.
Fix #659.
=> Do not append the last point of the prolongation if it matches the last point of the history

ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/mock_plugin.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp
The selector no longer owns its navigation frame, it is (explicitly, safely) owned by the plugin instead.
Two transfers of ownership occur at creation, but locally in the C#.
=> C# should not own things

benchmarks/benchmarks.vcxproj, journal/journal.vcxproj, journal/player_test.cpp
This makes it possible to measure the CPU time semi-accurately and it solves the odd coverage in Jenkins.
For instance, timing pre-PGO:
```
Run on (1 X 3310 MHz CPU )
2015-12-12 12:43:04
Benchmark        Time(ns)    CPU(ns) Iterations
-----------------------------------------------
BM_PlayForReal 36580656528 30030192500          1
```
and timing post-PGO:
```
Run on (1 X 3310 MHz CPU )
2015-12-12 12:43:04
Benchmark        Time(ns)    CPU(ns) Iterations
-----------------------------------------------
BM_PlayForReal 34107412577 27003773100          1
```
Considering that profiling shows 41.8% spent parsing the journal (code that's not affected by PGO) this means that PGO buys us a 19% speedup on the code that we care about.
=> Change the player test to be a test/benchmark mix

geometry/affine_map_test.cpp, geometry/identity_body.hpp, geometry/orthogonal_map_body.hpp, geometry/orthogonal_map_test.cpp, geometry/permutation_body.hpp, geometry/permutation_test.cpp, geometry/rotation_body.hpp, geometry/rotation_test.cpp, physics/body_test.cpp, physics/massive_body_body.hpp, physics/oblate_body_body.hpp, physics/rotating_body_body.hpp, serialization/geometry.proto, serialization/integrators.proto, serialization/physics.proto
=> Rename all extensions to be named `extension`.

ksp_plugin/interface_flight_plan.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp
There was a bug in the plotting of the Frenet trihedron in a rotating frame that suggests we may want to distinguish `World` and `PlottedWorld` somehow, since the plotting operation, namely from `Barycentric` to `Navigation` (`plotting_frame`) at actual time and then from `Navigation` (`plotting_frame`) to `Barycentric` at current time, does not change the type.
=> Draw the Frenet trihedron

Makefile, physics/hierarchical_system_test.cpp, physics/kepler_orbit_test.cpp
Fix #855.
In particular, define `NDEBUG`; this might improve performance.
=> Linux test fixes

integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp, integrators/ordinary_differential_equations.hpp
A simple implementation, working towards #846 (still needs to be used in the ephemeris).
Do we want to have a callback or a status of sorts to report early termination? In the flight plan, we will need to know it occured in order not to compute the remaining segments.
=> Maximal step count

geometry/affine_map.hpp, geometry/affine_map_body.hpp, ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/plugin.cpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp
Fixes #872.  Added a check so that similar bugs would be easier to detect in the future.
=> Do not forget the past of histories if that would destroy flight plans

install_deps.sh
make sure aclocal.m4 api version matches up with local version of autotools (there may be a better way to do this)
=> fix aclocal issues

stacktrace_decoder/stacktrace_decoder.cs
This decoder has become more useful than expected, so we now pretty much always want to decode.
=> Decode decoded stacks

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs
* Apsides for the prediction (I'm not sure whether we want to keep using the colour of the celestial, we'll see how things turn out in practice).
* "Warp to manœuvre" button, warps with 1 min overhead.
* Solid line for the planned burns (they're quite short, the dashing is a bit silly there).
* Change the parity of the dashing so that burns start at the marker and end at a colour change.
* Qualify the apsides so one can tell whether they're from the prediction or the flight plan.
* Prevent the navball markers from disappearing or fading when they're right in the middle.
=> Various usability fixes

ksp_plugin_adapter/ksp_plugin_adapter.cs
Apparently casting to float doesn't force the conversion, and the comparison occurred in double. `Convert.ToSingle` seems to do the job.
=> Fix the stock jool system detection

physics/barycentric_rotating_dynamic_frame.hpp, physics/barycentric_rotating_dynamic_frame_body.hpp, physics/body_centered_non_rotating_dynamic_frame.hpp, physics/body_centered_non_rotating_dynamic_frame_body.hpp, physics/dynamic_frame.hpp, physics/dynamic_frame_body.hpp, physics/dynamic_frame_test.cpp, physics/mock_dynamic_frame.hpp, physics/rigid_motion.hpp, physics/rigid_motion_body.hpp
This should also enable cleaner unit testing of the linear, Coriolis, centrifugal, and Euler accelerations (for now the [tests](https://github.com/mockingbirdnest/Principia/blob/f54bcf9589d79b38a651d8af8fbc441db3b48fb6/physics/barycentric_rotating_dynamic_frame_test.cpp#L216-L482) from BarycentricRotatingDynamicFrame take care of that).
=> Factor fictitious accelerations

ksp_plugin/plugin.cpp, physics/rotating_body.hpp, physics/rotating_body_body.hpp
This addresses #1111, and it also fixes a where bodies whose reference pole was the negative pole would rotate opposite to their scaled body.
=> Rotating body angular frequency accessor

ksp_plugin/plugin.cpp
And the apocalypse is back (probably because `g` was stupidly reset to 9.81 m/s^2) so: fix #1115.
=> New fingerprints for 1.2.1

integrators/symplectic_runge_kutta_nyström_integrator_body.hpp, ksp_plugin_test/plugin_integration_test.cpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/ulp_distance.hpp, numerics/ulp_distance_body.hpp, physics/continuous_trajectory_body.hpp, testing_utilities/almost_equals_body.hpp, testing_utilities/numerics.hpp, testing_utilities/numerics_body.hpp, testing_utilities/vanishes_before_body.hpp
Following these changes, across all `*.hpp` files, `#include "testing_utilities` occurs only in `testing_utilities`.
This fixes #1165.
=> ULP distance in numerics

documentation/Setup.md
Unity assembly `UnityEngine.UI.dll` is also required from `<KSP directory>\KSP_Data\Managed`
See Principia/ksp_plugin_adapter/ksp_plugin_adapter.csproj lines 55 thru 58:
https://github.com/mockingbirdnest/Principia/blob/3b6af2d12fe43e905346381b4593c294952fe89c/ksp_plugin_adapter/ksp_plugin_adapter.csproj#L56
=> Unity assembly `UnityEngine.UI.dll`

generate_version_header.ps1, ksp_plugin/interface.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/pile_up_test.cpp, parallel_test_runner/parallel_test_runner.cs, serialization/journal.proto
Stop using `PhysicsBubble` in the adapter, start using the `PileUp`-related functions. This is hilariously broken at the moment because we get a correction from the velocity relative to the barycentre of the solar system (we shouldn't try to convert anyway, we don't have anything to refer to right after AdvanceTime).
=> Out with the old, in with the new

ksp_plugin/interface.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Engines are now taken into account correctly, and conservation of momentum is otherwise enforced. Stage separation appears to work, however it also seems to jettison the camera for a while. This needs to be looked into.
=> Do not ignore engines

ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Today in "KSP is dumb": the FloatingOrigin system puts the origin where the root part of the vessel is (i.e. at top typically). Then the camera is offset from that so that it's at the barycentre of the vessel. Because putting the barycentre of the thing to which physics happens at 0 and the camera looking there would be too sane.
=> Fix the camera and selection bugs

ksp_plugin_adapter/ksp_plugin_adapter.cs
Together with @sarbian's commits on ModularFlightIntegrator, see https://github.com/sarbian/ModularFlightIntegrator/compare/89c79c0fa26b95989e49e4c37e72835693228aff...448a324efa30c4f47f9198c68982e0df5ada5bc9, this fixes an issue where vessels spawned in space, e.g. by decoupling, would measure an incorrect acceleration and prevent timewarp.
=> Fix an issue with ModularVesselPrecalculate

ksp_plugin_adapter/reference_frame_selector.cs
Earth-Centred Sun-Fixed is confusing (the sun isn't really fixed, because of the excentricity), it sounds too much like Earth-Centred Earth-Fixed, and it can lead to unnecessary acronym collisions, e.g. SCSF for either Saturn-Centred Saturn-Fixed or Saturn-Centred Sun-Fixed (SCSA with the new convention).
=> Rename the body-centred-body-direction frame

astronomy/solar_system_dynamics_test.cpp, base/not_null.hpp, base/not_null_body.hpp, base/not_null_test.cpp, ksp_plugin/celestial.cpp, ksp_plugin/celestial.hpp, ksp_plugin/interface.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/celestial_test.cpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/mock_plugin.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp
The `physics` layer still operates on massive bodies, so a few conversions are needed when crossing from `ksp_plugin` to `physics` and back.
Fix #1112.
=> Change Plugin and Celestial to operate on rotating bodies instead of massive bodies.

numerics/hermite3.hpp, numerics/hermite3_body.hpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
`DiscreteTrajectory` is now a `Trajectory`. The existing use of `Hermite3` is also for interpolation of discrete trajectories (when computing apsides in `Ephemeris`), we may want to switch to `Evaluate` there too in a future CL.
=> Evaluate discrete, first cut without hinting

ksp_plugin_adapter/reference_frame_selector.cs
`primary` and `secondary` for the body-centred, body direction frame are confusing, especially since we use the secondary as primary and vice-versa; perhaps we should use centre (as is the convention for the other body-centred frames) and [something, maybe `primary` would be fine in that case] instead.
=> Correctly read the NavigationFrameParameters in the ReferenceFrameSelector

physics/body_centred_body_direction_dynamic_frame.hpp, physics/body_centred_body_direction_dynamic_frame_body.hpp, physics/body_centred_body_direction_dynamic_frame_test.cpp
Maybe eventually we'll split the classes, for the moment this is more convenient.
=> Make the primary_trajectory_ functor return a constreference

ksp_plugin_adapter/ksp_plugin_adapter.cs
We now manage FLYING vessels too, because sometimes all vessels are reported as FLYING. This might fix maccollo's latest bug.
=> Motivate vessel removal

ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/vessel.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_test.cpp, serialization/journal.proto
The orbits of KSP's `Vessel`s are updated at `Early/Timing1(-99)`, whereas we updated the parents (in `InsertOrKeepVessel`) at `WaitForFixedUpdate`. This meant that for one frame, we would end up giving KSP offsets around the wrong body. Depending on various factors, this would put the vessel inside the sun, or sometimes merely dewarped to 1x (if the vessel escaped destruction, it would go back to the right place in the next frame).
This pull request also logs main body changes, similarly to vessel renamings.
=> Prevent the sun from slapping interplanetary vessels

base/disjoint_sets.hpp, ksp_plugin/interface.cpp, ksp_plugin/interface.hpp, ksp_plugin/interface_body.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/interface_iterator.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, serialization/integrators.proto, serialization/journal.proto
* Factor out the code that converts `XYZ` and `QP` to and from typed entities.
* The interface should not be the one deciding which integrator we use.
* Remove the `GetVessel` "abstraction".
=> A bunch of cleanups in the interface

astronomy/sol_initial_state_jd_2433282_500000000.cfg, physics/solar_system.hpp, physics/solar_system_body.hpp, tools/generate_configuration.cpp
This was broken in Catalan, but fixed in a hurry by a patch to the configuration.  This is the proper change for Cauchy.
=> Fix a bug in the generation of the RSS config

ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/interface_renderer_test.cpp, physics/kepler_orbit_test.cpp, testing_utilities/almost_equals_body.hpp
but some NaNs are less equal than others.
This fixes the Kepler orbit tests on Linux.
=> All NaNs are almost equal

astronomy/ksp_resonance_test.cpp, base/macros.hpp
=> Disable resonance tests on Linux

ksp_plugin/plugin.cpp, ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp, ksp_plugin_adapter/map_node_pool.cs
Shows the speed (in the plotting frame) on periapsis, apoapsis, and locally closest approach markers. Shows the speed normal to the reference plane on ascending/descending node markers.
=> Speed indications on markers

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #1404.
Somehow there are vessels that briefly register as being at the centre of Kerbin; let's keep managing those.
=> Prevent atmospherically flying vessels from briefly considered as manageable on quickload

journal/player_test.cpp, ksp_plugin_test/interface_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, stacktrace_decoder/stacktrace_decoder.cs
Unfortunately I wasn't able to write a unit test because I could create the unalignment in the first place.  It's unclear how the unaligned save came to be, but it's possible that this has something to do with #1395.  Anyway with this PR it is possible to read the save and to continue playing.
Fix #1422.
=> Fix ForgetBefore when the instance is not aligned with the polynomials

ksp_plugin_adapter/ksp_plugin_adapter.cs
The answer to [this question](http://answers.unity3d.com/questions/950463/waitforfixedupdate-coroutine-happens-after-the-int.html) was instrumental in getting a hold on this issue. It appears that setting the position of a rigid body is only reflected on its transform when Unity's physics run. We set the positions right after Unity's physics run (as a corrector), so setting the position only would mean that the position and transform would always be inconsistent; a plausible explanation is that the difference between the two was due to gravity (so vertical), and that the force would then be applied at one of the two while the centre of gravity was at the other (inducing a torque to right the force).
=> Fix a bug that induced a torque tending to make vessels thrust upwards.

documentation/Setup.md
Blank lines around headers, spaces after pound signs in headers. The old version doesn't render properly on Github.
=> Markdown formatting fixes

ksp_plugin/plugin.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
As mentioned in #1414, it makes sense to display nodes in, e.g., the EMB and MCEA frames like we do in the target LVLH frame.
=> Display nodes in orbital frames

geometry/perspective_body.hpp
Before:
```
BM_VisibleSegmentsOrbit/10                        3272 ns       3285 ns     213674 average visible segments: 1.000000
BM_VisibleSegmentsOrbit/100                      31592 ns      31289 ns      22436 average visible segments: 0.980000
BM_VisibleSegmentsOrbit/1000                    312704 ns     310417 ns       2362 average visible segments: 0.966000
BM_VisibleSegmentsRandomEverywhere/1000         136836 ns     137666 ns       4986 average visible segments: 1.073000
BM_VisibleSegmentsRandomNoIntersection/1000     106438 ns     102207 ns       7479 average visible segments: 1.000000
```
After:
```
BM_VisibleSegmentsOrbit/10                        1835 ns       1836 ns     407923 average visible segments: 1.000000
BM_VisibleSegmentsOrbit/100                      11361 ns …
```
=> Speed up hiding computations by exiting early if the sphere is far enough to the right or left of the segment

ksp_plugin/interface.cpp, ksp_plugin/part.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Since it is sometimes called when the parts are ahead of `current_time_`.
Fix #1416.
Also fix a nonsensical comment.
=> Pass a time to CelestialWorldDegreesOfFreedom

Makefile, generate_version_translation_unit.sh, install_deps.sh, ksp_plugin_adapter/ksp_plugin_adapter.dll.config
WIP WIP WIP WIP WIP
🚧  DO NOT MERGE 🚧 
some of the patches to the Makefile need to be made conditional or they'll most likely break Linux builds as well.
=> MacOSX support

geometry/perspective_body.hpp, numerics/hermite3.hpp, numerics/hermite3_body.hpp, numerics/root_finders.hpp, numerics/root_finders_body.hpp, numerics/root_finders_test.cpp, physics/apsides_body.hpp
Before:
```
Benchmark                                            Time           CPU Iterations
----------------------------------------------------------------------------------
BM_VisibleSegmentsOrbit/10                        1196 ns       1196 ns     560894 average visible segments: 1.000000
BM_VisibleSegmentsOrbit/100                       6736 ns       6606 ns      89743 average visible segments: 0.980000
BM_VisibleSegmentsOrbit/1000                     63809 ns      63969 ns      11218 average visible segments: 0.966000
BM_VisibleSegmentsRandomEverywhere/1000          68781 ns      68141 ns      11218 average visible segments: 1.073000
BM_VisibleSegmentsRandomNoIntersection/1000      44980 ns      44778 ns      16026 average visible segments: 1.000000
```
After:
```
Benchmark …
```
=> BoundedArray for Hermite and quadratic equations

base/macros.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/renderer.cpp, physics/ephemeris_body.hpp
=> Remove most VLOG and a function and a macro that now have no purpose

ksp_plugin/interface_future.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
Use the new futures to catch up asynchronously, log the time between the first promise and the first wait.
=> Asynchronous catch up

benchmarks/ephemeris.cpp, physics/solar_system_body.hpp
The results show the benefits of multithreading.  Note that the CPU times are garbled:
```
08/28/17 21:34:02
Benchmark                                        Time           CPU Iterations
BM_EphemerisMultithreadingBenchmark/3/1  165484370 ns     156001 ns        100 +9.98764788828618452e+06 m +1.99940980342582799e+07 m +2.99994767005582713e+07 m
BM_EphemerisMultithreadingBenchmark/3/2  113980341 ns          0 ns        100 +9.98764788828618452e+06 m +1.99940980342582799e+07 m +2.99994767005582713e+07 m
BM_EphemerisMultithreadingBenchmark/3/3   64404856 ns          0 ns        100 +9.98764788828618452e+06 m +1.99940980342582799e+07 m +2.99994767005582713e+07 m …
```
=> Benchmark for parallelism in the Ephemeris

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
See the last comment of #1552.
=> Remove an unused member variable and use a nicer output path

ksp_plugin/interface.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp, ksp_plugin/vessel.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/renderer_test.cpp, serialization/journal.proto
This was noticed when investigating #1561 (the new test show a case where we evaluate the prediction after its last point) but this is really unrelated because #1561 is about evaluating the prediction before its first point.
Also making `Vessel::UpdatePrediction` idempotent for performance.
=> Move the code that extends the prediction to Renderer

geometry/identity_test.cpp
Errors emitted were of the form
```
geometry/identity_test.cpp:77:19: error: qualified reference to 'Identity' is a
constructor name rather than a type in this context
EXPECT_THAT(Id::Identity().Inverse()(vector2).coordinates(),
^
```
To be honest, not sure since this is an actual problem rather than a compiler bug, since the code appears to have always been that way...
The way I fixed the compilation error was chosen because I noticed that the code under `TEST_F(IdentityTest, Determinant)` had a "standalone" (for lack of a better phrase) `Id` object, unlike the code causing the errors.
=> Fix compilation errors emitted by Clang 5.0

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Do not show the trajectory of the target if there is no active vessel.

ksp_physics/ksp_physics_lib.cpp
ksp_physics_lib.cpp gets picked up as part of the `LIBRARY_TRANSLATION_UNITS` Makefile target. Make sure it compiles.
=> Fix the build on *nix

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp
In favorable cases this is about 30% faster.  In unfavorable cases this is marginally slower, but probably in the noise.
Before:
```
----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                               Time           CPU Iterations
----------------------------------------------------------------------------------------------------------------------
BM_EphemerisMultithreadingBenchmark/3/1                                         172615405 ns          0 ns        100 +9.98764788888029195e+06 m +1.99940980346540436e+07 m +2.99994767007804625e+07 m
BM_EphemerisMultithreadingBenchmark/3/2                                         119318150 ns          0 ns …
```
=> Cache the index of the last accessed polynomial

geometry/r3_element_body.hpp, quantities/generators.hpp, quantities/quantities.hpp, quantities/quantities.vcxproj, quantities/quantities.vcxproj.filters, quantities/quantities_body.hpp, quantities/wide.hpp, quantities/wide_body.hpp, quantities/wide_test.cpp, testing_utilities/matchers.hpp
I am dropping `FromM128D` because:
1. We don't use it.
1. It doesn't work well with overloading because there's no overloading on the return type.  No tag types today.
=> A new class, Wide, to hold a 128-bit SSE representation of a quantity or double

geometry/r3_element_body.hpp, quantities/wide.hpp, quantities/wide_body.hpp, quantities/wide_test.cpp
It didn't give us the speed-up that we were hoping for, and it was making the code a bit clunky.  If someone wants to resurrect it, the full implementation is in [pleroy/WideOp2](https://github.com/pleroy/Principia/tree/WideOp2).
=> Remove class Wide

integrators/cohen_hubbard_oesterwinter.hpp, integrators/cohen_hubbard_oesterwinter_body.hpp, integrators/symmetric_linear_multistep_integrator.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp, integrators/symmetric_linear_multistep_integrator_test.cpp, mathematica/cohen_hubbard_oesterwinter.wl, physics/ephemeris_test.cpp
This brings significant improvements in accuracy and in speed:
Before:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 90719773589 ns 90371379300 ns          1 +9.92179030813603147e-01 ua
```
After:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 55156286341 ns 54912352000 ns          1 +9.92179030813603147e-01 …
```
=>  Implement the Cohen-Hubbard-Oesterwinter method

base/macros.hpp, geometry/r3_element.hpp, geometry/r3_element_body.hpp, numerics/newhall_body.hpp, quantities/elementary_functions_body.hpp, quantities/quantities.hpp, quantities/wide.hpp, testing_utilities/matchers.hpp
Also remove the usages of `Pow` in the Newhall code.
Before:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 55156286341 ns 54912352000 ns          1 +9.92179030813603147e-01 ua
```
After:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 52191586623 ns 51745531700 ns          1 +9.92179030813603147e-01 ua
```
=> Implement Sqrt using intrinsics

benchmarks/newhall.cpp
Results:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                        Time           CPU Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_NewhallApproximationDouble<Result???????Double,&NewhallApproximationIn???????Basis<double>>/4
933 ns        946 ns    1121788
BM_NewhallApproximationDouble<Result???????Double,&NewhallApproximationIn???????Basis<double>>/8
962 ns       1046 ns     641022
BM_NewhallApproximationDouble<Result???????Double,&NewhallApproximationIn? …
```
=> Better benchmarks for Newhall

geometry/r3_element_body.hpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp
This results in a 5-15% speedup depending on the benchmark.
Before:
```
----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                               Time           CPU Iterations
----------------------------------------------------------------------------------------------------------------------
BM_EphemerisMultithreadingBenchmark/3/1                                         114441042 ns          0 ns        100 +9.98765334517185204e+06 m +1.99941208075259104e+07 m +2.99993670271172673e+07 m
BM_EphemerisMultithreadingBenchmark/3/2                                          85154387 ns          0 ns        100 +9.98765334517185204e+06 m +1.99941208075259104e+07 m …
```
=> Optimize some R3Element operators and FixedVector scalar products

parallel_test_runner/parallel_test_runner.cs
The correct solution would be to:
* Change `gmock_main` to take a `wchar_t` and to use a `wmain`.  This requires to move `InitGoogleLogging` at a place where it can convert `argv[0]` to narrow.
* Change the Principia projects to use `wmainCRTStartup` as the linker entry points.
* Change the `parallel_test_runner.cs` to just pass unencoded strings when starting the test processes.
* Rewrite all the gtest code that has to do with death tests to use the `W` windows entry points, not the `A` entry points.
The latter is quite a bit of work.  Not today.
=> A hack to restore the tests that were lost when adding UTF-8 support to gtest

integrators/symmetric_linear_multistep_integrator_body.hpp
This saves about 8%:
Before:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 47698734889 ns 47517904600 ns          1 +9.92179030813603147e-01 ua
```
After:
```
---------------------------------------------------------------------------------
Benchmark                                          Time           CPU Iterations
---------------------------------------------------------------------------------
BM_EphemerisSolarSystemMajorBodiesOnly/-3 43992073257 ns 43883081300 ns          1 +9.92179030813603147e-01 ua
```
=> Reserve vector capacity to avoid repeated allocations

astronomy/ksp_system_test.cpp, benchmarks/ephemeris.cpp, ksp_plugin/integrators.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, mathematica/main.cpp, mathematica/retrobop_dynamical_stability.cpp, physics/apsides_test.cpp
This PR does a number of changes to address the instabilities in the orbits of Pol and Bop:
* It adds a benchmark for integrating the KSP system as we were only looking at the performance for the real solar system.
* It changes the default integrator from a Quinlan-Tremaine to a Blanes-Moan.  The integration step is chosen to yield similar performance.  The accuracy is degraded a bit (from 20 to 100 m) but the stability is greatly improved and the spurious oscillations caused by Quinlan-Tremaine are gone.
* It fixes a buglet in the local error analysis.
* It changes the retrobop stability analysis to use the Blanes-Moan integrator.
Fix #1741.
=> Change the default integrator

ksp_plugin/pile_up.cpp
It's not a bug in the compiler unless it's a bug in the compiler.
=> Capture by reference to fix an addressing fault

ksp_plugin_test/interface_test.cpp
See the attempts at running tests for #1761.
=> Initialize an out parameter that was causing serialization to die

ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/utf8_marshaler.cs
This means we copy the UTF-8 string, but at least it works.
=> Revert to string encoding without unsafe

ksp_plugin_adapter/flight_planner.cs
These frames differ significantly when hyperbolic orbits and changes of sphere of influence are involved, as the game will move the node to an orbit around another body as the time moves past the time of the node.
This fixes #1728.
=> Use the the frenet frame of the orbit of the patch, not that of the orbit of the vessel

integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, testing_utilities/is_near.hpp, testing_utilities/is_near_body.hpp, testing_utilities/is_near_test.cpp
Improve `IsNear` so that it is usable for integer arguments, and accurately reports the error.
=> Use IsNear where appropriate in SymplecticRungeKuttaNyströmIntegratorTest

geometry/grassmann_test.cpp, numerics/polynomial.hpp, numerics/polynomial_evaluators_body.hpp, numerics/чебышёв_series.hpp, quantities/constants.hpp, quantities/named_quantities.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp, testing_utilities/statistics_test.cpp
Now that some bugs have been fixed we can:
* Move `NthDerivative` to `named_quantities` and use it to define `Derivative`.
* Make `Inverse` more like `Sqrt`, `Square`, etc.
=> Improvements to named_quantities

ksp_plugin_adapter/compatibility_extensions.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
This fixes #1791.
1.4.1 is still supported by the when targeting 1.4.2, under the assumption that they are ABI compatible.
=> Compile against 1.4.2, deprecate 1.2.2.

numerics/cbrt.cpp, numerics/cbrt.hpp, numerics/cbrt_test.cpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters
This is part of the effort on #1760.
=> A cube root.

ksp_plugin/plugin.cpp, ksp_plugin_test/benchmark.cpp
Before:
```
-------------------------------------------------------------------------
Benchmark                                  Time           CPU Iterations
-------------------------------------------------------------------------
BM_PluginSerializationBenchmark   3366190962 ns 2683217200 ns          1   14.3157MB/s
```
After:
```
-----------------------------------------------------------------------
Benchmark                                Time           CPU Iterations
-----------------------------------------------------------------------
BM_PluginSerializationBenchmark 2367293571 ns 1638010500 ns          1   23.4505MB/s
```
=>  A benchmark for plugin serialization and an optimization

ksp_plugin/interface.cpp
It is not clear whether this is much faster, but it should cost half the memory, and it makes no sense to have a maximum block size smaller than the chunk size when we are trying to optimize saves that have more than a thousand chunks.
=> Tweak the arena.

ksp_plugin/interface_planetarium.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
This is a follow-up of the work done in [Chasles](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#chasles) on #1413,
see #1583, #1584, #1585, #1586, #1588, #1589, #1590, #1596, and #1601.
Specifically, this reverts #1589 now that Principia supports only versions of KSP supported by versions of FAR that add forces to the parts, rather than the rigid bodies.
This fixes #848.
In order for histories to be visible in the atmosphere, the radius multiplier is set to 1; this will result in histories behind a mountain being drawn in front.
=> Reunification of the egg and ferram4 sector

benchmarks/fast_sin_cos_2π_benchmark.cpp, numerics/fast_sin_cos_2π.cpp, numerics/fast_sin_cos_2π_test.cpp
```
08/07/18 23:31:10
------------------------------------------------------------------------
Benchmark                                 Time           CPU Iterations
------------------------------------------------------------------------
BM_FastSinCos2?Latency                18233 ns      18203 ns     153407
BM_FastSinCos2?Latency                18381 ns      18304 ns     153407
BM_FastSinCos2?Latency                18316 ns      18101 ns     153407
BM_FastSinCos2?Latency                18147 ns      18101 ns     153407
BM_FastSinCos2?Latency                18110 ns      18101 ns     153407
BM_FastSinCos2?Latency                18118 ns      18203 ns     153407
BM_FastSinCos2?Latency                18125 ns      18101 ns     153407
BM_FastSinCos2?Latency …
```
=> Trigonometric functions with better invariants

benchmarks/fast_sin_cos_2π_benchmark.cpp
Compute (cos bitand 2 ** 52 - 1) bitxor sin to induce a data dependency without reading from precomputed random inputs or doing a couple of floating-point additions.
Add a benchmark with constant-quadrant inputs, to see the cost of misprediction on random inputs.
The quadrant is unbiased; below is the histogram of 10000 iterates (mod 1, offset 1/2) for various values of 52.
Before:
```
Run on (4 X 2808 MHz CPU s)
08/08/18 23:41:59
------------------------------------------------------------------------
Benchmark                                 Time           CPU Iterations
------------------------------------------------------------------------
BM_FastSinCos2?Latency                21272 ns      21197 ns     137846
BM_FastSinCos2?Latency                21226 ns      21197 ns     137846 …
```
=> Improve the latency benchmark

numerics/fast_sin_cos_2π.cpp
This gains between 9 and 11 cycles, from about 55 to about 45 on Skylake and from about 59 to about 48 on Sandy Bridge.
Skylake:
```
Run on (4 X 2808 MHz CPU s)
2018-08-10T00:26:19
------------------------------------------------------------------------------------
Benchmark                                             Time           CPU Iterations
------------------------------------------------------------------------------------
BM_FastSinCos2?PoorlyPredictedLatency             16259 ns      16232 ns     172308
BM_FastSinCos2?PoorlyPredictedLatency             16273 ns      16323 ns     172308
BM_FastSinCos2?PoorlyPredictedLatency             16284 ns      16141 ns     172308
BM_FastSinCos2?PoorlyPredictedLatency             16275 ns      16323 ns     172308 …
```
=> For a few cycles more

astronomy/sol_gravity_model.proto.txt, benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/geopotential.cpp, physics/geopotential_test.cpp, physics/oblate_body_body.hpp, serialization/physics.proto
Results:
```
09/25/18 22:12:17
-----------------------------------------------------------------
Benchmark                          Time           CPU Iterations
-----------------------------------------------------------------
BM_ComputeGeopotentialCpp/2      319585 ns     319412 ns       8547
BM_ComputeGeopotentialCpp/3      519991 ns     519143 ns       5439
BM_ComputeGeopotentialCpp/5     1505456 ns    1509956 ns       1870
BM_ComputeGeopotentialCpp/10    8731285 ns    8716246 ns        315
BM_ComputeGeopotentialF90/2       71764 ns      71574 ns      39886
BM_ComputeGeopotentialF90/3      113550 ns     113163 ns      25641
BM_ComputeGeopotentialF90/5      198594 ns     198857 ns      13807
BM_ComputeGeopotentialF90/10     678941 ns     680215 ns       4174 …
```
=> A benchmark for the geopotential

physics/geopotential.hpp, physics/geopotential_body.hpp
```
09/29/18 13:50:36
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
--------------------------------------------------------------------
BM_ComputeGeopotentialCpp/2      237411 ns     236407 ns      11218
BM_ComputeGeopotentialCpp/3      308071 ns     307691 ns       8974
BM_ComputeGeopotentialCpp/5      541798 ns     541501 ns       5128
BM_ComputeGeopotentialCpp/10    3134201 ns    3147846 ns        897
BM_ComputeGeopotentialF90/2       73050 ns      73121 ns      38189
BM_ComputeGeopotentialF90/3      110732 ns     110460 ns      25280
BM_ComputeGeopotentialF90/5      200146 ns     199987 ns      13807
BM_ComputeGeopotentialF90/10     672758 ns     669003 ns       4174 …
```
=> Optimize the computation of the polynomials

benchmarks/geopotential.cpp, physics/geopotential.hpp, physics/geopotential_body.hpp, physics/geopotential_test.cpp
Benchmark (note that the Fortran code has become slower due to the benchmark being now fair):
```
09/30/18 16:32:13
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
--------------------------------------------------------------------
BM_ComputeGeopotentialCpp/2      193212 ns     193208 ns      13807
BM_ComputeGeopotentialCpp/3      249143 ns     248923 ns      11218
BM_ComputeGeopotentialCpp/5      380883 ns     380278 ns       7179
BM_ComputeGeopotentialCpp/10    1065107 ns    1061599 ns       2601
BM_ComputeGeopotentialF90/2      186733 ns     186696 ns      14957
BM_ComputeGeopotentialF90/3      237447 ns     235970 ns      11966
BM_ComputeGeopotentialF90/5      320568 …
```
=> Micro-optimizations of the geopotential computations

astronomy/time_scales.hpp, astronomy/time_scales_body.hpp, astronomy/time_scales_test.cpp, geometry/point.hpp, geometry/point_body.hpp
Earth Rotation Angle.
Note that this only incorporates the UT1 values reported by the IERS, and not the subdaily variations due to tides or libration; these have amplitudes bounded by 20 μs in UT1, resulting in sub-milliarcsecond changes in the ERA.
=> Transformation between the TIRS and the CIRS

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/thread_pool.cpp
To try to figure what's happening in #1955.  On Windows and Linux the results are what we expect, on macOS not so much.
On Windows:
```
10/14/18 17:50:12
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
--------------------------------------------------------------------
BM_ThreadPoolNoLock/1         622826191 ns   10920070 ns         10
BM_ThreadPoolNoLock/2         315923306 ns   14040090 ns         10
BM_ThreadPoolNoLock/3         209626186 ns    5546702 ns         90
BM_ThreadPoolNoLock/4         160130553 ns    5153604 ns        112
BM_ThreadPoolNoLock/5         158063773 ns     624004 ns        100
BM_ThreadPoolNoLock/6         158421306 ns     312002 ns        100 …
```
=> A benchmark for ThreadPool

Makefile, base/bundle.hpp, base/macros.hpp, base/pull_serializer.hpp, base/push_deserializer.hpp, base/thread_pool.hpp, base/thread_pool_body.hpp, google_abseil-cpp.props, install_deps.sh, ksp_physics/ksp_physics_lib.cpp, ksp_plugin/interface.cpp, principia.props, rebuild_all_solutions.ps1
The benchmarks below are to be compared with those in #1962.  TL;DR: the performance is unchanged on Windows and Linux; on macOS however the numbers are quite different (1) for shared locks, the performance doesn't degrade with the number of threads in the pool, i.e, there is no contention (2) for exclusive locks the performance is not degraded when there are only few threads in the pool, presumably because there is no attempt to be fair.
On Windows:
```
CPU Caches:
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
-------------------------------------------------------------------- …
```
=> Use absl::Mutex in the ThreadPool

benchmarks/ephemeris.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp, testing_utilities/solar_system_factory.hpp, testing_utilities/solar_system_factory_body.hpp, testing_utilities/solar_system_factory_test.cpp
TL;DR: The new code is 2x slower for low-Earth orbit, comparable in the other cases.
Benchmarks with `PRINCIPIA_USE_EXTENDED_GEOPOTENTIAL` set to 0:
```
CPU Caches:
------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                                     Time         CPU Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_EphemerisMultithreadingBenchmark/3/1 …
```
=> A benchmark for damping oblateness

benchmarks/geopotential.cpp
Before:
```
CPU Caches:
BM_ComputeGeopotentialCpp/2                209881 ns     203362 ns       3452
BM_ComputeGeopotentialCpp/3                247661 ns     244795 ns       2804
BM_ComputeGeopotentialCpp/5                389660 ns     391089 ns       1795
BM_ComputeGeopotentialCpp/10              1229934 ns    1223537 ns        561
BM_ComputeGeopotentialF90/2                187493 ns     187752 ns       3739
BM_ComputeGeopotentialF90/3                233889 ns     229490 …
```
=> Benchmark the effect of #1987

physics/geopotential.hpp, physics/geopotential_body.hpp
Also move some parameters out of Precomputations.
Before:
```
CPU Caches:
BM_ComputeGeopotentialCpp/2                185057 ns     183580 ns       3739
BM_ComputeGeopotentialCpp/3                262468 ns     267049 ns       2804
BM_ComputeGeopotentialCpp/5                361499 ns     359818 ns       1951
BM_ComputeGeopotentialCpp/10              1113582 ns    1112307 ns        561
BM_ComputeGeopotentialF90/2                189437 ns     189804 …
```
=> Remove the size parameter from Precomputations

ksp_plugin_adapter/config_node_parsers.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
This is in preparation for geopotential KSP configs, which will make the parsing code more tricky.  Also, less code in the adapter is a Good Thing™.
No semantically significant changes here (I hope).
=> Move (some of) the code that parses config nodes to a separate class

ksp_plugin_adapter/loader.cs
This comes from https://stackoverflow.com/questions/12206314/detect-if-visual-c-redistributable-for-visual-studio-2012-is-installed, but it doesn't use the GUID because that one is empty on my machine...
=> New C++ redistributable runtime for 15.9

astronomy/trappist_dynamics_test.cpp, astronomy/trappist_gravity_model.proto.txt, benchmarks/dynamic_frame.cpp, physics/apsides_test.cpp, physics/ephemeris_test.cpp, quantities/astronomy.hpp, quantities/elementary_functions_test.cpp, quantities/parser_body.hpp, quantities/quantities_test.cpp
While #1846 introduced a reference to the IAU resolution, it kept the existing constants.
These are ancient, introduced by https://github.com/mockingbirdnest/Principia/commit/3084f819b5bd3a88c2ddbbf0fb37ccddd846b620 in March 2014, predating the relevant IAU resolution by more than a year; being masses, they are fundamentally unsuitable as nominal values, as gravitational parameters are known with much greater accuracy than 𝐺 is.
Switch to the system of nominal solar and planetary conversion constants.
=> Actually implement IAU 29 resolution B3

astronomy/geodesy_test.cpp, astronomy/ksp_resonance_test.cpp, astronomy/ksp_system_test.cpp, astronomy/lunar_eclipse_test.cpp, astronomy/mercury_perihelion_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/trappist_dynamics_test.cpp, astronomy/молния_orbit_test.cpp, benchmarks/dynamic_frame.cpp, benchmarks/ephemeris.cpp, benchmarks/planetarium_plot_methods.cpp, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/pile_up_test.cpp, mathematica/local_error_analysis.cpp, mathematica/retrobop_dynamical_stability.cpp, physics/apsides_test.cpp, physics/barycentric_rotating_dynamic_frame_test.cpp, physics/body_centred_body_direction_dynamic_frame_test.cpp, physics/body_centred_non_rotating_dynamic_frame_test.cpp, physics/body_surface_dynamic_frame_test.cpp, physics/body_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp, physics/solar_system_test.cpp
Use `0x1p-24` in most places; this should make the tests (and benchmarks, etc.) a bit faster, and most importantly prevent them from becoming massively slower with #2032.
=> Remove the implicit constructor for AccuracyParameters

stacktrace_decoder/App.config, stacktrace_decoder/dbghelp.cs, stacktrace_decoder/stacktrace_decoder.cs, stacktrace_decoder/stacktrace_decoder.csproj
The stacktrace provided in #2056 notably differs from the one we recover from the logs in that it includes inline frames.
In order to get those, we need to directly use dbghelp instead of going through dbh. This also solves a lot of clunkiness surrounding base addresses, as well as the issue that dbh did not appear to work with non-ASCII paths (what year is this).
Further, GitHub now [automatically renders code snippets](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/), so use that by default instead of ``[`file:line`](link)`` markdown.
In order to have more context in the snippet, make the snippet range from the start of the symbol to the line corresponding to the stack frame. Make the trace most-recent-call-last so that the sequence of snippets reads …
=> Better stacktrace decoding

integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp
This may help with #2056 but I don't have an easy way to test.  There will be a message in the WARNING log to see if we are properly handling the condition.
=> Propagate errors found during integration to kill the vessel

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #1868, hopefully.
From traces, it seems that if https://github.com/mockingbirdnest/Principia/blob/f46184556565f10020d41125fd650a7066595798/ksp_plugin_adapter/ksp_plugin_adapter.cs#L657-L660 was called while the SAS was on (which happened, e.g., if the SAS was turned on before launch), it *would* change the invocation list as expected, i.e.,
```C#
active_vessel.OnAutopilotUpdate.GetInvocationList()[0] ==
(Delegate)(FlightInputCallback)OverrideRSASTarget
```
would then hold, but invoking `active_vessel.OnAutopilotUpdate` would somehow not call `OverrideRSASTarget`, thus keeping the stock SAS behaviour (and resulting in #1868).
I have no explanation for this behaviour.
The invocation did have the expected effect, however, if the delegate combination occurred with the SAS *off*, e.g., if …
=> Try to make the SAS more reliable

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
* Windows are now constructed with just their supervisor and later initialized with the plugin.  This makes it possible to reuse the same window when the plugin gets recreated (e.g., reloaded from a save).
* Windows are no longer using the "disposable" pattern and are no longer wrapped in a `Controlled` object.  Instead, they use the `clear_locks` and `dispose_windows` events to release the locks and unregister themselves at the right place.
* A bug is fixed whereby locks were not cleared when the main window was hidden.
* A bit of code reordering to bring related things closer together.
=> Get rid of the "disposable" pattern for windows

ksp_plugin_adapter/dialog.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
* Move the hide/show bit to `WindowRenderer` and save/load it.
* Add `Hide`, `Show`, `Shown` and `Toggle` to manage that bit.
* Make `RenderWindow` nonabstract to factor out logic that's common to all the windows (e.g., clearing the lock when hiding).
* Subclasses are now expected to override `Title` and a new `RenderWindow(int)` method.
* Pass GUI options at construction if needed with a reasonable default.
* Drudgery to centre a window the first time it is shown.
=> Make the hide/show status of windows persistent

ksp_plugin/interface.cpp, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs
This ensures that we don't change state between Layout and Repaint, and it eliminates a funky null pointer exception when first creating a flight plan.
=> Restructure the rendering of the flight plan

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs
Since `MapNode`s are costly to `Create` (proportionally to the number of existing `MapNode`s),
- reuse `MapNode`s as much as possible:
- make unused nodes invisible instead of terminating them,
- do not clear the `MapNodePool` when there is no trajectory to render;
- limit the number of map nodes of one kind to 64.
Further, fix the execution order issue that caused the nodes to lag behind the trajectories when moving the camera.
=> Map node pool improvements

ksp_plugin_adapter/window_renderer.cs
Not that we needed it anyway; `Rect` is a `struct`.
=> No UnityEngine.Rect.zero in KSP 1.3.1

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs
Without the check for `component.name`, we end up destroying the `textCaption` member of the `MapNode` (the hovertext), which is not what we want, and causes a `MapView` callback to systematically throw, preventing all nodes from ever being updated again.
=> I didn’t shoot the text caption

astronomy/trappist_dynamics_test.cpp, base/bundle_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/vessel_test.cpp
The lint check has been disabled, fixing #2093; remove the `NOLINT`s.
=> Remove NOLINT(build/namespaces)

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs
See the discussion in #2121: for far future manœuvres separated by a short time interval, this avoids the awkwardness of having two nearly equal long countdowns; further, since the displayed value becomes stable, this paves the way for editing it.
Note that a countdown is still shown for the first upcoming manœuvre.
=> Refer manœuvre times to a time base, not to the current time

ksp_plugin_adapter/burn_editor.cs
Reverts mockingbirdnest/Principia#2143
The function `MaxThrustOutputVac` doesn't seem to exist prior to 1.5.1.
=> Revert "Take the thrust limiter into account"

base/bundle_test.cpp, base/push_deserializer_test.cpp, base/thread_pool_test.cpp, numerics/fast_sin_cos_2π_test.cpp
I noticed that some of the *debug* tests had become quite slow.  There is really no reason for `base` to be more costly than the selenopotential.  I am fixing the glitch.
=> Speed up debug tests

ksp_plugin_adapter/map_node_pool.cs
Fix #2156; also fix an issue where nodes would have text written in the wrong colour; screenshot showcasing both (some `Ap` are written in blue, other markers have no text):
=> A node has no name

journal/player_test.cpp, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/reference_frame_selector.cs
We had a curious game of ping-pong: Frame 1, the burn editor notices that the reference frame has recently changed, so it returns that information to the flight plan; the flight plan reloads all the data from the C++ side, including the reference frame.  Frame 2, the burn editor notices that the reference frame has recently changed, etc.
The fix is to change the burn editor so that it only reports a change if the frame loaded from C++ is actually different from the one it was using.
Fix #2157.
=> Properly detect changes to the navigation frame

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs
1. Nail the initial time and use the slider to (effectively) edit `initial_time_ - time_base`.
1. Shrink the flight plan when the number of manoeuvres changes.
Fix #2154.
=> Properly deal with a changing time base in the burn editor

astronomy/geodesy_test.cpp, ksp_plugin_test/manœuvre_test.cpp, physics/body_centred_non_rotating_dynamic_frame.hpp, physics/body_centred_non_rotating_dynamic_frame_body.hpp, physics/body_centred_non_rotating_dynamic_frame_test.cpp, physics/body_surface_dynamic_frame.hpp, physics/ephemeris_test.cpp, physics/geopotential_body.hpp, physics/geopotential_test.cpp, physics/rotating_body.hpp, physics/rotating_body_body.hpp
This will make it possible to address #1841; additional logic would be needed for to properly address the irrelevance of the solar equator, other than that this is a simple matter of changing the following condition in the adapter.
https://github.com/mockingbirdnest/Principia/blob/80be4b3fdf0c0fe0b6f9e038815171ffc1ba82f7/ksp_plugin_adapter/ksp_plugin_adapter.cs#L1922-L1925
Note: this breaks tests (some values that were very small have become 0 because of the changes in (bi)equatorial), and it probably needs some new tests to check the orientation.
=> A better reference plane for the the ECI etc. frames.

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin_test/flight_plan_test.cpp
Shows up on (at least) `Append` and `RemoveLast` when there is a preceding anomalous segment.
=> Make sure that the FlightPlan operations return an error for an anomalous flight plan

ksp_plugin/interface.cpp, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/logging.cs, ksp_plugin_adapter/source_location.cs, ksp_plugin_test/interface_test.cpp, serialization/journal.proto
Before:
```
I0526 00:31:31.086426 30232 interface.cpp:851] Serialization has 160 chunks
```
After:
```
I0526 19:34:14.980886 24080 ksp_plugin_adapter.cs:585] Serialization has 152 chunks
```
=> Source location

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_test/flight_plan_test.cpp, ksp_plugin_test/interface_flight_plan_test.cpp, ksp_plugin_test/mock_flight_plan.hpp, serialization/journal.proto
* Remove `ReplaceLast` everywhere and use `Replace` instead.
* Remove the `enabled` boolean from the UI: all burn editors are always enabled.
* Change the flight planner to handle all burn editors identically.
Fix #1936.
=> Support edition of all manœuvres in a flight plan

ksp_plugin_adapter/ksp_plugin_adapter.cs
Without `principia_override_version_check {}`
```
Log file created at: 2019/06/29 12:54:22
Running on machine: BELLINI
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0629 12:54:22.463878 32608 interface.cpp:628] Initialized Google logging for Principia
I0629 12:54:22.464879 32608 interface.cpp:629] Principia version 2019060310-Fatou-27-g9c250e0d609be7ecdea3fd7de47088062ba20e13-dirty built on 2019-06-02T23:08:18Z by Microsoft Visual C++ version 192227724 for Windows x86-64
I0629 12:54:22.464879 32608 interface.cpp:642] Base address is 000007FEC49E0000
I0629 12:54:22.464879 32608 ksp_physics_lib.cpp:18] Principia KSP physics DLL version 2019060310-Fatou-27-g9c250e0d609be7ecdea3fd7de47088062ba20e13-dirty built on 2019-06-02T23:08:18Z by Microsoft Visual C++ version …
```
=> A mechanism to override version checking

astronomy/lunar_orbit_test.cpp, physics/kepler_orbit_body.hpp
They are counted in the direction of the orbit, not in the direction of longitude.
=> Fix the signs of ω and ν for retrograde orbits

ksp_plugin_adapter/main_window.cs
Also fix the "upgrade to 1.6.1" check.
Fix #2249.
=> Allow multiple lines for the "new release" message.

benchmarks/apsides.cpp, benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, ksp_physics/ksp_physics_lib.hpp
The first step in addressing #2261.
```
CPU Caches:
ApsidesBenchmark/ComputeApsides         198228715 ns  197061641 ns        212
ApsidesBenchmark/ComputeApsides         198536061 ns  197944665 ns        212
ApsidesBenchmark/ComputeApsides         198661021 ns  197797494 ns        212
ApsidesBenchmark/ComputeApsides_mean    198475266 ns  197601267 ns          3
ApsidesBenchmark/ComputeApsides_median  198536061 ns  197797494 ns          3 …
```
=> A benchmark for ComputeApsides and ComputeNodes

physics/forkable_body.hpp
This speeds up the apsides/nodes computations by 8-16%, and will benefit all the code that iterates over discrete trajectories.  Contributes to solving #2261.
Before:
```
CPU Caches:
ApsidesBenchmark/ComputeApsides         198228715 ns  197061641 ns        212
ApsidesBenchmark/ComputeApsides         198536061 ns  197944665 ns        212
ApsidesBenchmark/ComputeApsides         198661021 ns  197797494 ns        212 …
```
=>  Some micro-optimizations of the trajectory iterators

astronomy/trappist_dynamics_test.cpp, physics/solar_system.hpp, physics/solar_system_body.hpp
Copying a `SolarSystem` would discard the effect of `RemoveMassiveBody` and the like.
=> Move-only is better than incorrectly-copied

physics/forkable_body.hpp
The performance gain wrt to the original implementation is reduced to 6-13%:
```
CPU Caches:
ApsidesBenchmark/ComputeApsides         186739818 ns  185620573 ns        227
ApsidesBenchmark/ComputeApsides         186097324 ns  185070790 ns        227
ApsidesBenchmark/ComputeApsides         186573579 ns  185551850 ns        227
ApsidesBenchmark/ComputeApsides_mean    186470240 ns  185414404 ns          3
ApsidesBenchmark/ComputeApsides_median …
```
=> Avoid a unbounded behavior introduced in #2279

documentation/Setup.md, ksp_plugin_adapter/dialog.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/loader.cs
* We lost the "bad installation" dialog because its state was incorrectly restored from the save.
* The VC++ redistributable version should mention the unified 2015-2019 runtime.
This was prompted by #2297.
=> Improve error reporting for bad installations

astronomy/trappist_dynamics_test.cpp, build_for_benchmarking.ps1, parallel_test_runner/parallel_test_runner.cs, rebuild_release.ps1
- Add support for filtering and running disabled tests in the parallel test runner;
- make the "build for benchmarking" script build the whole solution;
- mark the TRAPPIST-1 optimization secular, in the sense that it must not be run periodically.
=> Diurnal testing

Makefile, Vagrantfile
Some tolerances have changed but they are not fixed in this PR:
```
[ RUN      ] ApsidesTest.ComputeApsidesDiscreteTrajectory
physics/apsides_test.cpp:122: Failure
Value of: time - *previous_time
Expected: is within 118 to 2792 ULPs of +1.05340260072161824e+08 s
Actual: +1.05340260072119743e+08 s, the numbers are separated by 2824 ULPs
physics/apsides_test.cpp:146: Failure
Value of: time - *previous_time
Expected: is within 103 to 4936 ULPs of +5.26701300360809118e+07 s
Actual: +5.26701300360429287e+07 s, the numbers are separated by 5098 ULPs
[  FAILED  ] ApsidesTest.ComputeApsidesDiscreteTrajectory (263 ms)
[ RUN      ] OrbitalElementsTest.KeplerOrbit
astronomy/orbital_elements_test.cpp:181: Failure
Value of: elements.nodal_period()
Expected: has an absolute error from …
```
=> Add support for Disco Dingo and Clang 8

astronomy/ksp_system_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/trappist_dynamics_test.cpp, base/disjoint_sets.hpp, journal/profiles.cpp, ksp_plugin/interface.cpp, ksp_plugin/part_subsets.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_test.cpp, physics/apsides_test.cpp, physics/continuous_trajectory_body.hpp, physics/discrete_trajectory_body.hpp, physics/ephemeris_body.hpp, physics/forkable_body.hpp, physics/oblate_body_body.hpp, physics/solar_system_body.hpp
This changes most instances of
```C++
for (auto const& pair : ⟨map⟩)
```
to
```C++
for (auto const& [key, value] : ⟨map⟩)
```
The exceptions are
https://github.com/mockingbirdnest/Principia/blob/a8cfa72ed7356caee03945da2f68e9c253bcefa2/physics/solar_system_body.hpp#L636-L638
where the name `degrees_of_freedom` is taken,
and the public functions of the journal proto processor:
https://github.com/mockingbirdnest/Principia/blob/a8cfa72ed7356caee03945da2f68e9c253bcefa2/tools/journal_proto_processor.cpp#L112-L188
In both cases, switching to structured bindings felt clumsier than the existing code. It is noteworthy that both are examples of the same pattern, turning the values of a map into a vector; perhaps we could write an utility function for that.
Where the key is unused, this pull request …
=> Use structured bindings

ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin/principia.manifest, ksp_plugin_adapter/loader.cs, serialization/serialization.manifest, serialization/serialization.vcxproj, serialization/serialization.vcxproj.filters
=> Use manifests instead of DLL paths to find our DLLs

physics/euler_solver.hpp, physics/euler_solver_body.hpp, physics/euler_solver_test.cpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
1. This is the pattern used by the other classes in physics, e.g. the dynamic frames.
1. We might want to have different principal axes frames for different vessels, for instance.
1. The current pattern would look weird once we take the inertial frame as a template parameter for solving the Arnold equation.
=> Change EulerSolver to take the principal axes frame as a template parameter

astronomy/orbit_analysis_test.cpp, astronomy/orbit_ground_track.hpp, astronomy/orbit_ground_track_body.hpp
The slow part of OrbitGroundTrack is the computation of the nodes; analysing how well pre-computed nodes follow a particular nominal recurrence grid is fast enough that it can be done in the UI thread, and this makes the analyser more convenient to use.
=> Separate the nominal recurrence from OrbitGroundTrack

astronomy/lunar_eclipse_test.cpp
We have an equatorial radius now.
There is a problem with the IMCCE link: the relevant page moved to https://promenade.imcce.fr/fr/pages3/333.html, but the relevant section *Correction de la parallaxe lunaire dans les calculs d'éclipse de Lune* was removed in the process. Should we link to http://web.archive.org/web/20170915031958/http://www.imcce.fr:80/langues/fr/ephemerides/phenomenes/eclipses/lune/?
=> Minor cleanups to the lunar eclipse test

physics/euler_solver_body.hpp
1. Avoid using absolute values everywhere.
1. Avoid using divisions when multiplications would work.
=> Change the code to conform to the documentation in Celledoni.pdf

testing_utilities/componentwise_test.cpp, testing_utilities/numerics_matchers.hpp, testing_utilities/numerics_matchers_body.hpp
Otherwise they don't work with Componentwise.
=> Change the numerics matchers to avoid references

benchmarks/elliptic_integrals_benchmark.cpp, numerics/elliptic_integrals.cpp, numerics/elliptic_integrals.hpp
This makes it possible to compute F and E without computing J when Π is not needed.
Before:
```
Run on (4 X 2808 MHz CPU s)
CPU Caches:
L1 Data 32K (x2)
L1 Instruction 32K (x2)
L2 Unified 262K (x2)
L3 Unified 4194K (x1)
------------------------------------------------------
Benchmark               Time           CPU Iterations
------------------------------------------------------
BM_EllipticF          233 ns        228 ns    2951600
BM_EllipticFEΠ        235 ns        230 ns    2992000
```
After:
```
Run on (4 X 2808 MHz CPU s)
CPU Caches:
L1 Data 32K (x2)
L1 Instruction 32K (x2)
L2 Unified 262K (x2)
L3 Unified 4194K (x1)
------------------------------------------------------
Benchmark               Time           CPU Iterations
------------------------------------------------------ …
```
=> Templatize on the need for the integral of the third kind

ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
This pull request makes the `Max history length` setting hide history, instead of forgetting it. It does not introduce a separate setting to forget the history; we may want to add that if people complain about performance issues.
Fix #942.
Fix #2164.
All hail retrobop:
Epicycles:
Short histories:
Miscellaneous screenshots:
=> Celestial trajectory plotting

physics/euler_solver.hpp, physics/euler_solver_body.hpp, physics/euler_solver_test.cpp
The documentation is certainly going to take a long time to review, but with some chance the code changes could go in quickly.  This would make it possible to keep working on the solver without having to go through a messy merge.
=> Separate out the code changes from #2375

ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_adapter/orbit_analyser.cs
```C#
$"{...}".ToString(Culture.culture)
```
actually calls `string.ToString`, which has no effect; we would have to go through `FormattableString`, which is Framework 4.6 and therefore the distant future (the year 2015).
This results in formatting with the invariant culture in places, violating Resolution 7 of the 9th CGPM (1948) and its reaffirmation in Resolution 10 of the 22nd CGPM (2003).
> *Pour faciliter la lecture, les nombres peuvent être partagés en tranches de trois chiffres ; ces tranches ne sont jamais séparées par des points, ni par des virgules.*
> Numbers may be divided in groups of three in order to facilitate reading; neither dots nor commas are ever inserted in the spaces between groups.
We always want to format in our custom `Culture.culture`, and very often in an `N` …
=> Grouping mark

geometry/orthogonal_map.hpp, geometry/quaternion.hpp, geometry/quaternion_body.hpp, ksp_plugin/interface_body.hpp, physics/rigid_motion_test.cpp
... otherwise we accumulate errors when converting to the Barycentric frame.
Fix #2389.
=> Normalize the quaternions that we get from Unity

ksp_plugin/renderer.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
This is probably because the hemisphere on which clouds are drawn is chosen in the shader based on the position of the planet, which is computed with respect to the galaxy camera, rather than the scaled camera:
https://github.com/rbray89/EnvironmentalVisualEnhancements/blob/0c6fdac386c0fe6da20ddabea25f4fe60ca25b1b/Atmosphere/CloudsPQS.cs#L218-L224.
Normally, both cameras are at the origin, because `ScaledSpace` shifts positions accordingly, so this does not matter; since we adjusted the cameras after `ScaledSpace` ran, we moved the scaled space camera (but not the galaxy camera) away from the origin.
This may arguably be a bug in EVE (that position should be computed using the scaled space camera, since this is the one that renders), but it is probably a bad idea to violate the KSP …
=> Fix miscellaneous bugs with camera rotation

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/planetarium_camera_adjuster.cs
Fix #2401.
The `LateUpdate` of the new file is essentially the old `OrientPlanetariumCamera`. Some of the remainder of the diff is removing workarounds for timing-induced issues; it may be more to compare the adapter with its state prior to #2393: https://github.com/mockingbirdnest/Principia/compare/14ee57622a1064f4518f6f6e1c8c4e3f89cb3fcc...eggrobin:camera-rotation?expand=1#diff-c8666bccb01bd25d11f7ae5e0b5f2d1f.
=> Use a custom timing to adjust the planetarium camera.

ksp_plugin/interface_planetarium.cpp
Show celestial histories before the beginning of the history of the active vessel.
Prior to this change, seeing long celestial trajectories was easiest to achieve in the tracking station, with no vessel selected.
However, to quote @lpgagnon, the primary reason to look at long celestial trajectories is
> because they're pretty
whereas
> the tracking station is not pretty
> (and, annoyingly, doesn't support F2 to hide the UI)
Long celestial histories can now be seen in map view, along with the shorter history of a vessel. Note that predictions still end where the vessel's does (in the screenshots below, the prediction ends as the vessel collides with Earth, so that the predicted trajectories of Earth and the vessel end at the same point).
=> Ancient history

ksp_plugin_adapter/planetarium_camera_adjuster.cs
This fixes the known issue in Fréchet whereby the camera would spin wildly when the game was paused in map view.
It also fixes a more subtle issue (which was partially hidden by the previous one) whereby changing the plotting frame when the game was paused would fail to preserve the orientation of the camera.
=> Do not adjust the camera when paused

ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, serialization/ksp_plugin.proto
Addresses #2443, but will need to be tested in game.
=> Keep the prediction parameters of the vessels that have disappeared

ksp_plugin_adapter/config_node_parsers.cs
See #2429 and its fix, #2430: if a [`principia_gravity_model.body`](https://github.com/mockingbirdnest/Principia/wiki/Principia-configuration-files#principia_gravity_model.body) node has no [`geopotential_row`](https://github.com/mockingbirdnest/Principia/wiki/Principia-configuration-files#principia_gravity_model.body.geopotential_row), `geopotential` is an empty array rather than a null in the affected code. This meant that we would provide a defaulted `reference_radius` to the C++, which would fail with
```
Check failed: body.has_j2() || body.has_geopotential() == body.has_reference_radius() (0 vs. 1)
```
even though the constraint
> either `reference_radius` is absent, or one of `j2` and `geopotential_row` is present;
was satisfied by the configuration.
=> Do not provide a defaulted reference_radius if no geopotential is present

ksp_plugin/interface_part.cpp, ksp_plugin/part.cpp, ksp_plugin/part.hpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/part_test.cpp, ksp_plugin_test/pile_up_test.cpp, serialization/journal.proto
Keep track of the angular momentum of a pile up.
For the moment, it is neither exposed nor serialized.
=> Angular momentum accounting

base/flags.cpp, base/flags.hpp
The Linux test dumps a core at the very end.  Let's avoid static objects at namespace scope.
=> Avoid exit destructors

base/macros.hpp, quantities/quantities.hpp
Clang 8.0.0 has not heard about the new rule, but Clang 9.0.0 has.
=> Use the CONSTEXPR_INFINITY macro for new constants

ksp_plugin/flight_plan.cpp, ksp_plugin/manœuvre.hpp, ksp_plugin/manœuvre_body.hpp, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_test/flight_plan_test.cpp
Also changed the default flight plan length to 1 hour from 1000 seconds (?).
Fix #852.
=> Extend the flight plan when the last manœuvre is moved forward or extended

geometry/r3x3_matrix_body.hpp, journal/player_test.cpp, ksp_plugin/part.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs
It seems that in some cases (maybe when a part is about to be destroyed) KSP gives us NaNs in the positions, velocities, angular velocities, forces and torques.  This change filters out such parts early in the C# code, as if they had no rigid body.
The alternative of letting `NaN`s enter the C++ code would be a nightmare because they would fail every single `CHECK`.
Will hopefully fix #2530.
=> Do not call C++ with positions, velocities or angular velocities that are NaNs.

ksp_plugin/interface_part.cpp, ksp_plugin/interface_vessel.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs, serialization/journal.proto
This appears to significantly improve the behaviour reported in #2519.
It is not perfect. In the save from https://github.com/mockingbirdnest/Principia/issues/2519#issuecomment-612605437, while we get no uncontrolled spin-up, we get more oscillations than in stock, slowing the rocket down, so that it reaches the water without burning up.
Note that this adds back some traces and toggles for debugging. They will be hidden in a separate pull request (but I would like to keep the plumbing around for now; we may not be quite done with this issue yet).
=> A more stable angular momentum correction.

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/window_renderer.cs
These two seem to make the tracking station much more useful.
The implementation involves a bit of code restructuring where we use `PredictedVessel` systematically in many places that were using `ActiveVessel`.  Overall this factors out a bit of logic and fixes a buglet where the orbit analyser in the tracking station would show a stump of a window.
There is a remaining know issue for a Kerbal in EVA: if a flight plan is constructed in the tracking station, that flight plan is lost when switching to the map view.  That's because the Kerbal becomes unready for a couple of frames.  It doesn't happen in the other direction.  We call this "the invariants of KSP".  The ultimate fix would be to keep some of the state of unmanaged vessels, but that's a long term effort.
Fix #2531.
=> Display the flight planner and the orbit analyser in the tracking station

base/traits.hpp, mathematica/error_analysis_test.cpp, mathematica/local_error_analysis.cpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, mathematica/retrobop_dynamical_stability.cpp
1. All *Mathematica* conversion function now take an `ExpressIn`, for composability, even if they don't use it.
1. `ExpressIn` automatically applies to all types for which `ToMathematica` and related functions apply.
1. All checks are compile-time, so if it compiles it's going to do the right thing.
=> Add a new class, ExpressIn, to help with type erasure of quantities in Mathematica output

ksp_plugin_adapter/loader.cs
Will help users who run into #2548.  Message:
```
The Principia DLL failed to load.
C:\Program Files\Kerbal Space Program\1.9.1- 多体 contains the non-ASCII character 多; this is known to confuse Mono.
Warning: don't load a Principia save before you have fixed this error; it might get damaged.
```
=> Detect non-ASCII paths as they confuse Mono

ksp_plugin_adapter/loader.cs
=> Don't protest on a non-ASCII path if the DLL can be loaded

ksp_plugin/pile_up.cpp, ksp_plugin_adapter/main_window.cs, ksp_plugin_test/pile_up_test.cpp
The thresholding toggle now switches between this behaviour when off and the Fubini behaviour + PID  (as in test2550) when on.
There seems to be an improvement: in the save given in https://github.com/mockingbirdnest/Principia/issues/2519#issuecomment-612605437, the vessel now explodes on reentry as it does in stock (the oscillations no longer slow it down enough for it to make it to the water unharmed).
However:
1. the oscillations on descent are still larger than in stock;
2. the westward drift on ascent is larger than in Fubini (where it was larger than in Frobenius).
Perhaps some PID tuning might help with those issues (especially 1).
=> A smoother correction

ksp_plugin/interface_flight_plan.cpp
On ignition, switch to tracking the current actual Frenet frame (current behaviour).
Fix #2577; all Principia burns can now be executed by MechJeb, and MechJeb warps properly.
=> Point to the planned initial Frenet frame before ignition

base/traits.hpp, quantities/si.hpp
Clang 9 changed the linkage definition for variable templates with const-qualified type
(see https://github.com/llvm/llvm-project/commit/bb750689d51d2109b9898b53a4b69d8183ab1f26).
This leads to the following linker error in "make test" when compiling with clang versions >= 9:
```
clang++ -c -std=c++1z -stdlib=libc++ -O3 -g -fPIC -fexceptions -ferror-limit=1000 -fno-omit-frame-pointer -Wall -Wpedantic -Wno-char-subscripts -Wno-gnu-anonymous-struct -Wno-gnu-zero-variadic-macro-arguments -Wno-nested-anon-types -Wno-unknown-pragmas -DPROJECT_DIR='std::filesystem::path("ksp_plugin_adapter/")' -DSOLUTION_DIR='std::filesystem::path("./")' -DTEMP_DIR='std::filesystem::path("/tmp")' -DNDEBUG -m64 -I. -Ideps/glog/src -Ideps/protobuf/src -Ideps/gipfeli/include -Ideps/abseil-cpp -Ideps/zfp/include …
```
=> Fix linker error when compiling with clang 9+

astronomy/ksp_system_test.cpp, astronomy/solar_system_dynamics_test.cpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, mathematica/integrator_plots.cpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp
1. Change the default of `make_unique`.
1. Change `ToMathematica` for a string to escape its argument.
=> More Mathematica improvements

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
The `Rebase` button discards past (and ongoing) manœuvres, and sets the flight plan initial state to the current state (in terms of mass as well as position and velocity).
---
Drive-by change: drop the guidance node for one frame when it switches manœuvres; this fixes MuMech/MechJeb2#1276 (though @lamont-granquist wants to leave that one open until the UX is cleaned up a little) and the stock equivalent, whereby guiding to the manœuvre through scheduled burnout would lead to a reorientation to the next manœuvre with the engines still firing.
After this change, at the scheduled end of the burn, MechJeb ceases burn execution (shutting down the engines), and the stock SAS switches to holding attitude.
=> Flight plan rebasing

astronomy/orbital_elements.hpp, astronomy/orbital_elements_body.hpp, ksp_plugin/interface_vessel.cpp, ksp_plugin_adapter/orbit_analyser.cs, principia.props, serialization/journal.proto
Add the following to the orbit analysis window:
- a warning if any of the following occur over the course of the mission:
- dropping below the nominal atmosphere height: reentry,
- dropping below the highest terrain altitude: collision risk,
- dropping below the lowest terrain altitude or, on a planet with oceans, sea level, whichever one is higher: collision);
- lowest altitude: the lowest altitude reached over the course of the mission;
- altitude of mean periapsis: the altitude corresponding to the periapsis distance itself corresponding to the mean semimajor axis and mean eccentricity;
- altitude of mean apoapsis: the altitude corresponding to the apoapsis distance itself corresponding to the mean semimajor axis and mean eccentricity;
While the mean periapsis and apoapsis altitudes …
=> Mean apsides and minimal distance

ksp_plugin/interface.cpp
Some users (I'm looking at you, @lpgagnon) have been known to give us the `ERROR` file and it's a bit embarrassing that we cannot do anything with it because we don't have enough information there to decode the stack.
=> Log version and module information to ERROR

ksp_plugin_adapter/collision_reporter.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/main_window.cs
It appears that `currentCollisions` is often wrong (reference counting never works).
This improves matters with respect to the ejection part of #2607: the elimination of spurious collisions means that the Kerbal is no longer considered part of its aircraft, and thus we no longer impart erratic velocity and position corrections after ejection.
The issue of the attitude under parachute remains, as we do not understand how the parachute acts upon the Kerbal’s attitude.
=> Handle collisions ourselves

ksp_plugin/part.cpp, ksp_plugin/part.hpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/part_test.cpp, ksp_plugin_test/pile_up_test.cpp
Missed in #2604, hidden by an old TODO.
This led to transient jumps when coming out of warp in vessels whose root part had a CoM offset, and, in some mysterious RO setups, to persistent deformation of the vessel.
=> Reference part offset

find_msbuild.ps1, make_principia_release.ps1
Use the earliest version after the requested one; if there is none, use the latest version before the requested one.
=> Accept other Visual Studio versions, except when releasing

ksp_plugin_adapter/orbit_analyser.cs
Due to confusion between radii and altitudes, submarine periapsides were seen as a mere collision *risk*.
=> Fix the collision warning for bodies with oceans

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs
Once we add orbit analysis for coasts, the one-line coast descriptions will reflect that analysis (something like `Coast for 2 d 14 h in Earth orbit (5.2 rev.)`) and will be expandable to show:
- the number of sidereal revolutions, with ±1 buttons;
- the number of nodal revolutions, with ±1 buttons;
- the number of anomalistic revolutions, with ±1 buttons;
- in the distant future, the number of parent-body-synodic revolutions, with ±1 buttons;
- a button to open the full orbit analysis (at least for the final trajectory).
All manœuvres minimized:
One expanded:
=> Collapsible manœuvres

numerics/frequency_analysis.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp
This yields nicer units when computing norm (we are not prepared to handle fractional exponents in quantity).
A contribution to #2400.
=> Normalize the dot product of Poisson series

numerics/frequency_analysis.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp
This makes it usable for dot products between any kind of functions in the implementation.  This in turns makes it possible to project a function of any degree on a basis of any degree (the test projects a function of degree 4 to bases of degrees 3, 4, and 5).
Fix a few places where polynomials were not converted to a higher degree.
Yet another contribution to #2400.
=> Change the dot product passed to frequency analysis to be a templated functor

numerics/frequency_analysis_test.cpp
Apparently MSVC and Clang disagree on the constness of distribution.
More #2400.
=> Fix a compilation error found by Clang

numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp
Ignore a basis element if it is sufficiently close to the span of the preceding basis elements (cancellation of at least 24 bits).  Not only does this yield better accuracy, it doesn't cause such huge tolerance changes between casanova and carpaccio (compare a5d483f445fe5e8eaf9efba1b57e28f1adfb973c and 34e915f61fb010aaa9de1004fae59084d008629c)
Contributes to #2400.
=> An attempt at addressing ill-conditioned basis elements.

numerics/frequency_analysis_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/poisson_series_basis.hpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_basis_test.cpp
That code is sufficiently complicated that it should be tested.  This PR smaller/simpler than it looks because it does two things: (1) it moves code around without semantic changes; (2) it adds a test.
#2400.
=> Move Poisson basis construction to a separate file

numerics/poisson_series.hpp, numerics/poisson_series_body.hpp
Speed up #2400: no real benchmark, but representation of 3 months of the trajectory of Io using 5th degree and 10 frequencies goes down from 284 s to 168 s.
=> Poisson series optimization

numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/polynomial.hpp
Use `vector` instead of `map`, avoid copies, do more `reserve`.  Overall this saves about 30% of the CPU.
Optimize #2400.
=> Reduce heap usage in Poisson series

numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/root_finders.hpp
1. Add a private constructor that avoids sorting.
1. Reduce a bit the number of evaluations of trigonometric functions.
1. In the dot product, instead of using formal multiplication and formal integration, use evaluation followed by multiplication and Gauss integration.
1. Add a parameter to the dot product to specify the number of points to use (mostly for tests, the default should work in real life).
#2400.
=> Improve the Poisson series implementation

numerics/fixed_arrays.hpp, numerics/frequency_analysis.hpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/poisson_series_test.cpp, numerics/polynomial.hpp, numerics/quadrature_body.hpp
Also:
1. Rename `Dot` into `InnerProduct` to be consistent with the `Hilbert` trait.
1. Fix the `PiecewisePoissonSeriesProjection` test.
#2400
=> Don't pass dot to the frequency analysis functions

numerics/poisson_series_body.hpp
=> Optimize += and -= for piecewise Poisson series by not falling back to + and -

astronomy/orbit_analysis_test.cpp, benchmarks/polynomial.cpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp, numerics/elliptic_functions.cpp, numerics/elliptic_integrals.cpp, numerics/fast_sin_cos_2π.cpp, numerics/legendre_test.cpp, numerics/newhall_test.cpp, numerics/poisson_series_body.hpp, numerics/polynomial.hpp, numerics/polynomial_body.hpp, numerics/polynomial_test.cpp, numerics/root_finders_test.cpp, physics/continuous_trajectory_body.hpp
1. Rename `Evaluate` into `operator()` to make polynomials *bona fide* functors.
1. Append `_` to the type template parameters to be able to reexport them (#572).
1. Use `typename` instead of `class` for the template template parameters.
Distantly related to #2400.
=> Cleanups for the polynomials

numerics/fast_fourier_transform.hpp, numerics/fast_fourier_transform_body.hpp
#2400: minor cleanup of #2726.
Rename `ω` to `Δω` for symmetry, in preparation for argument types other than `Time`.
=> Remove FFT type decay

numerics/fast_fourier_transform.hpp, numerics/fast_fourier_transform_body.hpp, numerics/fast_fourier_transform_test.cpp, numerics/frequency_analysis_test.cpp, physics/analytical_series_test.cpp
This will be used in Clenshaw-Curtis, which in turn will be used to compute the inner products and norms in the Modified Gram-Schmidt introduced by #2750, continuing the inexorable progress towards #2400.
=> Allow arguments other than Time in FFT

base/bits_body.hpp, base/bits_test.cpp, geometry/complexification_body.hpp, geometry/hilbert.hpp, geometry/hilbert_body.hpp, geometry/hilbert_test.cpp, numerics/frequency_analysis_body.hpp, numerics/frequency_analysis_test.cpp, numerics/poisson_series_body.hpp, numerics/quadrature_body.hpp, numerics/quadrature_test.cpp
1. Add `Norm²` which may be more efficient than `InnerProduct` of a vector with itself.
1. Change the Clenshaw-Curtis quadrature to cache function evaluations, thus cutting the overall number of evaluations by 2.
#2400.
=> Optimization of integration

benchmarks/discrete_trajectory.cpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
Previously it was a deque.
This change elides allocations in most cases.
Note that as part of the change, the direction of ancestry was reversed
(i.e. front and back have been swapped). This is only a notational
change and has no effect.
The inlined size of two was decided upon by analyzing [a journal](https://drive.google.com/file/d/1HZarUaRBwpAPdNdPCyndqu-CIiwegv9x/view?usp=sharing). Most (~80%) instances of ancestry_ eventually got to size 2, whereas only 10% got to size 3.
I also ran the benchmarks. I wasn't sure which ones to run, so I ran all of them. The results are
[attached here](https://github.com/mockingbirdnest/Principia/files/5448752/bench.txt).
Some context: At some point I noticed my game had become laggy and profiled it to see why. It turned out that a lot of time was …
=> Changed Forkable::ancestry_ to an absl::InlinedVector.

base/jthread_body.hpp
"A default constructed stop_token has no associated stop-state, and thus has not had stop requested."
=> Adhere to the semantics of stop_token::stop_requested

astronomy/orbit_analysis_test.cpp, astronomy/orbit_ground_track.hpp, astronomy/orbit_ground_track_body.hpp, astronomy/orbital_elements.hpp, astronomy/orbital_elements_body.hpp, base/jthread.hpp, base/jthread_body.hpp, base/status.hpp, base/status_or.hpp, base/status_or_body.hpp, ksp_plugin/orbit_analyser.cpp, ksp_plugin/orbit_analyser.hpp, ksp_plugin/vessel.cpp, ksp_plugin_test/orbit_analyser_test.cpp, physics/apsides.hpp, physics/apsides_body.hpp
In order to do that:
- refactor the orbit analyser a bit so that its thread can be restarted;
- fix the `operator=` of our implementation of `jthread`;
- introduce `RETURN_IF_STOPPED`;
- pepper it throughout `OrbitalElements` and related functions;
- avoid copies of large vectors, wherein we cannot `RETURN_IF_STOPPED`;
- in particular, update `Status` for move semantics (what year is this).
The analyser can lag a little bit when updating the mission duration during the actual analysis (as opposed to the integration), I think the remaining large atomic operations are vector destructions; not much we can easily do about those.
Drive-by changes: take an exclusive lock to swap, not a reader lock, don’t flow twice to the same time.
=> Interrupt the orbit analysis if the mission duration changes

numerics/frequency_analysis_test.cpp, numerics/poisson_series_basis.hpp, numerics/poisson_series_basis_body.hpp, numerics/poisson_series_basis_test.cpp, numerics/poisson_series_body.hpp
Also a microoptimization of the evaluation of Poisson series.
#2400.
=> Use parity in basis subspaces

ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, physics/ephemeris_body.hpp
This improves performance when looking at multiple vessels in quick succession in the tracking station.
=> Make ephemeris flows interruptible and stop unused prognosticators

ksp_plugin/orbit_analyser.cpp, ksp_plugin/orbit_analyser.hpp
This allows the analyser to try to see one full revolution if the `mission_duration` appears to be too short. This will be useful in the flight plan to figure out what orbit the vessel would be in if the orbit were not interrupted by the next manœuvre.
=> Extended mission in the analyser

mathematica/floating_point.wl
Usage:
```mathematica
SetFloatingPointFormat[binary64]
HexLiteral[π]
"0x1.921FB54442D18'469…p1"
SetRoundingMode[NearestTiesToEven]
HexLiteral[CorrectlyRound[π]]
"0x1.921FB54442D18p1"
SetRoundingMode[TowardPositiveInfinity]
HexLiteral[CorrectlyRound[π]]
"0x1.921FB54442D19p1"
```
=> A HexLiteral for the IEEE754FloatingPoint package

ksp_plugin/interface_vessel.cpp, ksp_plugin_adapter/orbit_analyser.cs, serialization/journal.proto
This will make it possible to reuse the orbit analyser UI for flight plan analyses, which are not constantly refreshed.
=> Separate getting the analysis from refreshing it

ksp_plugin/interface.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, serialization/journal.proto
Fix #2824.
The renderer only has a target vessel when we are in the target frame; otherwise, from the point of view of the plugin, it is like any other vessel; by stopping all prognosticators but the main vessel’s and, immediately afterwards, all prognosticators but the target vessel’s, we stop the prognosticator of the main vessel—and thus its prediction is never recomputed.
=> Update all predictions at the same time

ksp_plugin/interface_vessel.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/orbit_analyser.cs, serialization/journal.proto
The call to refresh went to the wrong place when the two were split in #2839.
Rename the interface function accordingly.
=> Refresh when getting, not when requesting

numerics/frequency_analysis_test.cpp
We had tests that were trying to build a signal with 3 frequencies and to optimize it using the same 3 frequencies.  Unfortunately they were actually building a signal with a single frequency, and this led to poorly-conditioned behaviour when trying to use the extra frequencies.  Changing the tests to mimic what we are doing in real life.
#2400.
=> Fix two bad tests

ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
It looks like the « ex nihilo » path had a bug. Previously, this path only was only taken when Principia took control of a new vessel:
- on liftoff this happens with vanishing krakensbane;
- for EVA kerbals the mass of the kerbal was probably too small for the displacement of the vessel to be noticeable—and Kerbals have their own weirdnesses when spawning anyway.
The new welding mechanic creates parts ex nihilo, including fairly heavy ones, so this is far more visible.
This may explain the « teleportation » aspect in https://github.com/mockingbirdnest/Principia/issues/2590#issuecomment-639648219:
> the position provided by KSP […] may differ significantly from the "real" one
It probably differed because it was misinterpreted: KSP should largely be consistent with us over small time spans.
=> KSP 1.11.0, and an ancient bug

journal/player.cpp, journal/player.hpp
The referenced bug was a pilot error: I was replaying with Germain (at head, really) a journal created with Гельфонд.  Confusion ensued.  I am adding a check to help me next time this happens.
As part of investigating this I realized that the calls to `SerializePlugin` that happen when replaying may not match those of the journal, presumably because the state of the plugin is different from that at the time of journaling.  This manifests itself as mismatching `DeleteString` not finding a pointer in the map.  I presume that this happens because differences in floating point computations lead to differences e.g., in the size of trajectories.  This is unfortunate, but hard to fix.
Fix #2863.
=> Check that the version of the binary matches that of the journal

ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/orbit_analyser.cs
Add the hardcoded `(precesses)` to the localization files; translate some terms whose translation is easy.
Some untranslated strings remain, but those will have to wait until Goldbach.
=> Fix some untranslated strings

ksp_plugin_adapter/ksp_plugin_adapter.cs
Fix #2808.
This was missed in #2604, when addressing #2560.
=> Correctly compute the lever arm when there is a CoM offset.

ksp_plugin_adapter/localization/zh-cn.cfg
As alluded to in #2890,
> Some day we may want to change `轨道机动 #𝑛` to `第𝑛次轨道机动` (I suspect this is currently messing with the word order when it comes to referring to the final time of a manœuvre), but this will have to come in a subsequent release.
Use ordinals (in the linguistic sense, _i.e._, « 𝑛th manœuvre », rather than cardinals as in « manœuvre number 𝑛 ») as they don’t require any particular logic in Chinese (contrary to [English -st -nd -rd -th](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#en)).
Reworded starting and ending point to starting and ending time when referring to times.
Reworded 加速 to 时间加速 for « [time] warp »; 加速 simply means « accelerate », which is a lot more overloaded here than the original « warp ». 加速至轨道机动起点 …
=> Number manœuvres idiomatically, tweak time-related words

ksp_plugin/vessel.cpp
Previously, Vessel::RepeatedlyFlowPrognostication would loop without sleeping while prognosticator_parameters_ was empty (because the continue bypasses the std::this_thread::sleep_until call). This resulted in the thread spending 40% of its time calling std::chrono::steady_clock::now and another 20% dealing with the mutex (see attached screenshot).
This change moves the std::this_thread::sleep_until call to the beginning of the loop where it cannot be bypassed.
=> Prevent Vessel::RepeatedlyFlowPrognostication from bypassing sleep call.

ksp_plugin_adapter/ksp_plugin_adapter.cs
This will ensure that users don't disable it forever.  Example:
```
principia_override_version_check {
version = 0.24.2
version = 1.11.2
version = 2.0.666
}
```
Tested in game with 1.11.2.
=> Smarter override of version check

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp
It's no longer needed now that we have stoppable threads.
=> Remove the shutdown bit from the prognosticator parameters

physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/checkpointer_test.cpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, serialization/physics.proto
Checkpoints now go in their separate message instead of in the parent message.
#2400, take two.
=> Change the way that checkpoints are serialized to allow multiple checkpoints

ksp_plugin/integrators.hpp, ksp_plugin/orbit_analyser.cpp, ksp_plugin/vessel.cpp
=> Downsample the analyser trajectories

physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/checkpointer_test.cpp, physics/continuous_trajectory_body.hpp, physics/ephemeris_body.hpp
This had been discussed in the review of #2932, it will be needed now as the reanimator might need to report errors while integrating.
Also tighten locking now that the `Checkpointer` callbacks are no longer run under a lock.
#2400, take two.
=> Return a Status when reading from a checkpoint

ksp_plugin/plugin.cpp
This is a pretty bad bug as it would kill compatibility.  Found thanks to benchmarks.
=> Don't die on 0 fingerprint

physics/checkpointer_body.hpp, physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/continuous_trajectory_test.cpp, physics/ephemeris_body.hpp
1. Change the API to avoid exposing the checkpointer and to make it possible for clients to create readers and writers.
2. Change the reader to fully rollback the trajectory to the time of the checkpoint, including the members not captured in the checkpoint.
3. Fix an error found by Clang.
=> Improve ContinuousTrajectory checkpointing

base/recurring_thread.hpp, base/recurring_thread_body.hpp, base/recurring_thread_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
Because `Reanimate` doesn't return a result (it modifies the `Ephemeris` directly) I am adding a specialization of `RecurringThread` for void output.  I am restructuring the code a bit by moving stuff that's common to all specializations in the base class.
=> Use a RecurringThread for the reanimator

journal/player.cpp, journal/player_test.cpp, journal/profiles.cpp, ksp_plugin/vessel.cpp
Fix #2641.
Fix #2931.
Fix #2967.
=> Only append the barycentre of the parts if it is after the end of the trajectory

ksp_plugin_adapter/orbit_analyser.cs
Fix #2974—which was indeed straightforward to reproduce, so this was tested in-game.
=> Close planned orbit analyser if there is no flight plan

benchmarks/discrete_trajectory.cpp, physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
In particular,
* `DiscreteTrajectory::EvaluatePosition` and friends now only compute the interpolation when necessary (as suggested by @pleroy in #2961).
* `Forkable::{begin, front, back}` have been made more efficient.
Accordingly, DiscreteTrajectory benchmarks for `t_max`, `t_min`, and `EvaluateDegreesOfFreedom` have been added. Additionally, some unrelated DiscreteTrajectory benchmarks have been improved:
* The `find` and `lower_bound` benchmarks now correctly adapt to trajectory size.
* The iteration benchmarks now cache `begin` and `end`.
Here are the relevant benchmark diffs from fc81d60 to f52362a:
```
Benchmark                                                                   Time             CPU      Time Old      Time New       CPU Old       CPU New …
```
=> Optimizations for DiscreteTrajectory

numerics/polynomial.hpp
These functions are virtual (and overriding), and all calls to them are virtual, since we never direct calls such as
```C++
p.PolynomialInMonomialBasis<Value, Argument, degree, Evaluator>::operator()(x);
```
As a result, [they are never inlined](https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-160#example-2).
See [godbolt](https://gcc.godbolt.org/z/eoYsY1446).
This may be a good thing (inlining an evaluation of a polynomial of degree 16 may be abusive).
Perhaps we would want an inlinable (but not force-inlined) evaluation for polynomials of small known degree (e.g. in special functions), but it would have to be a separate non-virtual function.
=> Remove misleading FORCE_INLINE

Makefile, numerics/fma.hpp, numerics/fma_body.hpp, numerics/fma_test.cpp
See the comments on #3010.
To be revisited once #3019 is addressed (the SSE2 build will never have FMA, and the AVX build will be VEX-encoded).
=> No FMA with clang

numerics/polynomial_evaluators.hpp
Clang doesn’t want to sweep a defaulted template parameter under the rug when using the template as a template template parameter.
Drive-by change: remove an obsolete comment (the evaluator structs are really needed, if only to group Evaluate and EvaluateDerivative).
=> Fix the build

astronomy/date_time_body.hpp
Fix the clang build after #3040.
We could use `std::optional` to make the delayed initialization explicit, but a NaN seems less intrusive.
=> Initialize local variables in constexpr code

base/macros.hpp, numerics/next_body.hpp
=> Oveflow in constexpr arithmetic with clang 8, continued

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
It turns out that this was as simple as removing checks.  Presumably someone was lazy and didn't feel like writing a test...
A modest contribution to #2400.
=> Change downsampling to work for non-root trajectories

ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/discrete_trajectory_body.hpp, serialization/ksp_plugin.proto
A vessel now has a multi-segment history which is forked off of the (newly-added) prehistory, a trajectory with a single point.
A contribution to #2400.
=> Detect collapsibility changes and fork new segments of the history

base/version.hpp
This will help maintaining the Windows pipeline.
=> Emit a message with the compiler version at compile time

base/macros.hpp, geometry/orthogonal_map_body.hpp, integrators/integrators_body.hpp, ksp_plugin/flight_plan.cpp, ksp_plugin/part.cpp, ksp_plugin/pile_up.cpp, ksp_plugin/plugin.cpp, ksp_plugin/vessel.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, numerics/polynomial_body.hpp, physics/continuous_trajectory_body.hpp, physics/discrete_trajectory_body.hpp, physics/ephemeris_body.hpp, physics/rotating_body_body.hpp
Add a time-based LOG_IF_EVERY (as opposed to count-based like LOG_IF_EVERY_N) to avoid spamming about every trajectory, polynomial, vessel, part, etc..
With this change (and logging `WARNING` to stderr) the test added in #3070 prints
```
[ RUN      ] PluginCompatibilityTest.PreCohen
E0718 17:50:59.961947 24484 plugin_compatibility_test.cpp:65] Deserialization starting
W0718 17:50:59.975911 17736 ephemeris_body.hpp:793] Reading pre-Ἐρατοσθένης Ephemeris
W0718 17:50:59.976277 17736 rotating_body_body.hpp:196] Reading pre-del Ferro RotatingBody
W0718 17:50:59.976506 17736 continuous_trajectory_body.hpp:399] Reading pre-Cohen ContinuousTrajectory
W0718 17:50:59.984709 17736 vessel.cpp:406] Reading pre-Cesàro Vessel
W0718 17:50:59.985708 17736 part.cpp:269] Reading pre-Cesàro Part
W0718 …
```
=> Log the compatibility paths

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_adapter/reference_frame_selector.cs
Do not merge before Grothendieck.
This pull request mostly makes the API of ReferenceFrameSelector less dependent on the UI (most notably doing away with the concept of a selected celestial).
Its observable effect is to make it so that the target frame always uses the primary of the target (in the stock sense for now).
This is a preparatory step for an overhaul of the frame selection UI.
=> Refactor the ReferenceFrameSelector API

ksp_plugin_adapter/window_renderer.cs
The tooltips look like this:
They pop up after half a second so as not to be obnoxious.
=> Add support for tooltips popping up near the pointer

ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/main_window.cs
It appears that KSP has it off-by-default, it doesn’t really work anyway, and it certainly doesn’t work in the presence of Scatterer, which one should have in order to observe eclipses in RSS.
=> Remove the sun lens flare toggle

ksp_plugin_adapter/localization/celestial_strings.cfg, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/reference_frame_selector.cs
Notable changes:
* Added localized strings for the new plotting frame selector.
* Localized the word 'Pin'.
* Rewrote the update reminders to be more faithful to the en-us version. It now mentions lunation numbers, but uses a written-out explanation ("The \<n\>th new moon, as defined by Meeus's _Astronomical Algorithms_, has arrived...") as the concept does not appear to exist in Chinese.
* Corrected the patched conics toggle to actually use the term 'patched conics'. The original instead used 'original orbit plotting,' in the sense of being in the unmodded game.
* Changed a number of flight analyser error messages so that they no longer refer to the craft not being inside an SoI. (_N.B._ the term Egg originally suggested for 'gravitationally bound' was '重力束缚‘. However, this term is not …
=> Update zh-cn localization and add strings for the new frame selector

ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/localization/celestial_strings.cfg, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/localization_extensions.cs, ksp_plugin_adapter/map_node_pool.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/reference_frame_selector.cs
No functional change; preparation for fr support.
Use Lingoona articles (^d) rather than an explicit « the ».
Merge some strings to allow further reordering.
Every time the English version uses the name of a celestial without an article if it has one, e.g. « Mun orbit », « Mun periapsis », or an initial, pass instead three parameters 3k+1, 3k+2, 3k+3 which are « Mun^d », « Mun », and « M ».
Introduce a navball name string and drop the ad hoc code for that in Chinese.
=> Improve translation malleability

physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp, physics/ephemeris_test.cpp, physics/forkable.hpp, physics/forkable_body.hpp, serialization/physics.proto
This makes it possible to track a pointer that may denote either the root or some fork.
You guessed it, #2400.
=> Allow tracking the root trajectory (not only forks) during serialization

ksp_plugin_test/plugin_compatibility_test.cpp
Diurnal not because it is especially slow (103 s on my machine), but because the save is 44 MB and we might not want to check that in.
Progress towards #1119. Does not actually investigate the Лидов–古在 mechanism, that will be a job for an `astronomy` test, but gives us an initial state for such a test.
=> A diurnal test that reads Butcher’s save

astronomy/лидов_古在_test.cpp, base/macros.hpp
This should fix the mac build, where our compatibility `path` is lacking a `char16_t const*` constructor.
=> Use UTF-16 for filenames on Windows only

physics/discrete_trajectory.hpp, physics/discrete_trajectory_body.hpp, physics/forkable.hpp, physics/forkable_body.hpp, physics/forkable_test.cpp
=> A mechanism for prepending a Forkable to another Forkable

ksp_plugin_test/vessel_test.cpp, physics/degrees_of_freedom_body.hpp, physics/mock_ephemeris.hpp, testing_utilities/trajectory_factories.hpp, testing_utilities/trajectory_factories_body.hpp, testing_utilities/trajectory_factories_test.cpp
Hand computations don't really scale when we have larger trajectories for #2400.  Furthermore, injecting random degrees of freedom doesn't result in particularly strict tests.
=> Change the tests for Vessel to use trajectory factories

Principia.sln, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/differential_slider.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/time_span.cs
We now accept formats like:
```
7d
7d 6h
7d 6h 5min
7d 6h 5min 4s
```
With `d` replaced by `d6` as appropriate.
Example [here](http://regexstorm.net/tester?p=%5e%5b%2b%5d%3f%5cs*%28%3f%3cdays%3e%5cd%2b%29%5cs*d6%5cs*%28%3f%3a%28%3f%3chours%3e%5cd%2b%29%5cs*h%5cs*%28%3f%3a%28%3f%3cminutes%3e%5cd%2b%29%5cs*min%5cs*%28%3f%3a%28%3f%3cseconds%3e%5b0-9.%2c%27%5d%2b%29%5cs*s%29%3f%29%3f%29%3f&i=7d6+6h+5min+).
Fix #2984.
=> Improve the parsing of time spans

physics/discrete_trajectory2.hpp, physics/discrete_trajectory_iterator.hpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_iterator.hpp, physics/discrete_trajectory_segment_range.hpp, physics/discrete_trajectory_types.hpp, physics/physics.vcxproj, physics/physics.vcxproj.filters
=> Headers for the new-style DiscreteTrajectory

physics/discrete_traject0ry.hpp, physics/discrete_traject0ry_body.hpp, physics/discrete_traject0ry_test.cpp
Also make a test faster.
#3136.
=> Support for using segments().end() as a marker for nonexistent trajectory segments.

physics/discrete_traject0ry.hpp, physics/discrete_traject0ry_body.hpp, physics/discrete_traject0ry_test.cpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp
1. Fix the methods for which this change is necessary because a time far in the past makes sense: `lower_bound`, `upper_bound`, forgetting, etc.
2. Add a `clear` method to bring back a trajectory to its state at construction without iterator invalidation.
#3136.
=> Change FindSegment to avoid failing when given a time before the beginning of the trajectory

physics/discrete_traject0ry_body.hpp, physics/discrete_traject0ry_test.cpp
1. `ForgetAfter` should not delete all the segments, it should at least keep one empty segment.
2. Forgetting by iterator should support the past-the-end iterator.
#3136.
=> Fix some bugs related to forgetting

physics/discrete_traject0ry.hpp, physics/discrete_traject0ry_body.hpp, physics/discrete_traject0ry_test.cpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_test.cpp
This will be handy for `Entwurf`, if we ever resurrect it.  It will also be handy for using `DiscreteTraject0ry` in class `Vessel`, which is a more pressing concern.
#3136.
=> Change WriteToMessage to be capable of writing only a range of the trajectory

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_test/vessel_test.cpp, testing_utilities/discrete_trajectory_factories.hpp, testing_utilities/discrete_trajectory_factories_body.hpp
=> Convert Vessel and its test to DiscreteTraject0ry

ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp, ksp_plugin_test/mock_vessel.hpp, ksp_plugin_test/renderer_test.cpp
This requires some fixes to `MockVessel`.
#3136.
=> Convert Renderer and its test to DiscreteTraject0ry

ksp_plugin/iterators.hpp, ksp_plugin/iterators_body.hpp
=> Convert Iterator to DiscreteTraject0ry

ksp_plugin_test/plugin_compatibility_test.cpp, physics/discrete_traject0ry_body.hpp
=> Convert the plugin compatibility test to DiscreteTraject0ry

benchmarks/apsides.cpp, benchmarks/ephemeris.cpp, benchmarks/planetarium_plot_methods.cpp, ksp_plugin/ksp_plugin.vcxproj, ksp_plugin/ksp_plugin.vcxproj.filters, ksp_plugin_test/ksp_plugin_test.vcxproj, ksp_plugin_test/ksp_plugin_test.vcxproj.filters, ksp_plugin_test/plugin_integration_test.cpp, physics/ephemeris_test.cpp
This is expected to conclude the migration.
#3136.
=> Convert benchmark to DiscreteTraject0ry

ksp_plugin/pile_up.cpp, physics/discrete_traject0ry_body.hpp, physics/discrete_traject0ry_test.cpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp
1. When making the psychohistory authoritative, avoid replicating the last point of the history.
2. When attaching a trajectory, if the first time doesn't match the last time of the trajectory being appended to, prepend a point that matches.
#3136.
=> Fix problems found in game

ksp_plugin_adapter/style.cs
Before this PR, the save given in #3064 burns about 120 MiB/minute when the flight planner UI is visible.  After this PR, it uses about 10 MiB/minute.  Note that we do expect some memory growth due to Principia as the trajectories of the celestials and vessels are extended.
Fix #3064.
=> Use static styles to prevent Unity leaks

physics/discrete_trajectory_iterator.hpp, physics/discrete_trajectory_iterator_body.hpp, physics/discrete_trajectory_iterator_test.cpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp
This makes it possible to efficiently skip entire segments of the trajectory.
#3136.
=> Make DiscreteTrajectoryIterator a LegacyRandomAccessIterator

ksp_plugin/vessel.cpp, ksp_plugin_test/plugin_compatibility_test.cpp, physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_test.cpp, physics/discrete_trajectory_test.cpp
Also a small bug in pre-陈景润 compatibility that would cause us to clobber the downsampling parameters in some cases.
Fix #3203.
=> Properly downsample very flat trajectories

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/discrete_trajectory.cpp, testing_utilities/discrete_trajectory_factories.hpp, testing_utilities/discrete_trajectory_factories_body.hpp, testing_utilities/discrete_trajectory_factories_test.cpp
It turns out that this file was never added to our project (see #2776), so I didn't convert it.
Note that it's sometimes a bit hard to decide how to do the conversion: the old benchmark was doing fancy things with forks that may or may not have an equivalent with segments.
The numbers are not so nice, apparently because `operator++` and `operator--` on `DiscreteTrajectoryIterator` are costly.
Before:
```
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
BM_DiscreteTrajectoryFront                                      9.06 ns         8.97 ns …
```
=> Benchmark for DiscreteTrajectory

benchmarks/discrete_trajectory.cpp, physics/discrete_trajectory_iterator_body.hpp, physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_iterator_body.hpp, physics/discrete_trajectory_test.cpp
Also fix a 1337 identifier that I had missed.
Benchmark results (the alert reader may also want to compare with the "before" section in #3206).  Note how iteration got faster:
Before:
```
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
BM_DiscreteTrajectoryFront                                      13.9 ns         13.8 ns     49857230
BM_DiscreteTrajectoryBack                                       73.1 ns         73.7 ns     11217877
BM_DiscreteTrajectoryBegin                                      11.6 ns         11.7 ns     64102153 …
```
=> Optimize some operations of DiscreteTrajectory and friends

Makefile, physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_segment_body.hpp
=> Fix more Clang errors

physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_test.cpp
=> Make sure that the number of dense points is correctly maintained by serialization and ForgetAfter

ksp_plugin_adapter/localization_extensions.cs, ksp_plugin_adapter/lru_cache.cs
Fix #3226.
This allows for null strings (but not null objects, which `Localization.Format` does not support).
=> Mirror the overloads of Localizer.Format in LRUCache.Get and L10n.CacheFormat

ksp_plugin_adapter/time_span.cs
=> Compute time spans in Double, not Int, to avoid overflows

ksp_plugin/vessel.cpp
We'll need it when reanimating to know what segment to use.
#2400.
=> Track the backstory when checkpointing

documentation/Setup.md, ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/localization_extensions.cs
Lingoona 1.7.0 can do some fairly fancy things:
https://lingoona.com/cgi-bin/grammar#l=ru&t=%3C%3CC%3A%3C%3C1%3E%3E+%D0%BF%D0%B5%D1%80%D0%B8%D1%86%D0%B5%D0%BD%D1%82%D1%80%5Em%3E%3E.+%3C%3CC%3A%3C%3C1%3E%3E+%D0%BF%D1%80%D0%B8%D0%B1%D0%BB%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%5En%3E%3E.&v1=%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D1%8B%D0%B9&oh=1
We are stuck with a version that cannot, but we can hack in some limited support.
=> Some support for nested placeholders

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
=> Proper management of the time-to-segment map when merging trajectories with 1-point segments

ksp_plugin_adapter/ksp_plugin_adapter.cs
They produce tiny forces (micronewtons or less) there.
We never noticed that because most of the pile-up testing was done with FAR, and little forces are of little consequence prior to the advent of checkpointing for #2400.
=> Bypass stock aerodynamics outside the atmosphere

ksp_plugin_adapter/ksp_plugin_adapter.csproj
This reference, added in #3238, was set up to be copied to the output directory. We don’t want that.
=> Do not ship Assembly-CSharp-firstpass

ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/localization_extensions.cs
The result is not great (in particular in stock we end up with translated celestial names inside untranslated message templates, with any hope of sensible grammar long lost), but at least it is not saying `_Selector_` on every button in the reference frame selector.
Fix #3245.
=> Ungarble unsupported languages somewhat

ksp_plugin/renderer.cpp, ksp_plugin/renderer.hpp
Fix #3235.
The reference rotation is used here:
https://github.com/mockingbirdnest/Principia/blob/0aa17d4d67902cfeffc54aeb8d1fc7324e0599f0/ksp_plugin_adapter/planetarium_camera_adjuster.cs#L64-L76
The rotation of the pivot *is* with respect to `World`. However, the game compensates for the planetarium rotation, and we only adjust the orientation maintained by the game, we do not maintain an authoritative camera orientation, so that we should not compensate for the planetarium rotation ourselves.
=> Orient the camera in CelestialSphere, not World

physics/discrete_trajectory_body.hpp, physics/discrete_trajectory_test.cpp
This led to an inconsistent time-to-segment map (reference to a 1-point segment that was not the most recent).
#3136.
=> Merge was not processing the segments of the target after the end of the source

geometry/perspective.hpp, geometry/perspective_body.hpp, ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin_adapter/ksp_plugin_adapter.cs, serialization/journal.proto
Related to #3035.
This uses the hierarchical Keplerian structure of celestials to only plot those that could be visibly separated from their primary at some point along the plotted trajectory.
On a sample 50ish-year trajectory flying by Jupiter and Neptune, looking at the Neptune flyby in Neptune-Sun-Orbit, the framerate goes from 2 to 8 FPS; looking at the Jupiter flyby in Jupiter-Sun-Orbit, from 2 to 4 FPS.
The following table lists the bodies plotted in various situations in RSS, with multi-year trajectories:
| Reference frame & camera position | Bodies plotted |
|---|---|
| ECEF or ECI, near the Earth | Sun, Mercury, Venus,<br>(Earth), Moon,<br>Mars, ~~Phobos~~, ~~Deimos~~,<br>Vesta, Ceres,<br>Jupiter, ~~Io~~, ~~Europa~~, Ganymede, Callisto,<br>Saturn, ~~Mimas~~, ~~Enceladus~~, …
=> Don’t plot all celestials all the time

journal/player.cpp, journal/player_test.cpp, ksp_plugin/vessel.cpp
Also properly serialize the last segment when it is non-collapsible.
Fix #3277.
=> Do not do multiple checkpoints at the same time

Makefile, install_deps.sh
It is no longer needed as of #3279.
=> Remove custom optional implementation.

base/cpuid_test.cpp
(My machine does not have AVX)
#3290
=> Don't require AVX in cpuid_test.

ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, serialization/ksp_plugin.proto
=> Zermelo is हरीश चंद्र

base/not_null.hpp, base/not_null_body.hpp, base/not_null_test.cpp
This fixes an annoying -Wrange-loop-construct clang warning.
Done by creating a wrapper struct that uses the default move assignment operator for trivially move assignable pointers and the custom swap-based move assignment operator for others.
=> Make not_null<foo*> trivially copyable.

Makefile
Also replaced the usage of `sed` with the `-MT` compiler flag.
=> Added benchmark dependency rules to Makefile.

ksp_plugin_test/plugin_compatibility_test.cpp
=> Fix a test that was broken by the removal of history()

benchmark_automation/benchmark_automation.cs, benchmarks/dynamic_frame.cpp, benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp, benchmarks/ephemeris.cpp, benchmarks/fast_sin_cos_2π_benchmark.cpp, benchmarks/geopotential.cpp, benchmarks/newhall.cpp, benchmarks/perspective.cpp, benchmarks/planetarium_plot_methods.cpp, benchmarks/polynomial.cpp, benchmarks/quantities.cpp, benchmarks/symplectic_runge_kutta_nyström_integrator.cpp, benchmarks/thread_pool.cpp, benchmarks/чебышёв_series.cpp, journal/player_test.cpp, ksp_plugin_test/benchmark.cpp
Because I don't need to know a multi-second benchmark to nanosecond precision.
For example, `BM_EphemerisKSPSystem` goes from `16353847667  ns` to `16.3 s`
Microseconds, milliseconds, and seconds are used where appropriate.
Also replaced `while (state.KeepRunning())` with the updated form `for (auto _ : state)`, and updated `state.range_x()`and `state.range_y()` to `state.range(0)` and `state.range(1)`.
New benchmark output is here: [bench.txt](https://github.com/mockingbirdnest/Principia/files/7991189/bench.txt).
=> Added time units to benchmarks

astronomy/ksp_system_test.cpp, astronomy/lunar_orbit_test.cpp, astronomy/solar_system_dynamics_test.cpp, astronomy/standard_product_3_test.cpp, benchmarks/dynamic_frame.cpp, benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp, benchmarks/ephemeris.cpp, integrators/symmetric_linear_multistep_integrator_test.cpp, integrators/symplectic_runge_kutta_nyström_integrator_test.cpp, ksp_plugin/vessel.cpp, mathematica/integrator_plots.cpp, physics/ephemeris_body.hpp, physics/ephemeris_test.cpp
Deprecated macros, unused declarations, etc.
Also added a missing `reserve` call to `AppendMassiveBodiesStateToTrajectories`.
=> Fixes for some clang warnings.

astronomy/fortran_astrodynamics_toolkit_body.hpp, benchmarks/geopotential.cpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, ksp_plugin/interface_external.cpp, mathematica/mathematica_body.hpp, numerics/finite_difference_body.hpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/frequency_analysis_body.hpp, numerics/matrix_computations_body.hpp, numerics/max_abs_normalized_associated_legendre_functions_test.cc, numerics/quadrature_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp, physics/body_test.cpp, physics/geopotential_body.hpp, physics/geopotential_test.cpp, physics/oblate_body_body.hpp, testing_utilities/almost_equals_body.hpp, testing_utilities/almost_equals_test.cpp
Notably:
1. Change matrix indexing to use `A(i, j)` instead of `A[i][j]`.  It avoids having helper classes for the rows and we'll be able to convert it to `A[i, j]` in C++23.
2. Rename `dimension` into `size` because that's what it gives, the size of the storage (surely that the dimension of some vector space, but we don't care that much).
3. Add `!=` for all arrays.
4. Systematically declare `constexpr` functions `rows`, `columns` and `size`.
=> Cleanup and simplify the array APIs

base/macos_allocator_replacement.hpp, base/macos_allocator_replacement_test.cpp, base/malloc_allocator.hpp, base/malloc_allocator_test.cpp
The main containers affected are `absl::btree_set` and `absl::btree_map`, which are used in the new `DiscreteTrajectory` (and showed up in a trace).
=> Add Abseil containers to macOS allocator overrides.

journal/player_test.cpp, ksp_plugin/vessel.cpp, physics/discrete_trajectory_body.hpp, stacktrace_decoder/stacktrace_decoder.cs
1. Change the C# regexp that parses our info logs to handle properly handle indic scripts.
2. Change the consistency check that fires in [#3332](https://github.com/mockingbirdnest/Principia/issues/3332) to not cause undefined behaviour.  Not severe in itself, but it would be good if the failure message didn't have junk float values.
3. Make sure that, when we refuse to create a checkpoint because it would fall at the same time as a previous checkpoint, we leave the trajectory in a consistent state.
Consider what happens when we have the following collapsibility changes, all occurring at the same time `t`:
```
Segment #1 (NC) ⟶ Segment #2 (C) ⟶ Segment #3 (NC) ⟶ Segment #4 (C)
```
where `NC` indicates a non-collapsible segment and `C` a collapsible segment.
* At the end of `Segment #1`, we …
=> A number of fixes related to #3332

benchmarks/checkpointer_benchmark.cpp, ksp_plugin/vessel.cpp, physics/checkpointer.hpp, physics/checkpointer_body.hpp, physics/ephemeris_body.hpp
Some optimizations for `Checkpointer`:
- Changed `std::pair<Instant, typename Message::Checkpoint>` to `std::pair<Instant const, typename Message::Checkpoint>`. The second of those is the correct `value_type` for `std::map`; using the incorrect type caused spurious proto copies (which I noticed when I captured [this flame graph](https://user-images.githubusercontent.com/71856888/158324434-79d23d8f-c951-48bc-a157-f27581214d07.svg) during gameplay).
- Changed `std::set` to `absl::btree_set`, which provided some further gains.
To measure the effects of these changes I wrote some benchmarks. Here are the relevant results:
```
Benchmark                                                     Time             CPU      Time Old      Time New       CPU Old       CPU New …
```
=> Optimizations for Checkpointer

physics/continuous_trajectory.hpp, physics/continuous_trajectory_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
This API is for the exclusive use of `Ephemeris`, which needs to provide proper locking.  On the journal provided in #3230, this saves about 4% of the CPU.  On the benchmarks, the effect may be as high as 25%, but is typically more modest:
Before:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                                                 Time             CPU   Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Provide a lock-free API in ContinuousTrajectory

astronomy/ksp_resonance_test.cpp, physics/apsides_body.hpp, physics/ephemeris_body.hpp, physics/kepler_orbit_body.hpp
This improves performance by a few percents.  Before:
```
--------------------------------------------------------------------------
Benchmark                                Time             CPU   Iterations
--------------------------------------------------------------------------
ApsidesBenchmark/ComputeApsides  119451153 ns    115664830 ns          362
ApsidesBenchmark/ComputeNodes     36542126 ns     35692924 ns         1191
```
after:
```
--------------------------------------------------------------------------
Benchmark                                Time             CPU   Iterations
--------------------------------------------------------------------------
ApsidesBenchmark/ComputeApsides  113703789 ns    112403921 ns          375
ApsidesBenchmark/ComputeNodes     33949542 ns …
```
=> Use Brent's method instead of bisection for computing apsides and nodes

physics/geopotential.hpp, physics/geopotential_body.hpp
1. Move the initialization of the `Precomputations` struct to a constructor.  Add a few extra fields to the struct to avoid having to pass them as extraneous parameters.
2. Factor out the code that updates the `Precomputations` in a method `UpdatePrecomputations` of the degree and order iterators.
These changes are preparatory work for #3358, as it is expected that the computation of the potential will be able to use the new functions.
Since the code is being restructed, I ran the benchmarks to check that the performance is unaffected.  The changes are in the noise.
Before:
```
----------------------------------------------------------------------------------------
Benchmark                                              Time             CPU   Iterations …
```
=> Restructure the class Geopotential

physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp, physics/discrete_trajectory_segment_test.cpp, physics/ephemeris_test.cpp, serialization/physics.proto
This will be useful to take decisions regarding the merging of a collapsible segment into the preceding non-collapsible segment without depending on the details of the downsampling decisions.
#3375.
=> Add a function to determine if a trajectory segment was ever downsampled

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/main_window.cs, ksp_plugin_adapter/orbit_analyser.cs, ksp_plugin_adapter/reference_frame_selector.cs, ksp_plugin_adapter/window_renderer.cs
Not the prettiest thing, but it should help with usability when there are lots of windows around.
A potentially confusing quirk is that since closing the main window has the exact same effect as toggling the toolbar button, it closes all windows. It’s not clear that anything else would work well though, since there wouldn’t be an unambiguous interaction to bring it back.
Fix #2295.
=> A close window button.

ksp_plugin/vessel.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp
=> Keep appending to non-collapsible segments until they are long enough to downsample

ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/main_window.cs
Inspired by the mock in #2275; also made the length tolerances a little more human readable.
This does not change the flight plan selectors to match; that is tracked by #3395.
=> Single-line prediction settings

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs
On top of #3396.
Probably fixes #2196.
This does not completely solve #3157: the passage of time can mean we go past a marker from the prediction, shifting prediction markers of the same kind.
However, it should greatly improve it, enough that we should be able to use marker pinning as part of #3394.
=> Pool map nodes by provenance

ksp_plugin_adapter/burn_editor.cs
Spotted by @al2me6.
The interaction of an impure formatter and input detection by comparison with the formatted text leads to weirdness, as predicted.
=> Don’t drop fractional digits when loading a flight plan

ksp_plugin_test/manœuvre_test.cpp, physics/dynamic_frame_test.cpp, physics/mock_dynamic_frame.hpp
Only keep one, which is public and only overrides the pure virtual methods.
=> Clean up the two MockDynamicFrame

geometry/symmetric_bilinear_form.hpp, geometry/symmetric_bilinear_form_body.hpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, numerics/gradient_descent_body.hpp, physics/equipotential.hpp, physics/equipotential_body.hpp, physics/equipotential_test.cpp
This requires support for computing an equipotential given a `DegreesOfFreedom` (to specify position and energy).
Also make gradient descent more robust and remove some zombie code in `geometry`.
#3358.
=> Add a test to plot equipotentials at equidistant energies

ksp_plugin_adapter/burn_editor.cs
Fixes #3419.
Only considers thrusters where the associated gameobject is active. This prevents parts there there are multiple switched variants from over estimating thrust.
=> Fix for inactive thrusters being considered

mathematica/mathematica_test.cpp
On macOS, `std::filesystem` is broken (prior to Catalina).  On Ubuntu, the introduction of `Flush` caused the test to fail because apparently the file is never written to.  We don't really care, we only use the logger on Windows.
=> Only run the logger test on Windows

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/main_window.cs
=> Change the flight plan tolerance and steps to be consistent with the prediction

physics/discrete_trajectory_segment_body.hpp
The new field added in Hesse was not (always) serialized so trajectories were perpetually considered pre-Hesse.
=> Fix a buglet introduced in Hesse

ksp_plugin/plugin.cpp, ksp_plugin_adapter/config_node_parsers.cs
Fix #3430. No change to the interpretation of the initial state, thus no change to the fingerprints. All hail retrobop.
=> Fix the initialRotation

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/nearest_neighbour.cpp, numerics/nearest_neighbour_body.hpp, numerics/nearest_neighbour_test.cpp
No optimization so far.  It demonstrates that there is a sweet spot in the number of values per node for the query.  Related to #3358.
The numbers:
```
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 6144 KiB (x1)
--------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations
--------------------------------------------------------------------------------
BM_PCPBuildTree/1000/1                   1742994 ns      1737205 ns          449
BM_PCPBuildTree/1000/4                    703417 ns       695192 ns         1122
BM_PCPBuildTree/1000/16                   387528 ns       383746 ns         1870
BM_PCPBuildTree/1000/64 …
```
=> A benchmark for the PCP tree

ksp_plugin_adapter/ksp_plugin_adapter.cs
Progress on #3441.
Displaying patched conics is a way to visualize the discrepancy between Princpia’s modeling and the approximations used by stock (chiefly patched conics, as in Figure 1, but also impulsive manœuvres, as in Figure 2).
| Figure 1 | Figure 2 |
|---|---|
| ![screenshot4](https://user-images.githubusercontent.com/2284290/197392644-06c94e7d-eb94-414c-90a4-8357d57ef2a1.png) | ![screenshot2](https://user-images.githubusercontent.com/2284290/197392712-d5e45438-f30c-4901-ba1b-47923dafa1ad.png) |
However, enabling all patched conics leads to misleading display, as some conics, such as the trajectories of faraway planets, are displayed in a different reference frame (Figure 3). Depending on the choice of reference frame, all conics can be inappropriate, leading to a confusing mess …
=> Only show patched conics if the frame makes sense

numerics/global_optimization.hpp, numerics/global_optimization_body.hpp, numerics/global_optimization_test.cc
This reduces the number of local searches from 8 to 6, and finds 4 minima instead of 3.
Related to #3358.
=> Bayesian stopping rule for multi-level single linkage

parallel_test_runner/parallel_test_runner.cs
We occasionally see failures like:
```
09:48:42 System.ComponentModel.Win32Exception: The process cannot access the file because it is being used by another process
09:48:42    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
09:48:42    at principia.parallel_test_runner.ParallelTestRunner.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Principia\parallel_test_runner\parallel_test_runner.cs:line 234
```
(The line can also be 214.)
I suspect that we must release the resources held by the process, see the discussion of `Close` in the documentation of [`WaitForExit`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-7.0).
Since that is not the whole story, I am putting a retry loop around calls to …
=> Close the processes after running a test and retry process startup

ksp_plugin_adapter/time_span.cs
=> Insert zwsp between digits and units to make the selection more user-friendly

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/differential_slider.cs
Fix #3480, to the extent that we want to fix it.
This relies on the sign being the size of a figure space, which appears to be the case in whichever font I get on Windows 10.
=> No sign for a Δv of 0

mathematica/logger.hpp, mathematica/logger_body.hpp, mathematica/logger_test.cpp
1. Support for enabling/disabling a logger.
2. Support for informing distant code of the creation of loggers and letting it take action on the newly-created loggers.
=> More improvements to the Mathematica logger

benchmarks/apsides.cpp, benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/orbital_elements.cpp, numerics/piecewise_poisson_series_body.hpp, numerics/poisson_series.hpp, numerics/poisson_series_body.hpp, numerics/quadrature.hpp, numerics/quadrature_body.hpp
```
Run on (4 X 2712 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x2)
L1 Instruction 32 KiB (x2)
L2 Unified 256 KiB (x2)
L3 Unified 3072 KiB (x1)
-------------------------------------------------------------------------------------------------
Benchmark                                                       Time             CPU   Iterations
-------------------------------------------------------------------------------------------------
OrbitalElementsBenchmark/ComputeOrbitalElements        26873351050 ns   26117187500 ns            2
OrbitalElementsBenchmark/ComputeOrbitalElements        27432409050 ns   25132812500 ns            2
OrbitalElementsBenchmark/ComputeOrbitalElements        34241835950 ns   21359375000 ns            2
OrbitalElementsBenchmark/ComputeOrbitalElements_mean …
```
=> A benchmark for orbital elements

ksp_plugin_adapter/gl_lines.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/ksp_plugin_adapter.csproj
```
I0118 14:30:08.555745 40620 plugin.cpp:202] System fingerprint is 0x7A077635599E23F2
W0118 14:30:08.555745 40620 plugin.cpp:208] This appears to be the dreaded KSP stock system!
I0118 14:30:08.555745 40620 plugin.cpp:211] System fingerprint after stabilization is 0x4B830CBDF5E77F8D
I0118 14:30:08.555745 40620 plugin.cpp:218] This is the stabilized KSP system, all hail retrobop!
```
=> Support for 1.12.5

numerics/fit_hermite_spline_body.hpp, numerics/hermite3.hpp, numerics/hermite3_body.hpp, numerics/hermite3_test.cpp
Instead of computing the L∞ norm explicitly, we can check on each point if the distance between the cubic and the trajectory exceeds the tolerance and return immediately if it does.  This makes the computation considerably faster in the case where downsampling is inefficient.
=> A more efficient L-Infinity check

astronomy/orbit_analysis_test.cpp, astronomy/orbital_elements_body.hpp, astronomy/лидов_古在_test.cpp
Benchmark:
```
Run on (4 X 3311 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 6144 KiB (x1)
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
OrbitalElementsBenchmark/ComputeOrbitalElementsEquatorial  830357700 ns    828125000 ns            1
OrbitalElementsBenchmark/ComputeOrbitalElementsInclined    761847400 ns    765625000 ns            1
```
=> Avoid interpolations when computing mean elements

astronomy/orbital_elements_body.hpp, astronomy/orbital_elements_test.cpp
Test failure:
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from OrbitalElementsTest
[ RUN      ] OrbitalElementsTest.Escape
unknown file: error: C++ exception with description "vector too long" thrown in the test body.
[  FAILED  ] OrbitalElementsTest.Escape (131 ms)
[----------] 1 test from OrbitalElementsTest (131 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (134 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OrbitalElementsTest.Escape
```
=> Gracefully handle trajectories that are not gravitationally bound in OrbitalElements

ksp_plugin_adapter/flight_planner.cs
Fixes the `NullReferenceException` from #3593 (but not the main issue).
=> ClearBurnEditors may be called with burn_editors_ == null when there is no flight plan

ksp_plugin/plugin.cpp, ksp_plugin_adapter/main_window.cs
=> Avoid an overflow when extending the prediction of the target vessel

journal/player.cpp, journal/player_test.cpp, ksp_plugin/geometric_potential_plotter.cpp, physics/geopotential_body.hpp
#3358.
This should not happen (the reason why it happened is that we were using shaky bodies as secondaries, rather than the barycentres of their subsystems), but if it does, it should not bring down the game.
One of those will lead to Unity warnings about drawing NaNs, the other will lead to errors in the Principia log, but that is fine.
=> NaN resilience in equipotential computing

physics/barycentric_rotating_reference_frame_body.hpp, physics/rotating_pulsating_reference_frame_body.hpp
On mac, we are still in C++17, and `std::set` is actually an alias, so that we don’t get deduction guides.  We can revert this when we upgrade the mac build to C++20.
https://github.com/mockingbirdnest/Principia/blob/e90cf7e462da0ba4a809650e9838b4da6ac9f365/base/macos_allocator_replacement.hpp#L55-L57
=> Fix mac build

ksp_plugin/interface_renderer.cpp, ksp_plugin_adapter/planetarium_camera_adjuster.cs, serialization/journal.proto
This means that when the camera targets a fixed point in the reference frame (which can be a bit tricky since the interesting part may be the barycentre of multiple bodies; we should explore camera targeting later), the trajectories are fixed on the screen, and instead the bodies grow and shrink as expected.
=> Pulsate the camera distance in the rotating-pulsating reference frame

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg
It is really hard to explain to the user what they should do in that case.  "Just tickle the flight plan length" is not going to be helpful.  I am not proud of the wording, but it's probably an improvement over the current situation.
This will need to be localized in Chinese and Russian.
Not a fix of #3483.
=> Try to emit a message slightly more useful than "error 4"

physics/lagrange_equipotentials_body.hpp
See #3665. Accidentally reverted in #3666.
=> Bring back the typename

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/lagrange_equipotentials.cpp
```
Run on (12 X 2688 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x6)
L1 Instruction 32 KiB (x6)
L2 Unified 1280 KiB (x6)
L3 Unified 12288 KiB (x1)
---------------------------------------------------------------------------------------------------------------
Benchmark                                                                     Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------------
LagrangeEquipotentialsBenchmark/RotatingPulsating_GlobalOptimization 18900048500 ns   13562500000 ns            1
```
=> A benchmark for Lagrange equipotentials

benchmarks/lagrange_equipotentials.cpp
```
2023-06-05T16:53:16+02:00
Running C:\Users\robin\Projects\mockingbirdnest\Principia\Release\x64\benchmarks.exe
Run on (12 X 2688 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x6)
L1 Instruction 32 KiB (x6)
L2 Unified 1280 KiB (x6)
L3 Unified 12288 KiB (x1)
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
LagrangeEquipotentialsBenchmark/EarthMoon  17350231900 ns   9843750000 ns            1
LagrangeEquipotentialsBenchmark/SunNeptune 519124848300 ns   190312500000 ns            1
```
=> A benchmark for the Sun-Neptune equipotentials

physics/barycentric_rotating_reference_frame.hpp, physics/barycentric_rotating_reference_frame_body.hpp
Before:
```
2023-06-08T20:52:51+02:00
Running C:\Users\robin\Projects\mockingbirdnest\Principia\Release\x64\benchmarks.exe
Run on (12 X 2688 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x6)
L1 Instruction 32 KiB (x6)
L2 Unified 1280 KiB (x6)
L3 Unified 12288 KiB (x1)
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
LagrangeEquipotentialsBenchmark/EarthMoon   399438500 ns    328125000 ns            2
LagrangeEquipotentialsBenchmark/SunNeptune 8773415400 ns   5171875000 ns            1
```
After:
```
2023-06-08T20:50:40+02:00
Running …
```
=> Cache the derivatives of the barycentres

benchmarks/benchmarks.vcxproj, benchmarks/planetarium_plot_methods.cpp
We have been using PlotMethod3 since #3303.
```
> .\Release\x64\benchmarks.exe --benchmark_filter=Planetarium
2023-06-10T00:29:58+02:00
Running C:\Users\robin\Projects\mockingbirdnest\Principia\Release\x64\benchmarks.exe
Run on (12 X 2688 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x6)
L1 Instruction 32 KiB (x6)
L2 Unified 1280 KiB (x6)
L3 Unified 12288 KiB (x1)
---------------------------------------------------------------------------------------------
Benchmark                                                   Time             CPU   Iterations
---------------------------------------------------------------------------------------------
BM_PlanetariumPlotMethod3NearPolarPerspective            10.1 ms         6.56 ms          100 1621100 points within -1.49365 ± 7028.58 × 3.70166 ± 7029.11 × …
```
=> Benchmark PlotMethod3, not PlotMethod2.

ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/manœuvre_marker.cs, ksp_plugin_adapter/map_node_pool.cs
As alluded to in #3692, this PR adds the following functionalities to manœuvre markers:
* A pinnable hover tooltip is displayed when the cursor is hovered over the marker, emulating stock node markers. When manœuvre markers overlap node markers, manœuvre markers will take precedence for hovering. However, the stock node markers have slightly larger colliders, so it remains possible to interact with node markers that are otherwise obscured.
* When a marker is single-clicked, the flight planner will open to the corresponding burn editor.
A new localization string has been introduced, and requires translations for fr and ru.
=> Additional interactions for manœuvre markers

physics/lagrange_equipotentials_test.cpp
The theory is that the change is due to 7ded8d73dc1ac6d4e389de0064a53b7b538a8c64: in the case where we cannot meet the strong Wolfe condition, it seems logical to return our latest estimate, but it may sometimes be a bit worst than the previous one.  (Of course, the tests don't tell us about cases where it would be better.)
=> Fix the diurnal build

ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/flight_plan_optimizer.hpp, ksp_plugin_test/flight_plan_optimizer_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, t.txt
1. Use a cache to avoid evaluating the flight plan multiple times with the same burn.
2. Use the Gateaux derivative instead of computing the full gradient when possible (i.e., in the line search).  This requires changing a bit the use of the gradient descent to pass `HomogeneousArgument`s instead of `Argument`s.
3. Add a callback executed when a flight plan is evaluated and use it to count the number of evaluations of the flight plan.
Overall, the number of evaluations is reduced by a factor of 2-2.5, although in some cases the use of the Gateaux derivative can increase the cost a bit:
|Test|Manœuvre #|Options|Evaluations|
|---|---|---|---|
|ReachTheMoon|5|Original|164|
|||Cache|102|
|||Cache+Gateaux|88|
||6|Original|130|
|||Cache|89|
|||Cache+Gateaux|57|
||7|Original|127|
|||Cache|101| …
=> Optimize the flight plan optimizer

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/flight_plan_optimizer.cpp
Disable orbit analysis during flight plan optimization.  It makes the test 2.5× faster.
#3681.
=> Add support for disabling flight plan orbit analysis

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan_optimizer.cpp
If the end of the flight plan is the point that minimizes the metric, we would find a better solution with a longer flight plan, so we extend it automatically.
Also fix the copy constructor (again) to avoid appending duplicate points.
#3681.
=> Automatically extend the flight plan when its extremity is the closest point

ksp_plugin/interface_flight_plan.cpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/style.cs, ksp_plugin_adapter/window_renderer.cs, serialization/journal.proto
What it looks like:
This PR does the following:
1. Add localization tags.
2. Move the optimize button to the burn.
3. Move the optimization parameters up a bit, and makes inclination optimization optional.
4. Change the interface to separate the creation of an optimization driver from the actual run of the optimization driver.  The driver is updated when the parameters change.  This means in particular that changes the parameters interrupts the optimization.
=> Clean up the optimization UI

astronomy/geodesy_test.cpp, astronomy/standard_product_3_test.cpp, benchmarks/apsides_benchmark.cpp, benchmarks/ephemeris_benchmark.cpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_integrator_body.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp, integrators/explicit_linear_multistep_integrator_body.hpp, integrators/explicit_runge_kutta_integrator_body.hpp, integrators/ordinary_differential_equations.hpp, integrators/ordinary_differential_equations_body.hpp, integrators/symmetric_linear_multistep_integrator_body.hpp, integrators/symplectic_runge_kutta_nyström_integrator_body.hpp, ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp, ksp_plugin/interface_flight_plan.cpp, ksp_plugin/pile_up.cpp, ksp_plugin_adapter/flight_planner.cs, ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_test/plugin_compatibility_test.cpp, ksp_plugin_test/plugin_test.cpp, ksp_plugin_test/vessel_test.cpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp, physics/mock_ephemeris.hpp, serialization/journal.proto
This properly handles the "deadline exceeded" error, by effectively "tickling" the flight plan when necessary.
Fix #3483.
=> Add a thread to asynchronously prolong the ephemeris in the FlightPlan

astronomy/orbit_analysis_test.cpp, astronomy/orbital_elements_body.hpp, astronomy/лидов_古在_test.cpp, journal/player_test.cpp, testing_utilities/matchers.hpp
If the step would go over `period / 3` we reduce drastically the tolerance-to-error ratio to force the integrator to generate denser points.  This ensures that the unwinding algorithm never sees a jump bigger than `period / 2`, and that M is always increasing.
Fix #3569.
=> Don't allow the adaptive step integrator to use steps that are too long

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Add a dampening torque when the angularDrag field is set

ksp_plugin/vessel.hpp, ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs
That's in addition to being recreated when the optimization parameters change.
Fixes parts of #3789.
=> The optimizer holds a copy of the flight plan so it must be recreated whenever burns get added/deleted.

ksp_plugin/flight_plan_optimization_driver.cpp, ksp_plugin/flight_plan_optimization_driver.hpp, ksp_plugin/vessel.cpp, ksp_plugin/vessel.hpp
#3789 has a crash with `Check failed: has_deserialized_flight_plan()` in `UpdateFlightPlanFromOptimization`.  While I wasn't able to reproduce the crash, the API is unfriendly as it requires the UI to carefully keep track of the calls that may have deserialized the flight plan before calling `principia__FlightPlanUpdateFromOptimization `.  That's a very brittle precondition.  If we are going to optimize the flight plan, we might as well deserialize it.
I'm also moving the last parameters into the optimization driver, where they belong.  A given vessel may logically have multiple optimizations in flight for multiple flight plans, so having this information in the vessel was plain wrong.
Fix #3789.
=> Deserialize the flight plan when calling the optimization entry points

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Don't try to render markers related to the target vessel when the target vessel does not exist

.gitignore, ksp_plugin_adapter/ksp_plugin_adapter.cs
With the vessel in #3230, which has 1167 parts, the time spent in `WaitedForFixedUpdate` goes down from 183 ms to 54 ms.
=> Optimize the code in the adapter

ksp_plugin_adapter/interface.cs, ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/mono_marshaler.cs, ksp_plugin_adapter/utf8_marshaler.cs
1. Avoid double conversions (e.g., `Vector3` → `Vector3d` → `XYZ`).
2. Use local variables to hold nontrivial expressions.
3. Disable physics auto-sync over a larger region.
4. Do a bit less work in the marshallers (notably, less allocations).
None of that makes a big difference.  Optimistically, this PR brings a 10% speed up in the test case of #3230.
=> A bunch of micro-optimizations in the adapter

geometry/r3_element.hpp, geometry/r3_element_body.hpp, physics/apsides.hpp, physics/apsides_body.hpp, physics/apsides_test.cpp, physics/rotating_body.hpp, physics/rotating_body_body.hpp
=> A function to compute a collision between a vessel and a celestial

ksp_plugin_adapter/burn_editor.cs, ksp_plugin_adapter/flight_planner.cs
Addresses the following issue reported by **test_account** on Discord:
>Also, it seems to always choose "Inertially fixed" which can waste some dV for longer burns.
=> Properly reset the optimizer after each change of the flight plan

ksp_plugin/flight_plan_optimization_driver.cpp
It used to disable itself, but that was lost in a code restructuring.  I noticed this in a video shared by **Prophet1313** on Discord.
=> Disable the Optimize button when an optimization is in progress

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan_optimization_driver.cpp, ksp_plugin/flight_plan_optimization_driver.hpp, ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin/vessel.cpp
The copy doesn't have an orbit analyser, we only want one when it was created by the optimizer.
=> Do not create a flight plan copy when creating an optimization driver

ksp_plugin_adapter/map_node_pool.cs
Possibly fix #3826. The preconditions on `ComputeCollision` are a bit of a mess, but so long as we are underground at `last_time` it should work. However, we were instead checking whether we would have been underground had we been on one branch of the φ=λ analemma. The height above terrain calculation used to actually compute the collision was correct, which is why it would show up in the right place (up to the issue of multiple intersections). This may explain some oddities as to whether we would try to compute the collision at all—though the underground periapsis thing is of course fundamentally deficient as a criterion.
=> Compute the terrain altitude at the right place to determine whether the periapsis is underground

geometry/r3x3_matrix_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_computations_test.cpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp, testing_utilities/almost_equals_body.hpp
Also adds lots of operations to vectors and matrices, and fixes a longstanding case of UB in `AlmostEquals`.
=> Hessenberg decomposition of a matrix

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/gradient_descent_body.hpp, numerics/matrix_computations_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
1. Make sure that `fixed` and `unbounded` arrays have the same operations where it makes sense.
2. Use `TransposedView` in more places.
This PR causes a fair amount of code replication that will be addressed later.
=> Clean up the arrays code

numerics/чебышёв_series_body.hpp, physics/apsides.hpp, physics/apsides_body.hpp, physics/apsides_test.cpp
=> A function to compute the first collision between a vessel and a celestial

numerics/approximation.hpp, numerics/approximation_body.hpp, numerics/approximation_test.cpp, physics/apsides_body.hpp
1. Give the caller control over the `max_degree`.
2. Return the `error_estimate`.
3. Don't recompute the interpolation matrices all the time.
#2913.
=> Improvements to Чебышёв polynomial approximants

ksp_plugin_adapter/localization/en-us.cfg, ksp_plugin_adapter/localization/fr-fr.cfg, ksp_plugin_adapter/localization/ru.cfg, ksp_plugin_adapter/localization/zh-cn.cfg, ksp_plugin_adapter/map_node_pool.cs
=> Add captions to the impact marker

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/map_node_pool.cs
=> Support for collisions in the flight plan

base/push_pull_callback.hpp, base/push_pull_callback_body.hpp, journal/player_test.cpp, journal/profiles.cpp
The journal replaying for #3872 was not completely conclusive as it didn't reproduce the crash.  However, it told us exactly what code we were executing when the crash happened.  After staring at this code for a while, @eggrobin noticed that the `PushPullCallback` class would always be destroyed with its internal mutex held.  That's violates the invariants of `Mutex` and might cause plague and pestilence.
This change may or may not address #3872.
=> Fix locking in PushPullCallback

astronomy/orbit_recurrence_body.hpp, astronomy/orbital_elements_body.hpp, numerics/elliptic_integrals.cpp
By restricting identifiers to [UAX31-R1](https://www.unicode.org/reports/tr31/#R1) with the [Mathematical Compatibility Notation Profile](https://www.unicode.org/reports/tr31/#Mathematical_Compatibility_Notation_Profile).
=> Make it build on clang 16+

ksp_plugin_adapter/localization_extensions.cs
=> Properly handle a null primary in the orbit analyser

numerics/concepts.hpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/matrix_computations_body.hpp, numerics/numerics.vcxproj, numerics/numerics.vcxproj.filters, numerics/transposed_view.hpp, numerics/transposed_view_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
Note that this makes heavy use of concepts, so we'll have to see if Clang is happy with it.
Contributes to #3302.
=> Improve TransposeView by exposing operations for sizing and indexing

ksp_plugin_test/flight_plan_optimizer_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/transposed_view.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
1. Remove `Transpose`.
2. Remove most references to `transpose`.
Contributes to #3302.
=> Add support for constructing a matrix from a TransposedView

Makefile, base/version.hpp, integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator.hpp, integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp, integrators/integrators.hpp, integrators/symmetric_linear_multistep_integrator.hpp, numerics/angle_reduction.hpp, physics/mechanical_system_test.cpp, principia.props
Includes resurrecting `Release_LLVM`.
=> Migration to Clang 16

numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp
This exercises more code, so of course it uncovered bugs.
Contributes to #3302.
=> Make the tests for fixed and unbounded arrays consistent

benchmarks/discrete_trajectory_benchmark.cpp, geometry/barycentre_calculator.hpp, geometry/barycentre_calculator_body.hpp, geometry/barycentre_calculator_test.cpp, geometry/perspective_body.hpp, geometry/point_test.cpp, ksp_plugin/flight_plan_optimizer.cpp, ksp_plugin_test/flight_plan_optimizer_test.cpp, ksp_plugin_test/vessel_test.cpp, mathematica/mathematica_body.hpp, numerics/apodization_body.hpp, numerics/approximation_body.hpp, numerics/nearest_neighbour_body.hpp, numerics/newhall_body.hpp, numerics/poisson_series_basis_body.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp, numerics/root_finders_body.hpp, physics/apsides_body.hpp, physics/barycentric_rotating_reference_frame_body.hpp, physics/barycentric_rotating_reference_frame_test.cpp, physics/body_centred_body_direction_reference_frame_test.cpp, physics/ephemeris_test.cpp, physics/equipotential_body.hpp, physics/equipotential_test.cpp, physics/lagrange_equipotentials_body.hpp, physics/lagrange_equipotentials_test.cpp
Not touching the container one for now, so those callers are still ugly.
Also we probably want a 1-parameter overload for equal weights, but I will do that in a subsequent change.
=> Get rid of Barycentre of std::pair and simplify its callers

base/macros.hpp, numerics/polynomial.hpp, numerics/polynomial_evaluators_body.hpp, numerics/polynomial_in_monomial_basis.hpp, numerics/polynomial_in_monomial_basis_body.hpp, numerics/polynomial_in_чебышёв_basis.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp
1. Pass quantities by copy.
2. Use `__vectorcall` to return results in registers.
3. Simplify the control flow for degree less than 2, where Estrin and Horner are identical.
4. Do not generate the squares upfront for Estrin, rely on common subexpression elimination instead.
The benchmarks after this PR show small but consistent improvements of 5-10% (compare with #3930).
```
CPU Caches:
------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                              Time             CPU   Iterations …
```
=> Optimize the polynomial evaluation

base/macros.hpp, geometry/r3_element_body.hpp, geometry/r3x3_matrix_body.hpp, integrators/integrators_body.hpp, ksp_plugin/interface_body.hpp, ksp_plugin_test/pile_up_test.cpp, numerics/global_optimization_body.hpp, numerics/polynomial_in_чебышёв_basis_body.hpp, physics/body_body.hpp, physics/euler_solver_body.hpp, physics/geopotential_body.hpp, physics/hierarchical_system_body.hpp, physics/massive_body_body.hpp, physics/oblate_body_body.hpp, physics/solar_system_body.hpp, quantities/parser_body.hpp, testing_utilities/solar_system_factory_body.hpp, tools/journal_proto_processor.cpp
An SPRK can be viewed as an SRKN, so we need to check for both kinds of ODE at deserialization time.
Also remove `base::noreturn`, which hid the bug for a year, and use `std::abort` instead.
=> Fix a bug in the deserialization of integrators

ksp_plugin_test/plugin_compatibility_test.cpp
ElementsAre ends up using `std::span::const_iterator` which [is C++23](https://en.cppreference.com/w/cpp/container/span).
=> Our C++ is too modern for clang

numerics/fit_hermite_spline.hpp, numerics/fit_hermite_spline_body.hpp, numerics/fit_hermite_spline_test.cpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/fixed_arrays_test.cpp, numerics/hermite3.hpp, numerics/hermite3_body.hpp, numerics/hermite3_test.cpp, numerics/poisson_series.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp, numerics/unbounded_arrays_test.cpp, physics/apsides_body.hpp, physics/discrete_trajectory_segment.hpp, physics/discrete_trajectory_segment_body.hpp
1. Reorder the template parameters of `Hermite3`.
2. Move construction for matrices.
3. No `size` for matrices.
4. Remove a few obsolote TODOs.
=> Fix a few TODOs

physics/apsides_body.hpp, physics/apsides_test.cpp
=> Do not try to find collision intervals when the computation of the apsides is ill-conditioned

functions/std_accuracy_test.cpp
=> More precise error estimate for elementary functions

functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp, functions/functions.vcxproj, functions/functions.vcxproj.filters, functions/std_accuracy_test.cpp
Many things to be improved, notably:
1. Only looks for accurate values for a single function.
2. Does an exhaustive search.
3. Single-threaded.
#1760.
=> A basic accurate table generator

functions/accurate_table_generator_test.cpp, functions/functions.vcxproj, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, principia.props, shared/base.vcxitems
This also adds support for output in base 2, and amends the test for accurate tables to check the binary representation more directly.
Also some tidying of the property files.
#1760.
=> Mathematica output of cpp_bin_float

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/elementary_functions_benchmark.cpp, benchmarks/trigonometry_benchmark.cpp
Output:
```
CPU Caches:
------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations
------------------------------------------------------------------------------------------------------
BM_EvaluateElementaryFunction<Metric::Latency, std::sin>          5.96 ns         6.00 ns    112000000
BM_EvaluateElementaryFunction<Metric::Throughput, std::sin>       4.04 ns         3.99 ns    172308000
BM_EvaluateElementaryFunction<Metric::Latency, std::cos>          6.84 ns         6.84 ns    112000000 …
```
=> A benchmark for some elementary functions

functions/cos.cc, functions/sin.cc, numerics/fma.hpp
=> Remove the FMA preventer and avoid FMA for Clang in core-math

boost_multiprecision.props, functions/functions.vcxproj, numerics/polynomial_in_monomial_basis.hpp, numerics/polynomial_in_monomial_basis_body.hpp, numerics/polynomial_in_monomial_basis_test.cpp, quantities/concepts.hpp, quantities/elementary_functions.hpp, quantities/elementary_functions_body.hpp, quantities/generators_body.hpp, quantities/quantities.hpp, quantities/quantities_body.hpp
1. Add support for Boost multiprecision types in `quantities`, in particular for elementary functions and tracing.
2. Adjust the concepts so that the Boost multiprecision types are considered to have the appropriate algebraic structure.
3. Fix a bug in the composition of polynomials with nontrivial origins.
#1760.
=> Prerequisites for the implementation of the Stehlé-Zimmermann algorithm

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/elementary_functions_experiments_benchmark.cpp, benchmarks/tradeoffs_benchmark.cpp, functions/std_accuracy_test.cpp, ksp_plugin_test/vessel_test.cpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/double_precision_test.cpp
* With a spacing of 2/256, we need a degree-2 polynomial for cos.
* With a spacing of 2/1024, we can use a degree-1 polynomial for both sin and cos.
The latter wins:
```
CPU Caches:
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
BM_EvaluateSinTableSpacing<2.0 / 256.0>        2.56 ns         2.55 ns    263530000
BM_EvaluateSinTableSpacing<2.0 / 1024.0>       2.26 ns         2.25 ns    320000000
BM_EvaluateCosTableSpacing<2.0 / 256.0>        2.54 ns         2.57 …
```
=> A benchmark to decide on the spacing of accurate values table

.gitignore, benchmarks/elementary_functions_benchmark.cpp, benchmarks/elementary_functions_experiments_benchmark.cpp
Not great, not terrible:
```
CPU Caches:
---------------------------------------------------------------------
Benchmark                           Time             CPU   Iterations
---------------------------------------------------------------------
BM_ExperimentSinMultiTable       3.24 ns         3.22 ns    213334000
BM_ExperimentCosMultiTable       3.21 ns         3.22 ns    213334000
```
For reference, the Windows implementation:
```
BM_EvaluateElementaryFunction<Metric::Throughput, std::sin>       2.22 ns         2.20 ns    298667000
BM_EvaluateElementaryFunction<Metric::Throughput, std::cos>       2.44 ns         2.40 ns    280000000
```
#1760.
=> A benchmark for a multi-table implementation of sin and cos

ksp_plugin/vessel.cpp, ksp_plugin_test/vessel_test.cpp
The scenario is this:
1. The test thread calls `RefreshPrediction` [here](https://github.com/mockingbirdnest/Principia/blob/b860ba6c0ccd137aa967b6bf75c2e135c55c0204/ksp_plugin_test/vessel_test.cpp#L305).
2. It gets suspended after calling `Start` [here](https://github.com/mockingbirdnest/Principia/blob/b860ba6c0ccd137aa967b6bf75c2e135c55c0204/ksp_plugin/vessel.cpp#L622) but before calling `Get`.
3. The prognosticator thread executes `FlowPrognostication` [here](https://github.com/mockingbirdnest/Principia/blob/b860ba6c0ccd137aa967b6bf75c2e135c55c0204/ksp_plugin/vessel.cpp#L1102), and consumes the `WillOnce` expectation [here](https://github.com/mockingbirdnest/Principia/blob/b860ba6c0ccd137aa967b6bf75c2e135c55c0204/ksp_plugin_test/vessel_test.cpp#L289).  This results in a proper …
=> Fix a race between the code and the test for Vessel

benchmarks/elementary_functions_experiments_benchmark.cpp, ksp_plugin_test/vessel_test.cpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp
Interestingly a tad faster than the multi-table implementation in #4011, showing that tests are *way* more expensive than floating-point computations:
```
CPU Caches:
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_ExperimentSinSingleTable       3.04 ns         3.00 ns    224000000
BM_ExperimentCosSingleTable       2.99 ns         2.93 ns    224000000
```
=> A benchmark for a single-table implementation of sin and cos

benchmarks/elementary_functions_experiments_benchmark.cpp, mathematica/floating_point.wl, numerics/double_precision.hpp, numerics/double_precision_body.hpp
A bit faster:
```
CPU Caches:
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_ExperimentSinSingleTable       2.89 ns         2.85 ns    235790000
BM_ExperimentCosSingleTable       2.84 ns         2.83 ns    248889000
```
#1760.
=> Round the polynomial coefficients using Mathematica and take advantage of powers of two

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/elementary_functions_benchmark.cpp, benchmarks/elementary_functions_experiments_benchmark.cpp, benchmarks/metric.hpp, benchmarks/polynomial_in_monomial_basis_benchmark.cpp
```
CPU Caches:
---------------------------------------------------------------------------------------------------------
Benchmark                                                               Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------
BM_EvaluateElementaryFunction<Metric::Latency, std::sin>             7.25 ns         7.15 ns     89600000
BM_EvaluateElementaryFunction<Metric::Throughput, std::sin>          2.22 ns         2.25 ns    320000000
BM_EvaluateElementaryFunction<Metric::Latency, cr_sin>               31.8 ns         31.5 ns     21334000 …
```
=> Latency benchmark for the elementary functions

benchmarks/elementary_functions_experiments_benchmark.cpp
Note that FMA decreases both the latency (good) and the throughput (bad) a bit.
```
CPU Caches:
---------------------------------------------------------------------------------------------------------
Benchmark                                                               Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------
BM_ExperimentSinTableSpacing<Metric::Latency, 2.0 / 256.0>           11.6 ns         11.7 ns     64000000
BM_ExperimentSinTableSpacing<Metric::Throughput, 2.0 / 256.0>        2.59 ns         2.62 ns    280000000 …
```
=> Use polynomial evaluators to compute the polynomials for sin and cos

benchmarks/elementary_functions_benchmark.cpp, benchmarks/elementary_functions_experiments_benchmark.cpp
```
CPU Caches:
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
BM_ExperimentSinNearZero<Metric::Latency>          11.8 ns         11.7 ns     56000000
BM_ExperimentSinNearZero<Metric::Throughput>       3.50 ns         3.53 ns    194783000
BM_ExperimentCosNearZero<Metric::Latency>          11.3 ns         11.2 ns     56000000
BM_ExperimentCosNearZero<Metric::Throughput>       2.33 ns         2.30 ns    298667000
```
#1760.
=> Support for sin arguments near zero and simplification of the cos

base/macros.hpp, benchmarks/elementary_functions_benchmark.cpp, benchmarks/elementary_functions_experiments_benchmark.cpp, mathematica/floating_point.wl, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/fma.hpp, numerics/polynomial_evaluators.hpp, numerics/polynomial_evaluators_body.hpp
I am changing the existing benchmarks to force FMA, as that makes their results cleaner, and I am adding a benchmark to evaluate the cost of the FMA decision.
I also noticed that loop unrolling was creating noise (if the code in the benchmark loop was getting too big unrolling would stop and it would loop like we took a big performance hit).  So I am unrolling by hand.
```
CPU Caches:
---------------------------------------------------------------------------------------------------------
Benchmark                                                               Time             CPU   Iterations
----------------------------------------------------------------------- …
```
=> Change the FMA support to make it possible to test for FMA upstream and propagate the decision

ksp_plugin_adapter/ksp_plugin_adapter.cs, ksp_plugin_adapter/manœuvre_marker.cs
In the tracking station, one may switch from a vessel with a flight plan to one without. The stale markers still need to be cleared.
The only reason this ever worked in flight is because one cannot delete a non-empty flight plan.
Fix #4029.
=> Correctly clear manœvre markers when the flight plan disappears

ksp_plugin_adapter/ksp_plugin_adapter.cs
=> Early detection of NaN in terrain computation

benchmarks/benchmarks.vcxproj, benchmarks/benchmarks.vcxproj.filters, benchmarks/lattices_benchmark.cpp
Results:
```
CPU Caches:
---------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                 Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------------------------
LatticesBenchmark<double, 1'000'000>/LenstraLenstraLov├íszDouble6                      1808 ns         1800 ns       408000
LatticesBenchmark<double, 1'000'000'000>/LenstraLenstraLov├íszDouble9                  1737 ns         1766 ns       345000 …
```
=> A benchmark for lattice reduction

benchmarks/lattices_benchmark.cpp
```
CPU Caches:
----------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                              Time
CPU   Iterations
----------------------------------------------------------------------------------------------------------------------------------------
LatticesBenchmark<double, 1'000>/LenstraLenstraLov├íszDouble3                                       1659 ns         1629 ns       374000
LatticesBenchmark<double, 1'000'000>/LenstraLenstraLov├íszDouble6                                   1630 ns …
```
=> Fix a bug in the lattices benchmark and add new instances

functions/accurate_table_generator_body.hpp, numerics/fixed_arrays.hpp, numerics/fixed_arrays_body.hpp, numerics/matrix_computations.hpp, numerics/matrix_computations_body.hpp, numerics/matrix_views.hpp, numerics/matrix_views_body.hpp, numerics/unbounded_arrays.hpp, numerics/unbounded_arrays_body.hpp
We were not overly consistent as to whether we preferred `int` or `std::int64_t`, and this led to annoying `static_cast`.
#1760.
=> Use std::int64_t in matrices

benchmarks/lattices_benchmark.cpp
TL;DR: It is 200-300× faster than LLL.
```
Running C:\Users\phl\Projects\GitHub\Principia\Principia\Release\x64\benchmarks.exe
CPU Caches:
----------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                              Time             CPU   Iterations
----------------------------------------------------------------------------------------------------------------------------------------
LatticesBenchmark<double, 1'000>/LenstraLenstraLovászDouble3                                        894 ns          899 …
```
=> A benchmark for the Nguyễn-Stehlé algorithm

functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
Also optimize the remainder computation.  After this change the bulk of the time is spent in polynomial composition.
#1760.
=> Use Nguyễn-Stehlé in the accurate table generation

ksp_plugin_test/vessel_test.cpp
The test that is waiting for the prediction to be ready and the computation of the prognostication are fundamentally racing with each other.  Prior to this PR, it was possible for the prediction computed by the first set of expectations to not be picked by `RefreshPrediction`, and subsequent expectation would not grow the prediction.
This PR is just reflecting the actual behaviour in the mock.
=> Fix a test that is causing the Release build to flake

ksp_plugin_adapter/ksp_plugin_adapter.csproj, ksp_plugin_adapter/manœuvre_marker.cs
The previous implementation leaked four materials per marker, since access to the `material` field actually copies the material.
Also updates the C# language version to `latest`. There are certain runtime-dependent features (range indexing `^1`, static-method-in-interface, &c.) that don't work, but the vast majority of syntax sugar is fine.
=> Don't leak materials in markers

base/not_null.hpp, base/not_null_body.hpp, base/not_null_test.cpp, ksp_plugin/pile_up.hpp, ksp_plugin/plugin.cpp
It turns out that it creates endless pain in `not_null` because MSVC blows up left and right whenever we touch that class.
=> Rollback the change in #4079

base/bits.hpp, base/bits_body.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp, geometry/interval.hpp, geometry/interval_body.hpp
Intervals of measure 2 T₀ (after rescaling) on each side of the starting argument are processed sequentially and there is no "bleeding" of an interval onto the next one.  The search for each interval takes 10-50 ms, and is therefore suitable for parallelization.  This is preparatory work for speculatively searching in distant intervals when we have free cores.
Note that changing the intervals means that the heuristic can find different solutions.  It's the case in one of the tests.
#1760.
=> Process intervals with predictible bounds in the Stehlé-Zimmermann search

functions/accurate_table_generator_body.hpp
This is a semantics-preserving change in preparation for speculative execution:
1. Move the rescaling code to a separate function, `ScaleToBinade0`.
2. Extract the code that searches in a "slice" of two intervals of measure 2 T₀.
3. Remove dead code related to the LLL algorithm (which we don't use anymore).
#1760.
=> Restructure the code of Stehlé-Zimmermann search

functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp, numerics/polynomial_in_monomial_basis_test.cpp
Also remove a call to `Compose` by doing a single change of variable instead of two.
#1760.
=> Let's generate the tables that we actually need for the Gal algorithm

numerics/double_precision_body.hpp, numerics/hermite3_test.cpp, numerics/polynomial_in_чебышёв_basis_test.cpp, numerics/root_finders_body.hpp, numerics/root_finders_test.cpp
Thanks to @gotmachine for bringing this eight year old code to our attention.
=> Add a test for quadratic and near-quadratic Hermite3, fix SolveQuadraticEquation for determinants near 0

numerics/lattices_body.hpp, numerics/lattices_test.cpp
=> Avoid double-to-int64_t overflows in the lattice reduction

functions/accurate_table_generator_body.hpp
The old code was producing an incorrect solution near 1/512 (one of the functions was halfway between machine numbers).  The new code handles this correctly, and also produces better (i.e., less perturbed) solutions near 8/512 and 32/512.
#1760.
=> Properly handle binade boundaries in the Stehlé-Zimmermann algorithm

functions/accurate_table_generator.hpp, functions/accurate_table_generator_body.hpp, functions/accurate_table_generator_test.cpp
It's somewhat hard to measure the speed-up because it depends a lot on multiprocessing, but realistically this might be around 10-20%.
#1760.
=> Micro-optimizations of the Stehlé-Zimmermann search

benchmarks/elementary_functions_benchmark.cpp, functions/sin_cos_test.cpp, numerics/double_precision.hpp, numerics/double_precision_body.hpp, numerics/sin_cos.cpp, numerics/sin_cos.hpp
* Support for angles in [-π/4, π/4].
* Support for uninitialized `DoublePrecision` objects.
* Improved computation of the table index.
Benchmark:
```
CPU Caches:
------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations
------------------------------------------------------------------------------------------------------
BM_EvaluateElementaryFunction<Metric::Latency, std::sin>          7.26 ns         7.25 ns    112000000 cycles: 27.5162
BM_EvaluateElementaryFunction<Metric::Throughput, std::sin>       2.12 ns …
```
=> A benchmark for our trigonometric functions and a few performance improvements

base/push_pull_callback.hpp, base/push_pull_callback_body.hpp, base/push_pull_callback_test.cpp
The `thread_` must be declared last because its execution uses the other member variables.
Fix #4136.
=> Avoid a race in the construction of PushPullExecutor

numerics/numerics.vcxproj, numerics/sin_cos.cpp, numerics/sin_cos.hpp
* Don’t inline the functions.
* fix the garbled argument reduction in UNDER_OSACA_HYPOTHESES;
* carry the loop through registers by default now that ordering the graph is dealt with by https://github.com/mockingbirdnest/OSACA/pull/21;
* use an outer loop to pin the markers where the loop-carried dependencies are still valid;
* make the OSACA_loop_terminator volatile. Reading it early did not seem to allow any unwanted optimizations, but it made the code less readable, with a load outside the loop and a mysterious test at the end. The extra movzx is irrelevant to latency analysis.
Now works as expected for other quadrants, e.g., θ = 3 (CSX; Mind the missing roundsd latency; something else seems to be missing, [compare other *CAs on the same …
=> Improve the OSACA macros

functions/functions.vcxproj, functions/sin_cos_test.cpp, numerics/sin_cos.cpp
1. Cleanup leftovers from the previous version of OSACA macros.
2. Simplify the FMA wrappers.
3. Change all the algorithms except `Sin` near 0 to operate on the absolute value of their operand and restore the sign at the end if needed.
4. Extract a deeply nested FMA and replace it with a multiplication.  This makes a difference on Zen.
Comparison on Zen 3.  Before:
```
RAW TSC:                         min      1‰      1%      5%     10%     25%     50%
identity            4.94   +0.00   +0.00   +0.00   +0.38   +0.38   +0.38
sqrtps_xmm0_xmm0           16.72   +0.38   +0.38   +0.38   +0.38   +0.38   +0.38
mulsd_xmm0_xmm0            7.60   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
mulsd_xmm0_xmm0_4x           15.20   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
Slope: 1.186186 cycle/TSC …
```
=> More optimizations of Sin and Cos

numerics/cbrt.cpp, numerics/numerics.vcxproj, numerics/osaca.hpp, numerics/sin_cos.cpp, quantities/elementary_functions_body.hpp
Also use intrinsics for Sqrt (broken by https://github.com/mockingbirdnest/Principia/pull/3722)
Method 5²Z4¹FMA fast path, on SKX:
=> Move the *CA markup macros into their own header and mark up Cbrt

functions/sin_cos_test.cpp, numerics/sin_cos.cpp
Don't use the `roundsd` instruction but use an addition and a subtraction to drop the fractional part.  This in turn makes it possible to use FMA in two places.
Comparison on Zen 3. Before:
```
RAW TSC:                         min      1‰      1%      5%     10%     25%     50%
identity            4.94   +0.00   +0.00   +0.00   +0.38   +0.38   +0.38
sqrtps_xmm0_xmm0           16.72   +0.38   +0.38   +0.38   +0.38   +0.38   +0.38
mulsd_xmm0_xmm0            7.60   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
mulsd_xmm0_xmm0_4x           15.20   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
Slope: 1.186186 cycle/TSC
Correlation coefficient: 0.999887
Cycles:             expected     min      1‰      1%      5%     10%     25%     50%
R           identity       0   -0.07   +0.00   +0.00 …
```
=> Improve argument reduction

functions/sin_cos_test.cpp, numerics/sin_cos.cpp
Comparison on Zen 3.  Before:
```
RAW TSC:                         min      1‰      1%      5%     10%     25%     50%
identity            4.94   +0.00   +0.00   +0.00   +0.38   +0.38   +0.38
sqrtps_xmm0_xmm0           16.72   +0.00   +0.38   +0.38   +0.38   +0.38   +0.38
mulsd_xmm0_xmm0            7.60   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
mulsd_xmm0_xmm0_4x           15.20   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
Slope: 1.186186 cycle/TSC
Correlation coefficient: 0.999887
Cycles:             expected     min      1‰      1%      5%     10%     25%     50%
R           identity       0   -0.07   +0.00   +0.00   +0.00   +0.45   +0.45   +0.45
R    mulsd_xmm0_xmm0       3    3.08   +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
R mulsd_xmm0_xmm0_4x      12   12.10   +0.00 …
```
=> Do not preserve the sign in argument reduction if computing a Cos

benchmarks/elementary_functions_benchmark.cpp, functions/sin_cos_test.cpp, nanobenchmarks/main.cpp, numerics/osaca.hpp, numerics/sin_cos.cpp, numerics/sin_cos.hpp
It removes some `if` statements, and more importantly gives a way to use the functions from the platform if needed (e.g., when loading a legacy save).  The performance is unaffected.
This requires to call the non-thread-safe `principia::numerics::_sin_cos::StaticInitialization` before calling `Sin` or `Cos`.
=> Use indirect calls for Sin and Cos

astronomy/orbit_analysis_test.cpp, astronomy/orbit_recurrence.hpp, astronomy/orbit_recurrence_body.hpp, astronomy/orbit_recurrence_test.cpp, ksp_plugin/orbit_analyser.cpp, testing_utilities/matchers.hpp
`ClosestRecurrence` now returns an error status if it trips on a floating-point value that cannot be represented as in `int`.
Fix #3831, #4162.
=> Detect UB in conversion of floats to integers during orbit analysis

physics/barycentric_rotating_reference_frame.hpp, physics/barycentric_rotating_reference_frame_body.hpp, physics/ephemeris.hpp, physics/ephemeris_body.hpp
For the rotating-pulsating frame it can result in a 2x speedup if there are many bodies in the frame.
Before:
```
CPU Caches:
------------------------------------------------------------------------------------------
Benchmark                                                Time             CPU   Iterations
------------------------------------------------------------------------------------------
BM_BodyCentredNonRotatingReferenceFrame/1024001        279 ms          281 ms            3
BM_BarycentricRotatingReferenceFrame/1024001          3965 ms         3953 ms            1
BM_RotatingPulsatingReferenceFrame/1024001           51332 ms        51297 ms …
```
=> Avoid the repeated computation of positions in the barycentric reference frame

ksp_plugin_test/flight_plan_optimizer_test.cpp, tools/journal_proto_processor.cpp
Apparently the latest greatest Windows 11 (26100.3476?) has changed the elementary functions libraries and that affects the flight plan optimization tests.
=> Adjust the tolerances after upgrading Windows

google_glog.props, google_protobuf.props, ksp_plugin_test/flight_plan_optimizer_test.cpp, principia.props, tools/journal_proto_processor.cpp
And pin it at 10.0.22621 (Windows 11 22H2), which is before before 10.0.26100 (Windows 11 24H2).
(There is no Windows 11 SDK for 10.0.22631, Windows 11 23H2).
Fix #4188.
This also gets rid of the separate glog.dll, libprotobuf.dll, and serialization.dll, which had been introduced in #1686.
=> Statically link the UCRT

base/status_utilities.hpp, benchmarks/planetarium_benchmark.cpp, ksp_plugin/interface_planetarium.cpp, ksp_plugin/planetarium.hpp, ksp_plugin/planetarium_body.hpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/mock_planetarium.hpp, ksp_plugin_test/mock_plugin.hpp, ksp_plugin_test/planetarium_test.cpp
This code plots the same equipotentials at various angular resolutions and determines (1) their cost, given by the total number of points produced; and (2) their quality, given by the Euclidean distance from the plot at the "correct" resolution (human visual accuracy).
For convenience, the plotted lines are turned into `DiscreteTrajectory` objects, as that makes it possible to evaluate them at any time.
The outcome is that the cost varies approximately like `1/Sqrt[resolution]` and the distance to the "correct" plot like `Sqrt[resolution]`.
Note that at this point there is no telling how the distance corresponds to the "pleasantness" of the graph.  That will need to be examined in game.
=> Evaluate the effect of the angular resolution on the cost and quality of PlotMethod3

mathematica/error_analysis_test.cpp, mathematica/integrator_plots.cpp, mathematica/mathematica.hpp, mathematica/mathematica_body.hpp, mathematica/mathematica_test.cpp, testing_utilities/integration.hpp, testing_utilities/integration_body.hpp
Following some refactoring of `mathematica`, the tool had been generating strings instead of lists of numbers.
Also:
1. provide data on _all_ integrators: both ABA and BAB for the SPRKs as SRKN (bringing the number of varieties of symplectic or conjugate symplectic integrators from 37 to 57), and plot the integrators that are neither symplectic nor conjugate symplectic too;
2. provide information on the types of integrators to make it easier to filter them in Mathematica for specific plots;
3. solve the same problem with the same settings for different final times so that the evolution of the error over time can be examined (in particular, this shows the effect of the (conjugate-)symplectic property).
=> Fix integrator plots

mathematica/error_analysis_test.cpp, mathematica/integrator_plots.cpp
I had written 1 / min_step_per_evaluation instead of 1.0 / min_step_per_evaluation when addressing https://github.com/mockingbirdnest/Principia/pull/4194#discussion_r2030054902, which broke the fixed-step graphs.
Also record energy error over time, instead of just the maximum.
=> Integrator plots: A bug and error history

integrators/ordinary_differential_equations.hpp, ksp_plugin_test/planetarium_test.cpp, physics/equipotential_body.hpp, physics/lagrange_equipotentials_body.hpp, physics/lagrange_equipotentials_test.cpp
The tolerance was too large, causing the integrator to jump over L1 and L2, and to produce equipotentials that were not closing.  This in turn was causing the plotting to waste work and to create visual artifacts.
This is not a complete solution though.  For the Pluto-Charon system, the tolerance would have to go down to (at least) 1 fm and would generate trajectories with 80,000 points, which is excessive.  For the stock system, there remain some visual artifacts to be investigated.
=> Tune the parameters of the integrator used for computing equipotentials

mathematica/floating_point.wl
No changes to the code, but some reordering so that the private part is in the same order as the public part.
Output:
=> Document the functions in package IEEE754FloatingPoint`

ksp_plugin/flight_plan.cpp, ksp_plugin/flight_plan.hpp
Also change the way that we pop segments to make it easier to enforce the invariant that the flight plan starts and ends with a coast.
Fix #4216.
=> Interrupt the analysers when recomputing a coast

ksp_plugin_adapter/reference_frame_selector.cs
I would like to propose the following change to the distance set when using the new feature for setting focus to a celestial body in the reference frame list. This would cause the distance after focus to no longer be the smallest possible, but rather give some room to better observe the surroundings of the body in the map view.
This came from personally getting a little bit annoyed by having to zoom out every time after using the focus button. I really appreciate the feature though. It's been a life saver since I run too many simulations and have to recreate plans every time.
This was tested locally, the images show how the bodies would be drawn with the new value. I think the ideal would having it be a setting so the user may set to whatever is preferred
=> Increase the distance after setting focus to a celestial body

mathematica/ieee754_floating_point_evaluation_test.wl
Also tighten the test of the error bounds of [SZ05].
#1760.
=> Fix a Mathematica test where random intervals were generated with insufficient precision

functions/sin_cos_test.cpp, numerics/sin_cos.cpp, numerics/sin_cos.hpp
This happens about once every 30,000 calls, which is rather higher than I would like.
#1760.
=> Add a callback to the Sin/Cos implementation to track fallback to CORE-MATH

astronomy/orbit_analysis_test.cpp, astronomy/лидов_古在_test.cpp, journal/player_test.cpp, ksp_plugin/plugin.cpp, ksp_plugin/plugin.hpp, ksp_plugin_test/interface_test.cpp, ksp_plugin_test/plugin_integration_test.cpp, ksp_plugin_test/plugin_test.cpp, numerics/elementary_functions.hpp, numerics/elementary_functions_body.hpp, numerics/poisson_series_test.cpp, numerics/quadrature_test.cpp, numerics/чебышёв_lobatto_body.hpp
1. Add a saver object to the plugin to restore the configuration of the elementary functions across creations/destructions of plugins.
2. Change the computation of the Lobatto points to always use the correctly-rounded implementation.
3. Tentatively change the tolerances on Linux and macOS.
#1760.
=> Make the tests hermetic

geometry/point.hpp, geometry/point_body.hpp, nanobenchmarks/nanobenchmarks.cpp, nanobenchmarks/nanobenchmarks.vcxproj, nanobenchmarks/nanobenchmarks.vcxproj.filters, principia.props
Also rename the unfortunately-named `examples.cpp` and enable assembly generation in `nanobenchmarks`: we often want to look at the code in this project.
#3019.
=> Remove copy constructors for Point that lead to inefficient code generation
